let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RXN0YWNpb25fY29tdW5hLEluZGljYWRvcixSZXN1bHRhZG8sTixQZWFyc29uLFNwZWFybWFuLExPT19taW4sTE9PX21heCxyX3Npbl8yMDE5XzIwMjENCkNoaW1iYXJvbmdvLExsdXZpYV9KSkEsRW1wbGVvX3ZlcmFub19PSGlnZ2lucyw5LC0wLjI4MTcxNjY4MDQwOTE0MTQ0LC0wLjI1LC0wLjQ2MTk0MjQwNTczOTAwMDYsLTAuMTIwMzE2MjU2ODA5OTY5MTIsLTAuMjk3MzY4NjUxOTkxNjE2Mw0KQ2hpbWJhcm9uZ28sTGx1dmlhX0pKQSxDYW1iaW9fZW1wbGVvX2ludGVyYW51YWwsOSwwLjA4NDkwNjU1MjQ2NTgwMDk1LDAuMDY2NjY2NjY2NjY2NjY2NjcsLTAuMzI1ODM4NTU1Mjk1NzE3NSwwLjQwODIyMjc0NzE5NDY0MjM1LC0wLjQ0NzYwNDExNDkyNDQ3MjA1DQpDaGltYmFyb25nbyxNYXgyNGhfSkpBLEVtcGxlb192ZXJhbm9fT0hpZ2dpbnMsOSwtMC41NDEzOTI5NjM1NDY3MzA5LC0wLjYsLTAuNzU3OTY3ODQ5MDQxMDIzNywtMC40NDAzNTA4Njc1Mzg1MzU2LC0wLjUyMzI1NDg1NDQ4OTUxNTgNCkNoaW1iYXJvbmdvLE1heDI0aF9KSkEsQ2FtYmlvX2VtcGxlb19pbnRlcmFudWFsLDksLTAuMDk2MDI0NzYxNjgyNzA1OCwwLjAsLTAuMzkzMTM2ODA5MzUwMjYxOTYsMC4yMDAyMjUzMzEyMDMwMDg1NiwtMC4zMzQ5ODk5MjUxNjI1MTE1DQpTYW4gRmVybmFuZG8sTGx1dmlhX0pKQSxFbXBsZW9fdmVyYW5vX09IaWdnaW5zLDgsLTAuMjYwODMwNTIyNTMyODM2LC0wLjM4MDk1MjM4MDk1MjM4MTA0LC0wLjQwOTQwOTQyNzA0MzcwMzgsLTAuMDA4MDQ3NjQzODgyNDEyODA2LC0wLjI4MTEwMzU2MzUxMTg0MzkNClNhbiBGZXJuYW5kbyxMbHV2aWFfSkpBLENhbWJpb19lbXBsZW9faW50ZXJhbnVhbCw4LDAuMzk0NzgzMDk3MzAxNzk0MiwwLjAyMzgwOTUyMzgwOTUyMzgxNSwtMC4wNjgwNTk1ODkzNzQ3NjQ4LDAuNTY4NDYwNTQwOTI3ODQ1OCwwLjAyODIwNzM4MzU3MDA4MTI0DQpTYW4gRmVybmFuZG8sTWF4MjRoX0pKQSxFbXBsZW9fdmVyYW5vX09IaWdnaW5zLDgsLTAuNTAyOTc1MDAzODkyNTEwOCwtMC41NDc2MTkwNDc2MTkwNDc3LC0wLjYyMzg0MzgxMTQyODE3MDksLTAuMzY0NTc3NDQ4OTQyNTI5MjUsLTAuNDU1MDUyNjkxMTc2NTkyNw0KU2FuIEZlcm5hbmRvLE1heDI0aF9KSkEsQ2FtYmlvX2VtcGxlb19pbnRlcmFudWFsLDgsMC4xMjc0NTU5NDAzOTE2OTY5NCwwLjAsLTAuMzU4MjA5MTUzOTQ2MDkzOTMsMC4zMjkzMzcyNzgzNjM3MjY0LDAuMDM2OTQ2MTA5NTk0ODI4OTcNCg==", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\Correlaciones.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Estacion_comuna", type text}, {"Indicador", type text}, {"Resultado", type text}, {"N", Int64.Type}, {"Pearson", type number}, {"Spearman", type number}, {"LOO_min", type number}, {"LOO_max", type number}, {"r_sin_2019_2021", type number}}, "en-US")
in Tipos