let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RmVjaGEsQW5pbyxNZXMsQW5pb01lcw0KMjAxMy0wMS0wMSwyMDEzLDEsMjAxMy0wMQ0KMjAxMy0wMi0wMSwyMDEzLDIsMjAxMy0wMg0KMjAxMy0wMy0wMSwyMDEzLDMsMjAxMy0wMw0KMjAxMy0wNC0wMSwyMDEzLDQsMjAxMy0wNA0KMjAxMy0wNS0wMSwyMDEzLDUsMjAxMy0wNQ0KMjAxMy0wNi0wMSwyMDEzLDYsMjAxMy0wNg0KMjAxMy0wNy0wMSwyMDEzLDcsMjAxMy0wNw0KMjAxMy0wOC0wMSwyMDEzLDgsMjAxMy0wOA0KMjAxMy0wOS0wMSwyMDEzLDksMjAxMy0wOQ0KMjAxMy0xMC0wMSwyMDEzLDEwLDIwMTMtMTANCjIwMTMtMTEtMDEsMjAxMywxMSwyMDEzLTExDQoyMDEzLTEyLTAxLDIwMTMsMTIsMjAxMy0xMg0KMjAxNC0wMS0wMSwyMDE0LDEsMjAxNC0wMQ0KMjAxNC0wMi0wMSwyMDE0LDIsMjAxNC0wMg0KMjAxNC0wMy0wMSwyMDE0LDMsMjAxNC0wMw0KMjAxNC0wNC0wMSwyMDE0LDQsMjAxNC0wNA0KMjAxNC0wNS0wMSwyMDE0LDUsMjAxNC0wNQ0KMjAxNC0wNi0wMSwyMDE0LDYsMjAxNC0wNg0KMjAxNC0wNy0wMSwyMDE0LDcsMjAxNC0wNw0KMjAxNC0wOC0wMSwyMDE0LDgsMjAxNC0wOA0KMjAxNC0wOS0wMSwyMDE0LDksMjAxNC0wOQ0KMjAxNC0xMC0wMSwyMDE0LDEwLDIwMTQtMTANCjIwMTQtMTEtMDEsMjAxNCwxMSwyMDE0LTExDQoyMDE0LTEyLTAxLDIwMTQsMTIsMjAxNC0xMg0KMjAxNS0wMS0wMSwyMDE1LDEsMjAxNS0wMQ0KMjAxNS0wMi0wMSwyMDE1LDIsMjAxNS0wMg0KMjAxNS0wMy0wMSwyMDE1LDMsMjAxNS0wMw0KMjAxNS0wNC0wMSwyMDE1LDQsMjAxNS0wNA0KMjAxNS0wNS0wMSwyMDE1LDUsMjAxNS0wNQ0KMjAxNS0wNi0wMSwyMDE1LDYsMjAxNS0wNg0KMjAxNS0wNy0wMSwyMDE1LDcsMjAxNS0wNw0KMjAxNS0wOC0wMSwyMDE1LDgsMjAxNS0wOA0KMjAxNS0wOS0wMSwyMDE1LDksMjAxNS0wOQ0KMjAxNS0xMC0wMSwyMDE1LDEwLDIwMTUtMTANCjIwMTUtMTEtMDEsMjAxNSwxMSwyMDE1LTExDQoyMDE1LTEyLTAxLDIwMTUsMTIsMjAxNS0xMg0KMjAxNi0wMS0wMSwyMDE2LDEsMjAxNi0wMQ0KMjAxNi0wMi0wMSwyMDE2LDIsMjAxNi0wMg0KMjAxNi0wMy0wMSwyMDE2LDMsMjAxNi0wMw0KMjAxNi0wNC0wMSwyMDE2LDQsMjAxNi0wNA0KMjAxNi0wNS0wMSwyMDE2LDUsMjAxNi0wNQ0KMjAxNi0wNi0wMSwyMDE2LDYsMjAxNi0wNg0KMjAxNi0wNy0wMSwyMDE2LDcsMjAxNi0wNw0KMjAxNi0wOC0wMSwyMDE2LDgsMjAxNi0wOA0KMjAxNi0wOS0wMSwyMDE2LDksMjAxNi0wOQ0KMjAxNi0xMC0wMSwyMDE2LDEwLDIwMTYtMTANCjIwMTYtMTEtMDEsMjAxNiwxMSwyMDE2LTExDQoyMDE2LTEyLTAxLDIwMTYsMTIsMjAxNi0xMg0KMjAxNy0wMS0wMSwyMDE3LDEsMjAxNy0wMQ0KMjAxNy0wMi0wMSwyMDE3LDIsMjAxNy0wMg0KMjAxNy0wMy0wMSwyMDE3LDMsMjAxNy0wMw0KMjAxNy0wNC0wMSwyMDE3LDQsMjAxNy0wNA0KMjAxNy0wNS0wMSwyMDE3LDUsMjAxNy0wNQ0KMjAxNy0wNi0wMSwyMDE3LDYsMjAxNy0wNg0KMjAxNy0wNy0wMSwyMDE3LDcsMjAxNy0wNw0KMjAxNy0wOC0wMSwyMDE3LDgsMjAxNy0wOA0KMjAxNy0wOS0wMSwyMDE3LDksMjAxNy0wOQ0KMjAxNy0xMC0wMSwyMDE3LDEwLDIwMTctMTANCjIwMTctMTEtMDEsMjAxNywxMSwyMDE3LTExDQoyMDE3LTEyLTAxLDIwMTcsMTIsMjAxNy0xMg0KMjAxOC0wMS0wMSwyMDE4LDEsMjAxOC0wMQ0KMjAxOC0wMi0wMSwyMDE4LDIsMjAxOC0wMg0KMjAxOC0wMy0wMSwyMDE4LDMsMjAxOC0wMw0KMjAxOC0wNC0wMSwyMDE4LDQsMjAxOC0wNA0KMjAxOC0wNS0wMSwyMDE4LDUsMjAxOC0wNQ0KMjAxOC0wNi0wMSwyMDE4LDYsMjAxOC0wNg0KMjAxOC0wNy0wMSwyMDE4LDcsMjAxOC0wNw0KMjAxOC0wOC0wMSwyMDE4LDgsMjAxOC0wOA0KMjAxOC0wOS0wMSwyMDE4LDksMjAxOC0wOQ0KMjAxOC0xMC0wMSwyMDE4LDEwLDIwMTgtMTANCjIwMTgtMTEtMDEsMjAxOCwxMSwyMDE4LTExDQoyMDE4LTEyLTAxLDIwMTgsMTIsMjAxOC0xMg0KMjAxOS0wMS0wMSwyMDE5LDEsMjAxOS0wMQ0KMjAxOS0wMi0wMSwyMDE5LDIsMjAxOS0wMg0KMjAxOS0wMy0wMSwyMDE5LDMsMjAxOS0wMw0KMjAxOS0wNC0wMSwyMDE5LDQsMjAxOS0wNA0KMjAxOS0wNS0wMSwyMDE5LDUsMjAxOS0wNQ0KMjAxOS0wNi0wMSwyMDE5LDYsMjAxOS0wNg0KMjAxOS0wNy0wMSwyMDE5LDcsMjAxOS0wNw0KMjAxOS0wOC0wMSwyMDE5LDgsMjAxOS0wOA0KMjAxOS0wOS0wMSwyMDE5LDksMjAxOS0wOQ0KMjAxOS0xMC0wMSwyMDE5LDEwLDIwMTktMTANCjIwMTktMTEtMDEsMjAxOSwxMSwyMDE5LTExDQoyMDE5LTEyLTAxLDIwMTksMTIsMjAxOS0xMg0KMjAyMC0wMS0wMSwyMDIwLDEsMjAyMC0wMQ0KMjAyMC0wMi0wMSwyMDIwLDIsMjAyMC0wMg0KMjAyMC0wMy0wMSwyMDIwLDMsMjAyMC0wMw0KMjAyMC0wNC0wMSwyMDIwLDQsMjAyMC0wNA0KMjAyMC0wNS0wMSwyMDIwLDUsMjAyMC0wNQ0KMjAyMC0wNi0wMSwyMDIwLDYsMjAyMC0wNg0KMjAyMC0wNy0wMSwyMDIwLDcsMjAyMC0wNw0KMjAyMC0wOC0wMSwyMDIwLDgsMjAyMC0wOA0KMjAyMC0wOS0wMSwyMDIwLDksMjAyMC0wOQ0KMjAyMC0xMC0wMSwyMDIwLDEwLDIwMjAtMTANCjIwMjAtMTEtMDEsMjAyMCwxMSwyMDIwLTExDQoyMDIwLTEyLTAxLDIwMjAsMTIsMjAyMC0xMg0KMjAyMS0wMS0wMSwyMDIxLDEsMjAyMS0wMQ0KMjAyMS0wMi0wMSwyMDIxLDIsMjAyMS0wMg0KMjAyMS0wMy0wMSwyMDIxLDMsMjAyMS0wMw0KMjAyMS0wNC0wMSwyMDIxLDQsMjAyMS0wNA0KMjAyMS0wNS0wMSwyMDIxLDUsMjAyMS0wNQ0KMjAyMS0wNi0wMSwyMDIxLDYsMjAyMS0wNg0KMjAyMS0wNy0wMSwyMDIxLDcsMjAyMS0wNw0KMjAyMS0wOC0wMSwyMDIxLDgsMjAyMS0wOA0KMjAyMS0wOS0wMSwyMDIxLDksMjAyMS0wOQ0KMjAyMS0xMC0wMSwyMDIxLDEwLDIwMjEtMTANCjIwMjEtMTEtMDEsMjAyMSwxMSwyMDIxLTExDQoyMDIxLTEyLTAxLDIwMjEsMTIsMjAyMS0xMg0KMjAyMi0wMS0wMSwyMDIyLDEsMjAyMi0wMQ0KMjAyMi0wMi0wMSwyMDIyLDIsMjAyMi0wMg0KMjAyMi0wMy0wMSwyMDIyLDMsMjAyMi0wMw0KMjAyMi0wNC0wMSwyMDIyLDQsMjAyMi0wNA0KMjAyMi0wNS0wMSwyMDIyLDUsMjAyMi0wNQ0KMjAyMi0wNi0wMSwyMDIyLDYsMjAyMi0wNg0KMjAyMi0wNy0wMSwyMDIyLDcsMjAyMi0wNw0KMjAyMi0wOC0wMSwyMDIyLDgsMjAyMi0wOA0KMjAyMi0wOS0wMSwyMDIyLDksMjAyMi0wOQ0KMjAyMi0xMC0wMSwyMDIyLDEwLDIwMjItMTANCjIwMjItMTEtMDEsMjAyMiwxMSwyMDIyLTExDQoyMDIyLTEyLTAxLDIwMjIsMTIsMjAyMi0xMg0KMjAyMy0wMS0wMSwyMDIzLDEsMjAyMy0wMQ0KMjAyMy0wMi0wMSwyMDIzLDIsMjAyMy0wMg0KMjAyMy0wMy0wMSwyMDIzLDMsMjAyMy0wMw0KMjAyMy0wNC0wMSwyMDIzLDQsMjAyMy0wNA0KMjAyMy0wNS0wMSwyMDIzLDUsMjAyMy0wNQ0KMjAyMy0wNi0wMSwyMDIzLDYsMjAyMy0wNg0KMjAyMy0wNy0wMSwyMDIzLDcsMjAyMy0wNw0KMjAyMy0wOC0wMSwyMDIzLDgsMjAyMy0wOA0KMjAyMy0wOS0wMSwyMDIzLDksMjAyMy0wOQ0KMjAyMy0xMC0wMSwyMDIzLDEwLDIwMjMtMTANCjIwMjMtMTEtMDEsMjAyMywxMSwyMDIzLTExDQoyMDIzLTEyLTAxLDIwMjMsMTIsMjAyMy0xMg0KMjAyNC0wMS0wMSwyMDI0LDEsMjAyNC0wMQ0KMjAyNC0wMi0wMSwyMDI0LDIsMjAyNC0wMg0KMjAyNC0wMy0wMSwyMDI0LDMsMjAyNC0wMw0KMjAyNC0wNC0wMSwyMDI0LDQsMjAyNC0wNA0KMjAyNC0wNS0wMSwyMDI0LDUsMjAyNC0wNQ0KMjAyNC0wNi0wMSwyMDI0LDYsMjAyNC0wNg0KMjAyNC0wNy0wMSwyMDI0LDcsMjAyNC0wNw0KMjAyNC0wOC0wMSwyMDI0LDgsMjAyNC0wOA0KMjAyNC0wOS0wMSwyMDI0LDksMjAyNC0wOQ0KMjAyNC0xMC0wMSwyMDI0LDEwLDIwMjQtMTANCjIwMjQtMTEtMDEsMjAyNCwxMSwyMDI0LTExDQoyMDI0LTEyLTAxLDIwMjQsMTIsMjAyNC0xMg0KMjAyNS0wMS0wMSwyMDI1LDEsMjAyNS0wMQ0KMjAyNS0wMi0wMSwyMDI1LDIsMjAyNS0wMg0KMjAyNS0wMy0wMSwyMDI1LDMsMjAyNS0wMw0KMjAyNS0wNC0wMSwyMDI1LDQsMjAyNS0wNA0KMjAyNS0wNS0wMSwyMDI1LDUsMjAyNS0wNQ0KMjAyNS0wNi0wMSwyMDI1LDYsMjAyNS0wNg0KMjAyNS0wNy0wMSwyMDI1LDcsMjAyNS0wNw0KMjAyNS0wOC0wMSwyMDI1LDgsMjAyNS0wOA0KMjAyNS0wOS0wMSwyMDI1LDksMjAyNS0wOQ0KMjAyNS0xMC0wMSwyMDI1LDEwLDIwMjUtMTANCjIwMjUtMTEtMDEsMjAyNSwxMSwyMDI1LTExDQoyMDI1LTEyLTAxLDIwMjUsMTIsMjAyNS0xMg0KMjAyNi0wMS0wMSwyMDI2LDEsMjAyNi0wMQ0KMjAyNi0wMi0wMSwyMDI2LDIsMjAyNi0wMg0KMjAyNi0wMy0wMSwyMDI2LDMsMjAyNi0wMw0KMjAyNi0wNC0wMSwyMDI2LDQsMjAyNi0wNA0KMjAyNi0wNS0wMSwyMDI2LDUsMjAyNi0wNQ0KMjAyNi0wNi0wMSwyMDI2LDYsMjAyNi0wNg0KMjAyNi0wNy0wMSwyMDI2LDcsMjAyNi0wNw0KMjAyNi0wOC0wMSwyMDI2LDgsMjAyNi0wOA0KMjAyNi0wOS0wMSwyMDI2LDksMjAyNi0wOQ0KMjAyNi0xMC0wMSwyMDI2LDEwLDIwMjYtMTANCjIwMjYtMTEtMDEsMjAyNiwxMSwyMDI2LTExDQoyMDI2LTEyLTAxLDIwMjYsMTIsMjAyNi0xMg0KMjAyNy0wMS0wMSwyMDI3LDEsMjAyNy0wMQ0KMjAyNy0wMi0wMSwyMDI3LDIsMjAyNy0wMg0KMjAyNy0wMy0wMSwyMDI3LDMsMjAyNy0wMw0KMjAyNy0wNC0wMSwyMDI3LDQsMjAyNy0wNA0KMjAyNy0wNS0wMSwyMDI3LDUsMjAyNy0wNQ0KMjAyNy0wNi0wMSwyMDI3LDYsMjAyNy0wNg0KMjAyNy0wNy0wMSwyMDI3LDcsMjAyNy0wNw0KMjAyNy0wOC0wMSwyMDI3LDgsMjAyNy0wOA0KMjAyNy0wOS0wMSwyMDI3LDksMjAyNy0wOQ0KMjAyNy0xMC0wMSwyMDI3LDEwLDIwMjctMTANCjIwMjctMTEtMDEsMjAyNywxMSwyMDI3LTExDQoyMDI3LTEyLTAxLDIwMjcsMTIsMjAyNy0xMg0K", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\DimFecha.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type datetime}, {"Anio", Int64.Type}, {"Mes", Int64.Type}, {"AnioMes", type text}}, "en-US")
in Tipos