let
    Binario = if RutaDatos = "" then Binary.FromText("77u/QW5pbyxDVVQsQ29tdW5hLFNlY3RvcixFbXByZXNhcyxWZW50YXNfVUZfb2JzZXJ2YWRhcyxDZWxkYXNfdmVudGFzX3N1cHJpbWlkYXMNCjIwMjEsMDYzMDEsU2FuIEZlcm5hbmRvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsNjgsNDg1OTQ1LjAsMw0KMjAyMSwwNjMwMSxTYW4gRmVybmFuZG8sT3Ryb3Mgc2VjdG9yZXMsNTIwMCwyNjYyMDYyNC4wLDI2MQ0KMjAyMSwwNjMwMSxTYW4gRmVybmFuZG8sUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDIsLDENCjIwMjEsMDYzMDEsU2FuIEZlcm5hbmRvLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSw1MjQsNDMzNTU1Ni4wLDE2DQoyMDIxLDA2MzAxLFNhbiBGZXJuYW5kbyxTZXJ2aWNpb3MgYWdyw61jb2xhcywxODUsMTUxNjA1MS4wLDINCjIwMjEsMDYzMDEsU2FuIEZlcm5hbmRvLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsNDAwLDk5NjczMC4wLDINCjIwMjEsMDYzMDIsQ2jDqXBpY2EsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwxNCwxNTE1Ni4wLDINCjIwMjEsMDYzMDIsQ2jDqXBpY2EsT3Ryb3Mgc2VjdG9yZXMsNzUwLDI0MTc5MS4wLDE0NA0KMjAyMSwwNjMwMixDaMOpcGljYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMSwwNjMwMixDaMOpcGljYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNTIxLDEyMzQyMTYuMCwxNw0KMjAyMSwwNjMwMixDaMOpcGljYSxTZXJ2aWNpb3MgYWdyw61jb2xhcyw3MiwzMDc4OTAuMCwyDQoyMDIxLDA2MzAyLENow6lwaWNhLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTE4LDEzMzQxOS4wLDANCjIwMjEsMDYzMDMsQ2hpbWJhcm9uZ28sQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwyNCwxMzc4Ny4wLDMNCjIwMjEsMDYzMDMsQ2hpbWJhcm9uZ28sT3Ryb3Mgc2VjdG9yZXMsMTc2OCwxNTQ2MzcxLjAsMjA2DQoyMDIxLDA2MzAzLENoaW1iYXJvbmdvLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwxMDg3LDQyNDI4ODkuMCwxOQ0KMjAyMSwwNjMwMyxDaGltYmFyb25nbyxTZXJ2aWNpb3MgYWdyw61jb2xhcywxNTIsNjUxNDcwLjAsMQ0KMjAyMSwwNjMwMyxDaGltYmFyb25nbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDIxMiw0NjczMzUuMCwxDQoyMDIxLDA2MzA0LExvbG9sLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMiwsMQ0KMjAyMSwwNjMwNCxMb2xvbCxPdHJvcyBzZWN0b3Jlcyw0NzYsNjg4NjA1LjAsMTE1DQoyMDIxLDA2MzA0LExvbG9sLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDIxLDA2MzA0LExvbG9sLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwyMDEsNzQwOTU1LjAsMTkNCjIwMjEsMDYzMDQsTG9sb2wsU2VydmljaW9zIGFncsOtY29sYXMsNjcsMzY4OTcwLjAsMQ0KMjAyMSwwNjMwNCxMb2xvbCxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDMxLDM2NjgyLjAsMA0KMjAyMSwwNjMwNSxOYW5jYWd1YSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDE0LCwzDQoyMDIxLDA2MzA1LE5hbmNhZ3VhLE90cm9zIHNlY3RvcmVzLDEwMjYsMjY2MTAxOC4wLDE3Mw0KMjAyMSwwNjMwNSxOYW5jYWd1YSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMiwsMQ0KMjAyMSwwNjMwNSxOYW5jYWd1YSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMjg5LDIyMjkwNDMuMCwxOA0KMjAyMSwwNjMwNSxOYW5jYWd1YSxTZXJ2aWNpb3MgYWdyw61jb2xhcyw2OCw5NTA4NDUuMCwxDQoyMDIxLDA2MzA1LE5hbmNhZ3VhLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTA5LDI1NzgwMy4wLDANCjIwMjEsMDYzMDYsUGFsbWlsbGEsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwxNSwsNA0KMjAyMSwwNjMwNixQYWxtaWxsYSxPdHJvcyBzZWN0b3Jlcyw3MDYsNDQ1NzI0Mi4wLDEzNQ0KMjAyMSwwNjMwNixQYWxtaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMSwwNjMwNixQYWxtaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNDUxLDEyOTc0NTYuMCwxOA0KMjAyMSwwNjMwNixQYWxtaWxsYSxTZXJ2aWNpb3MgYWdyw61jb2xhcywxMDEsNDA0MjA1LjAsMg0KMjAyMSwwNjMwNixQYWxtaWxsYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDgzLDE3MDE4My4wLDANCjIwMjEsMDYzMDcsUGVyYWxpbGxvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMTEsLDQNCjIwMjEsMDYzMDcsUGVyYWxpbGxvLE90cm9zIHNlY3RvcmVzLDcyNyw1MTc1MDguMCwxNTQNCjIwMjEsMDYzMDcsUGVyYWxpbGxvLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDIxLDA2MzA3LFBlcmFsaWxsbyxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMjY0LDgwNzQxOS4wLDIwDQoyMDIxLDA2MzA3LFBlcmFsaWxsbyxTZXJ2aWNpb3MgYWdyw61jb2xhcyw3OCwyNzEwNzYuMCwyDQoyMDIxLDA2MzA3LFBlcmFsaWxsbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDY2LDkzODkyLjAsMQ0KMjAyMSwwNjMwOCxQbGFjaWxsYSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDExLCwzDQoyMDIxLDA2MzA4LFBsYWNpbGxhLE90cm9zIHNlY3RvcmVzLDM4MiwxMjcxNzYuMCwxMjINCjIwMjEsMDYzMDgsUGxhY2lsbGEsUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDEsLDENCjIwMjEsMDYzMDgsUGxhY2lsbGEsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDMzOCwxMzAyODQ0LjAsMTcNCjIwMjEsMDYzMDgsUGxhY2lsbGEsU2VydmljaW9zIGFncsOtY29sYXMsNTcsMTg3MDc3LjAsMQ0KMjAyMSwwNjMwOCxQbGFjaWxsYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDY3LDgzNzA2LjAsMA0KMjAyMSwwNjMwOSxQdW1hbnF1ZSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDIsLDINCjIwMjEsMDYzMDksUHVtYW5xdWUsT3Ryb3Mgc2VjdG9yZXMsMjE2LDY3ODAzLjAsNjYNCjIwMjEsMDYzMDksUHVtYW5xdWUsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDExOSw2MjU2LjAsMjQNCjIwMjEsMDYzMDksUHVtYW5xdWUsU2VydmljaW9zIGFncsOtY29sYXMsMTUsMTc0MDYuMCwwDQoyMDIxLDA2MzA5LFB1bWFucXVlLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTMsMTM2NTAuMCwwDQoyMDIxLDA2MzEwLFNhbnRhIENydXosQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCw0MCw1Mjg1NjQuMCw0DQoyMDIxLDA2MzEwLFNhbnRhIENydXosT3Ryb3Mgc2VjdG9yZXMsMzQxNSwxNDI1OTYxNy4wLDIzNg0KMjAyMSwwNjMxMCxTYW50YSBDcnV6LFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcyw1LCwxDQoyMDIxLDA2MzEwLFNhbnRhIENydXosUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDQ5MCwxNzgyNDU1LjAsMjENCjIwMjEsMDYzMTAsU2FudGEgQ3J1eixTZXJ2aWNpb3MgYWdyw61jb2xhcywyMTksMTM5MTQ5OC4wLDINCjIwMjEsMDYzMTAsU2FudGEgQ3J1eixUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDIyNiw0NzYwNjQuMCwwDQoyMDIyLDA2MzAxLFNhbiBGZXJuYW5kbyxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDczLDcxMTA5Mi4wLDMNCjIwMjIsMDYzMDEsU2FuIEZlcm5hbmRvLE90cm9zIHNlY3RvcmVzLDU0NDcsMjkyMjgyMDEuMCwyNDANCjIwMjIsMDYzMDEsU2FuIEZlcm5hbmRvLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywzLCwxDQoyMDIyLDA2MzAxLFNhbiBGZXJuYW5kbyxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNTQ1LDQyMDM0ODIuMCwxOA0KMjAyMiwwNjMwMSxTYW4gRmVybmFuZG8sU2VydmljaW9zIGFncsOtY29sYXMsMTc3LDIxNjkyNjMuMCwyDQoyMDIyLDA2MzAxLFNhbiBGZXJuYW5kbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDQyMyw5NDM5MjIuMCwyDQoyMDIyLDA2MzAyLENow6lwaWNhLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMTYsMjM5MzYuMCwyDQoyMDIyLDA2MzAyLENow6lwaWNhLE90cm9zIHNlY3RvcmVzLDc3OSwyNDA3NTguMCwxNDgNCjIwMjIsMDYzMDIsQ2jDqXBpY2EsUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDEsLDENCjIwMjIsMDYzMDIsQ2jDqXBpY2EsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDU3NywxNzg2MzA0LjAsMjANCjIwMjIsMDYzMDIsQ2jDqXBpY2EsU2VydmljaW9zIGFncsOtY29sYXMsODIsMzg0MTU1LjAsMQ0KMjAyMiwwNjMwMixDaMOpcGljYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDEyNCwxNTU1MzAuMCwwDQoyMDIyLDA2MzAzLENoaW1iYXJvbmdvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsNDMsMTA3MjI1LjAsMw0KMjAyMiwwNjMwMyxDaGltYmFyb25nbyxPdHJvcyBzZWN0b3JlcywxNzg5LDE1NjI2MTQuMCwyMDgNCjIwMjIsMDYzMDMsQ2hpbWJhcm9uZ28sUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDExMTIsMzk4MDcwOS4wLDE4DQoyMDIyLDA2MzAzLENoaW1iYXJvbmdvLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDE2OCw2NjM3NjUuMCwyDQoyMDIyLDA2MzAzLENoaW1iYXJvbmdvLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTk5LDQzMzU5Mi4wLDENCjIwMjIsMDYzMDQsTG9sb2wsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwxLCwxDQoyMDIyLDA2MzA0LExvbG9sLE90cm9zIHNlY3RvcmVzLDUxNiw2Njc5NzguMCwxMjUNCjIwMjIsMDYzMDQsTG9sb2wsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDIyNywxMDI5OTIwLjAsMTkNCjIwMjIsMDYzMDQsTG9sb2wsU2VydmljaW9zIGFncsOtY29sYXMsNzYsNTA5OTA5LjAsMQ0KMjAyMiwwNjMwNCxMb2xvbCxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDMyLDQ1NDE0LjAsMA0KMjAyMiwwNjMwNSxOYW5jYWd1YSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDEyLCwzDQoyMDIyLDA2MzA1LE5hbmNhZ3VhLE90cm9zIHNlY3RvcmVzLDEwNjIsMzE3ODc1Mi4wLDE4Mw0KMjAyMiwwNjMwNSxOYW5jYWd1YSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMywsMQ0KMjAyMiwwNjMwNSxOYW5jYWd1YSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMzA3LDE5MDc3OTMuMCwyNA0KMjAyMiwwNjMwNSxOYW5jYWd1YSxTZXJ2aWNpb3MgYWdyw61jb2xhcyw3MywzNjk1OTguMCwwDQoyMDIyLDA2MzA1LE5hbmNhZ3VhLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTA0LDIwMDU5Ni4wLDANCjIwMjIsMDYzMDYsUGFsbWlsbGEsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwxNSwsMw0KMjAyMiwwNjMwNixQYWxtaWxsYSxPdHJvcyBzZWN0b3Jlcyw3MDMsMzkwNzA5Mi4wLDEzMg0KMjAyMiwwNjMwNixQYWxtaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMiwwNjMwNixQYWxtaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNDk1LDEzOTgyMDEuMCwxOA0KMjAyMiwwNjMwNixQYWxtaWxsYSxTZXJ2aWNpb3MgYWdyw61jb2xhcywxMDAsMzgxOTE5LjAsMg0KMjAyMiwwNjMwNixQYWxtaWxsYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDgzLDMyNTAxNS4wLDENCjIwMjIsMDYzMDcsUGVyYWxpbGxvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMTUsLDQNCjIwMjIsMDYzMDcsUGVyYWxpbGxvLE90cm9zIHNlY3RvcmVzLDczNiw1NTI1NDMuMCwxNTENCjIwMjIsMDYzMDcsUGVyYWxpbGxvLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDIyLDA2MzA3LFBlcmFsaWxsbyxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMjgyLDk0MTI1Ny4wLDIyDQoyMDIyLDA2MzA3LFBlcmFsaWxsbyxTZXJ2aWNpb3MgYWdyw61jb2xhcyw5MCwyNzkzNDkuMCwyDQoyMDIyLDA2MzA3LFBlcmFsaWxsbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDYyLDk5NzEzLjAsMA0KMjAyMiwwNjMwOCxQbGFjaWxsYSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDE0LCwzDQoyMDIyLDA2MzA4LFBsYWNpbGxhLE90cm9zIHNlY3RvcmVzLDM5Nyw5NzI0OS4wLDEyMA0KMjAyMiwwNjMwOCxQbGFjaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMiwwNjMwOCxQbGFjaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMzU2LDg4MTQyNC4wLDE5DQoyMDIyLDA2MzA4LFBsYWNpbGxhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDU3LDIzMTE0NS4wLDINCjIwMjIsMDYzMDgsUGxhY2lsbGEsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCw2MSw4MDA3OS4wLDANCjIwMjIsMDYzMDksUHVtYW5xdWUsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwyLCwyDQoyMDIyLDA2MzA5LFB1bWFucXVlLE90cm9zIHNlY3RvcmVzLDIzOCw2MzA2NC4wLDc5DQoyMDIyLDA2MzA5LFB1bWFucXVlLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwxMjEsNTQ4NjcuMCwyMQ0KMjAyMiwwNjMwOSxQdW1hbnF1ZSxTZXJ2aWNpb3MgYWdyw61jb2xhcywxOSwxNTgwMC4wLDANCjIwMjIsMDYzMDksUHVtYW5xdWUsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCwxMiw1OTIyLjAsMA0KMjAyMiwwNjMxMCxTYW50YSBDcnV6LENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsNDQsMjk0MjUzLjAsNA0KMjAyMiwwNjMxMCxTYW50YSBDcnV6LE90cm9zIHNlY3RvcmVzLDM1NDEsMTMzNDQ0MjEuMCwyMzQNCjIwMjIsMDYzMTAsU2FudGEgQ3J1eixQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsNCwsMQ0KMjAyMiwwNjMxMCxTYW50YSBDcnV6LFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSw1NDEsMjUxMDk3Mi4wLDIyDQoyMDIyLDA2MzEwLFNhbnRhIENydXosU2VydmljaW9zIGFncsOtY29sYXMsMjMyLDE0MzcyMDMuMCwyDQoyMDIyLDA2MzEwLFNhbnRhIENydXosVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCwyMjcsNTc4MzUzLjAsMQ0KMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCw3MywzODAzMzIuMCwzDQoyMDIzLDA2MzAxLFNhbiBGZXJuYW5kbyxPdHJvcyBzZWN0b3Jlcyw1NTI4LDI0MTE5OTA2LjAsMjQ1DQoyMDIzLDA2MzAxLFNhbiBGZXJuYW5kbyxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsNCwsMQ0KMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDUyNSw0MTg2NjU1LjAsMTcNCjIwMjMsMDYzMDEsU2FuIEZlcm5hbmRvLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDE4MCwxNzY4NTQ2LjAsMQ0KMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCw0MzYsOTU1NTU3LjAsMg0KMjAyMywwNjMwMixDaMOpcGljYSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDIwLDE4NjM1LjAsMw0KMjAyMywwNjMwMixDaMOpcGljYSxPdHJvcyBzZWN0b3Jlcyw4MDcsMzIyMzgwLjAsMTUyDQoyMDIzLDA2MzAyLENow6lwaWNhLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDIzLDA2MzAyLENow6lwaWNhLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSw1NjEsMTM5MTIwOC4wLDE4DQoyMDIzLDA2MzAyLENow6lwaWNhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDg2LDM4OTgxNi4wLDENCjIwMjMsMDYzMDIsQ2jDqXBpY2EsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCwxMjksMTI5MDYxLjAsMA0KMjAyMywwNjMwMyxDaGltYmFyb25nbyxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDM0LDEyMjg0Ni4wLDINCjIwMjMsMDYzMDMsQ2hpbWJhcm9uZ28sT3Ryb3Mgc2VjdG9yZXMsMTgwNSwxNDQ3NTg0LjAsMTkyDQoyMDIzLDA2MzAzLENoaW1iYXJvbmdvLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwxMDgyLDM5ODc4NDcuMCwyMA0KMjAyMywwNjMwMyxDaGltYmFyb25nbyxTZXJ2aWNpb3MgYWdyw61jb2xhcywxNjgsNzE2NDQyLjAsMg0KMjAyMywwNjMwMyxDaGltYmFyb25nbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDE5OCw0MDI5NjkuMCwxDQoyMDIzLDA2MzA0LExvbG9sLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMywsMw0KMjAyMywwNjMwNCxMb2xvbCxPdHJvcyBzZWN0b3Jlcyw1MzgsNzk0NDI5LjAsMTI4DQoyMDIzLDA2MzA0LExvbG9sLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwyMzEsNzg1OTM3LjAsMTkNCjIwMjMsMDYzMDQsTG9sb2wsU2VydmljaW9zIGFncsOtY29sYXMsNzMsMzE0NzY4LjAsMQ0KMjAyMywwNjMwNCxMb2xvbCxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDMwLDM1MzQwLjAsMA0KMjAyMywwNjMwNSxOYW5jYWd1YSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDE1LCw0DQoyMDIzLDA2MzA1LE5hbmNhZ3VhLE90cm9zIHNlY3RvcmVzLDEwNzgsMTIyOTQ1MS4wLDE3NQ0KMjAyMywwNjMwNSxOYW5jYWd1YSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMiwsMQ0KMjAyMywwNjMwNSxOYW5jYWd1YSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMzAzLDE0NTU1ODguMCwyNA0KMjAyMywwNjMwNSxOYW5jYWd1YSxTZXJ2aWNpb3MgYWdyw61jb2xhcyw3NCwyMTk5OTguMCwxDQoyMDIzLDA2MzA1LE5hbmNhZ3VhLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTA0LDIyMDE3NC4wLDANCjIwMjMsMDYzMDYsUGFsbWlsbGEsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwxMywsMw0KMjAyMywwNjMwNixQYWxtaWxsYSxPdHJvcyBzZWN0b3Jlcyw3MDAsMjQ3NjEyMC4wLDEzNw0KMjAyMywwNjMwNixQYWxtaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMywwNjMwNixQYWxtaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNTAwLDExNDAzOTUuMCwyMQ0KMjAyMywwNjMwNixQYWxtaWxsYSxTZXJ2aWNpb3MgYWdyw61jb2xhcywxMDEsMzQ4Mzk4LjAsMg0KMjAyMywwNjMwNixQYWxtaWxsYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDgzLDIxNjI5Mi4wLDENCjIwMjMsMDYzMDcsUGVyYWxpbGxvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMTIsLDQNCjIwMjMsMDYzMDcsUGVyYWxpbGxvLE90cm9zIHNlY3RvcmVzLDc3Myw1OTI1MTMuMCwxNjANCjIwMjMsMDYzMDcsUGVyYWxpbGxvLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDIzLDA2MzA3LFBlcmFsaWxsbyxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMjc0LDgxMDY0OC4wLDIwDQoyMDIzLDA2MzA3LFBlcmFsaWxsbyxTZXJ2aWNpb3MgYWdyw61jb2xhcywxMDAsMjQ4MjI2LjAsMQ0KMjAyMywwNjMwNyxQZXJhbGlsbG8sVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCw2OSwxMTY5NzAuMCwwDQoyMDIzLDA2MzA4LFBsYWNpbGxhLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMTUsLDMNCjIwMjMsMDYzMDgsUGxhY2lsbGEsT3Ryb3Mgc2VjdG9yZXMsNDA3LDEwNTc0OC4wLDEzMQ0KMjAyMywwNjMwOCxQbGFjaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyMywwNjMwOCxQbGFjaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMzQ3LDc5MDkzMS4wLDE5DQoyMDIzLDA2MzA4LFBsYWNpbGxhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDY0LDE4Njg4OS4wLDENCjIwMjMsMDYzMDgsUGxhY2lsbGEsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCw2MCw3MTY5NS4wLDANCjIwMjMsMDYzMDksUHVtYW5xdWUsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwzLCwzDQoyMDIzLDA2MzA5LFB1bWFucXVlLE90cm9zIHNlY3RvcmVzLDI3OCw3MTU2ODUuMCw4MA0KMjAyMywwNjMwOSxQdW1hbnF1ZSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMTIxLDc1MTgwLjAsMTkNCjIwMjMsMDYzMDksUHVtYW5xdWUsU2VydmljaW9zIGFncsOtY29sYXMsMjMsMTc3MzMuMCwwDQoyMDIzLDA2MzA5LFB1bWFucXVlLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTIsNTM1Mi4wLDANCjIwMjMsMDYzMTAsU2FudGEgQ3J1eixDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDQxLDExNTYwMy4wLDQNCjIwMjMsMDYzMTAsU2FudGEgQ3J1eixPdHJvcyBzZWN0b3JlcywzNTg4LDExNDg3NjkyLjAsMjQzDQoyMDIzLDA2MzEwLFNhbnRhIENydXosUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDMsLDENCjIwMjMsMDYzMTAsU2FudGEgQ3J1eixQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNTEyLDE4MDYwMDcuMCwyMQ0KMjAyMywwNjMxMCxTYW50YSBDcnV6LFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDI0OCwxMTgxMDcxLjAsMg0KMjAyMywwNjMxMCxTYW50YSBDcnV6LFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMjIzLDU2NTA3OS4wLDANCjIwMjQsMDYzMDEsU2FuIEZlcm5hbmRvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsNzQsNzU4MTAwLjAsMw0KMjAyNCwwNjMwMSxTYW4gRmVybmFuZG8sT3Ryb3Mgc2VjdG9yZXMsNTY3OSwyODQzNDI4MS4wLDI0NQ0KMjAyNCwwNjMwMSxTYW4gRmVybmFuZG8sUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDMsLDENCjIwMjQsMDYzMDEsU2FuIEZlcm5hbmRvLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSw1MTMsNTQ4NjE4OS4wLDE4DQoyMDI0LDA2MzAxLFNhbiBGZXJuYW5kbyxTZXJ2aWNpb3MgYWdyw61jb2xhcywxODQsMTczNDM2Ni4wLDENCjIwMjQsMDYzMDEsU2FuIEZlcm5hbmRvLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsNDM0LDEwODkxODkuMCwyDQoyMDI0LDA2MzAyLENow6lwaWNhLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsMjIsNDQyNjEuMCwyDQoyMDI0LDA2MzAyLENow6lwaWNhLE90cm9zIHNlY3RvcmVzLDg2NCwzNjAyNTEuMCwxNjYNCjIwMjQsMDYzMDIsQ2jDqXBpY2EsUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDEsLDENCjIwMjQsMDYzMDIsQ2jDqXBpY2EsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDU2NiwxNTA2MzQ1LjAsMjANCjIwMjQsMDYzMDIsQ2jDqXBpY2EsU2VydmljaW9zIGFncsOtY29sYXMsOTQsMzcwNDM2LjAsMQ0KMjAyNCwwNjMwMixDaMOpcGljYSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDEyOCwxNDI0NjYuMCwwDQoyMDI0LDA2MzAzLENoaW1iYXJvbmdvLENvbWVyY2lvIGFncm9hbGltZW50YXJpbyBwb3RlbmNpYWwsNDIsMjE4MDY4LjAsMw0KMjAyNCwwNjMwMyxDaGltYmFyb25nbyxPdHJvcyBzZWN0b3JlcywxODY5LDE2NTQ2NjIuMCwyMDgNCjIwMjQsMDYzMDMsQ2hpbWJhcm9uZ28sUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDExMjYsNTE3MTU5NS4wLDIxDQoyMDI0LDA2MzAzLENoaW1iYXJvbmdvLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDE5Myw4Nzk4NzMuMCwxDQoyMDI0LDA2MzAzLENoaW1iYXJvbmdvLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMTk3LDQyODk3Ny4wLDENCjIwMjQsMDYzMDQsTG9sb2wsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwzLCwyDQoyMDI0LDA2MzA0LExvbG9sLE90cm9zIHNlY3RvcmVzLDYwMCwxMTA4NTI4LjAsMTMwDQoyMDI0LDA2MzA0LExvbG9sLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwyMjUsOTgxNjM0LjAsMTgNCjIwMjQsMDYzMDQsTG9sb2wsU2VydmljaW9zIGFncsOtY29sYXMsNzUsNTg0ODk3LjAsMQ0KMjAyNCwwNjMwNCxMb2xvbCxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDMyLDQ2Mjg4LjAsMA0KMjAyNCwwNjMwNSxOYW5jYWd1YSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDE2LDEwNzEzNi4wLDMNCjIwMjQsMDYzMDUsTmFuY2FndWEsT3Ryb3Mgc2VjdG9yZXMsMTE0OSwxNDMyNTY4LjAsMTg0DQoyMDI0LDA2MzA1LE5hbmNhZ3VhLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywzLCwxDQoyMDI0LDA2MzA1LE5hbmNhZ3VhLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwzMDIsMTg3NzM0MC4wLDIyDQoyMDI0LDA2MzA1LE5hbmNhZ3VhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDgwLDMzODIyMi4wLDENCjIwMjQsMDYzMDUsTmFuY2FndWEsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCwxMTcsMjQyNzU4LjAsMA0KMjAyNCwwNjMwNixQYWxtaWxsYSxDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDEyLCwzDQoyMDI0LDA2MzA2LFBhbG1pbGxhLE90cm9zIHNlY3RvcmVzLDc0OSwyMDI3NDg5LjAsMTQwDQoyMDI0LDA2MzA2LFBhbG1pbGxhLFByb2Nlc2FtaWVudG8gZnJ1dGFzIHkgaG9ydGFsaXphcywxLCwxDQoyMDI0LDA2MzA2LFBhbG1pbGxhLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSw0OTcsMTQ0MzcwMi4wLDIyDQoyMDI0LDA2MzA2LFBhbG1pbGxhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDExMiw0MDM4OTYuMCwyDQoyMDI0LDA2MzA2LFBhbG1pbGxhLFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsOTAsMjQ3MjAzLjAsMQ0KMjAyNCwwNjMwNyxQZXJhbGlsbG8sQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCw2LCw0DQoyMDI0LDA2MzA3LFBlcmFsaWxsbyxPdHJvcyBzZWN0b3Jlcyw4MjYsMTg2NTk4MC4wLDE2Ng0KMjAyNCwwNjMwNyxQZXJhbGlsbG8sUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDEsLDENCjIwMjQsMDYzMDcsUGVyYWxpbGxvLFByb2R1Y2Npw7NuIGFncm9wZWN1YXJpYSwyNzQsNjgzMzE5LjAsMjANCjIwMjQsMDYzMDcsUGVyYWxpbGxvLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDEwMywzMTAyNzUuMCwyDQoyMDI0LDA2MzA3LFBlcmFsaWxsbyxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDc4LDExOTA2Ni4wLDENCjIwMjQsMDYzMDgsUGxhY2lsbGEsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwyMyw3Mzg0Mi4wLDINCjIwMjQsMDYzMDgsUGxhY2lsbGEsT3Ryb3Mgc2VjdG9yZXMsNDU3LDE1MDc0MC4wLDEzNg0KMjAyNCwwNjMwOCxQbGFjaWxsYSxQcm9jZXNhbWllbnRvIGZydXRhcyB5IGhvcnRhbGl6YXMsMSwsMQ0KMjAyNCwwNjMwOCxQbGFjaWxsYSxQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsMzMwLDk1ODk2MS4wLDIwDQoyMDI0LDA2MzA4LFBsYWNpbGxhLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDU4LDI1OTI3Ny4wLDANCjIwMjQsMDYzMDgsUGxhY2lsbGEsVHJhbnNwb3J0ZSB5IGFsbWFjZW5hbWllbnRvIHBvdGVuY2lhbCw2NCw4NDAzNi4wLDANCjIwMjQsMDYzMDksUHVtYW5xdWUsQ29tZXJjaW8gYWdyb2FsaW1lbnRhcmlvIHBvdGVuY2lhbCwzLCwzDQoyMDI0LDA2MzA5LFB1bWFucXVlLE90cm9zIHNlY3RvcmVzLDMxOSwxODY0Nzg0LjAsODYNCjIwMjQsMDYzMDksUHVtYW5xdWUsUHJvZHVjY2nDs24gYWdyb3BlY3VhcmlhLDEyNSw2MzY5NC4wLDIzDQoyMDI0LDA2MzA5LFB1bWFucXVlLFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDIxLDIxNDQ2LjAsMQ0KMjAyNCwwNjMwOSxQdW1hbnF1ZSxUcmFuc3BvcnRlIHkgYWxtYWNlbmFtaWVudG8gcG90ZW5jaWFsLDksLDENCjIwMjQsMDYzMTAsU2FudGEgQ3J1eixDb21lcmNpbyBhZ3JvYWxpbWVudGFyaW8gcG90ZW5jaWFsLDU0LDQxNzY4My4wLDMNCjIwMjQsMDYzMTAsU2FudGEgQ3J1eixPdHJvcyBzZWN0b3JlcywzNzkyLDEyNjgxOTQ1LjAsMjQyDQoyMDI0LDA2MzEwLFNhbnRhIENydXosUHJvY2VzYW1pZW50byBmcnV0YXMgeSBob3J0YWxpemFzLDMsLDENCjIwMjQsMDYzMTAsU2FudGEgQ3J1eixQcm9kdWNjacOzbiBhZ3JvcGVjdWFyaWEsNTA5LDI0NTA3OTAuMCwxOA0KMjAyNCwwNjMxMCxTYW50YSBDcnV6LFNlcnZpY2lvcyBhZ3LDrWNvbGFzLDI3MywxNjI5NTk4LjAsMg0KMjAyNCwwNjMxMCxTYW50YSBDcnV6LFRyYW5zcG9ydGUgeSBhbG1hY2VuYW1pZW50byBwb3RlbmNpYWwsMjIyLDYxMDg0OS4wLDANCg==", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactSector.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Anio", Int64.Type}, {"CUT", type text}, {"Comuna", type text}, {"Sector", type text}, {"Empresas", Int64.Type}, {"Ventas_UF_observadas", type number}, {"Celdas_ventas_suprimidas", Int64.Type}}, "en-US")
in Tipos