let
    Binario = if RutaDatos = "" then Binary.FromText("77u/QW5pbyxDVVQsQ29tdW5hLExsdXZpYV9KSkEsTWF4MjRoX0pKQSxNZXNlc192YWxpZG9zLFJlZmVyZW5jaWFfMjAxN18yMDIyLEFub21hbGlhX2xsdXZpYQ0KMjAxNywwNjMwMSxTYW4gRmVybmFuZG8sMzM3LjUsMzYuNSwzLDI1NS42NjY2NjY2NjY2NjY2NiwwLjMyMDA3ODIyNjg1Nzg4NzkNCjIwMTcsMDYzMDMsQ2hpbWJhcm9uZ28sMzkwLjAsNDIuOSwzLDI2Mi44MzMzMzMzMzMzMzMzLDAuNDgzODMwMDU3MDcwMzg2ODQNCjIwMTgsMDYzMDEsU2FuIEZlcm5hbmRvLDIyMi41LDQ3LjAsMywyNTUuNjY2NjY2NjY2NjY2NjYsLTAuMTI5NzI2MjA1OTk3MzkyMzcNCjIwMTgsMDYzMDMsQ2hpbWJhcm9uZ28sMjMyLjcsNjEuMywzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjExNDY0ODA2NTk0ODAwMjQ4DQoyMDE5LDA2MzAxLFNhbiBGZXJuYW5kbywxMDQuNSwyOS4wLDMsMjU1LjY2NjY2NjY2NjY2NjY2LC0wLjU5MTI2NDY2NzUzNTg1MzkNCjIwMTksMDYzMDMsQ2hpbWJhcm9uZ28sMTAyLjQsNDkuOCwzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjYxMDM5OTQ5MjcwNzY3MjgNCjIwMjAsMDYzMDEsU2FuIEZlcm5hbmRvLDM5NS41LDU0LjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsMC41NDY5MzYxMTQ3MzI3MjUNCjIwMjAsMDYzMDMsQ2hpbWJhcm9uZ28sNDA5LjQwMDAwMDAwMDAwMDAzLDU0LjEsMywyNjIuODMzMzMzMzMzMzMzMywwLjU1NzY0MTA5MDY3ODUwMzYNCjIwMjEsMDYzMDEsU2FuIEZlcm5hbmRvLDI0Ny4wLDY4LjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsLTAuMDMzODk4MzA1MDg0NzQ1NjcNCjIwMjEsMDYzMDMsQ2hpbWJhcm9uZ28sMjI0LjcsNjAuOSwzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjE0NTA4NTYwNTU4MDIxNTU1DQoyMDIyLDA2MzAxLFNhbiBGZXJuYW5kbywyMjcuMCwzNC4wLDMsMjU1LjY2NjY2NjY2NjY2NjY2LC0wLjExMjEyNTE2Mjk3MjYyMDU0DQoyMDIyLDA2MzAzLENoaW1iYXJvbmdvLDIxNy44LDM0LjYsMywyNjIuODMzMzMzMzMzMzMzMywtMC4xNzEzMzc5ODM1MTI5OTkyMw0KMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sLCwyLDI1NS42NjY2NjY2NjY2NjY2NiwNCjIwMjMsMDYzMDMsQ2hpbWJhcm9uZ28sNDY4LjI5OTk5OTk5OTk5OTk1LDY5LjcsMywyNjIuODMzMzMzMzMzMzMzMywwLjc4MTczNzQ3NjIyMDY3MjENCjIwMjQsMDYzMDEsU2FuIEZlcm5hbmRvLDQ2MC4wLDcxLjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsMC43OTkyMTc3MzE0MjExMjEzDQoyMDI0LDA2MzAzLENoaW1iYXJvbmdvLDQ2Ni40LDgyLjUsMywyNjIuODMzMzMzMzMzMzMzMywwLjc3NDUwODU2MDU1ODAyMTUNCjIwMjUsMDYzMDEsU2FuIEZlcm5hbmRvLDI0My4wLDQ4LjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsLTAuMDQ5NTQzNjc2NjYyMzIwNzM1DQoyMDI1LDA2MzAzLENoaW1iYXJvbmdvLDIyOC43LDczLjQsMywyNjIuODMzMzMzMzMzMzMzMywtMC4xMjk4NjY4MzU3NjQxMDkwNw0K", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactInvierno.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Anio", Int64.Type}, {"CUT", type text}, {"Comuna", type text}, {"Lluvia_JJA", type number}, {"Max24h_JJA", type number}, {"Meses_validos", Int64.Type}, {"Referencia_2017_2022", type number}, {"Anomalia_lluvia", type number}}, "en-US")
in Tipos