let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RmVjaGEsVHJpbWVzdHJlLE9jdXBhZG9zX2Fncm8sTm90YV9JTkUsVGVycml0b3Jpbw0KMjAxMy0wMi0wMSxFbmUgLSBNYXIsMTE4MDY4LjM2MzUyODQwMDg5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDEzLTAzLTAxLEZlYiAtIEFiciwxMTM3NjMuNjAyMDkzNTQ4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDEzLTA0LTAxLE1hciAtIE1heSwxMDEzMjkuNDY1MTM1NzEzNywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxMy0wNS0wMSxBYnIgLSBKdW4sODU4MDMuMTUwNTUzODUyNDUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTMtMDYtMDEsTWF5IC0gSnVsLDg0MTUyLjEzOTU5NjM2MzUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTMtMDctMDEsSnVuIC0gQWdvLDg0OTIzLjI1ODY1NDA5MjE2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDEzLTA4LTAxLEp1bCAtIFNlcCw4MDc0My4wOTI5NzU5MDYyNywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxMy0wOS0wMSxBZ28gLSBPY3QsNzYyNDkuODI2NDk3MTAyNjQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTMtMTAtMDEsU2VwIC0gTm92LDc0NTkyLjA0NTA1NzM4MTI3LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDEzLTExLTAxLE9jdCAtIERpYyw4NDA0MS4xNzUzNDkwMjUwNywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxMy0xMi0wMSxOb3YgLSBFbmUsOTI1NzcuMDQyNjQzMzEyNDIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTQtMDEtMDEsRGljIC0gRmViLDk5NzE2LjQyOTM4OTk2NjUyLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE0LTAyLTAxLEVuZSAtIE1hciw5NzY2MC42MzUxNzQ3MDI2NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNC0wMy0wMSxGZWIgLSBBYnIsOTcwMzIuMTM2MTEyNzMzNzEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTQtMDQtMDEsTWFyIC0gTWF5LDg4NzUwLjI4MjI1MzgxMDE5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE0LTA1LTAxLEFiciAtIEp1biw3NzgzMC4zOTI4MjAxNzcwOCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNC0wNi0wMSxNYXkgLSBKdWwsNzMyNzcuNTkyMTYwNDY1OTcsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTQtMDctMDEsSnVuIC0gQWdvLDc0NjA5LjcyODY0MzM0Njk5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE0LTA4LTAxLEp1bCAtIFNlcCw3NTgxNy43MzIwODM5NzMxLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE0LTA5LTAxLEFnbyAtIE9jdCw3NjU1OS41NzYxNDIwNTk5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE0LTEwLTAxLFNlcCAtIE5vdiw4NjM0MC4yMDcwMzg1NTM0MywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNC0xMS0wMSxPY3QgLSBEaWMsOTQ4MDUuMTA3MzU1ODU5NDUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTQtMTItMDEsTm92IC0gRW5lLDk4MDM2LjQ5MjI4MzYzMDUyLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE1LTAxLTAxLERpYyAtIEZlYiw5OTc1NC45NTM1MjY1NzY0NywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNS0wMi0wMSxFbmUgLSBNYXIsMTAzODEwLjI3MTU0MTc4MTQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTUtMDMtMDEsRmViIC0gQWJyLDk2OTkzLjIxMjg2ODYxNTI2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE1LTA0LTAxLE1hciAtIE1heSw4NDM0NS41ODg4ODQ4MDk5OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNS0wNS0wMSxBYnIgLSBKdW4sNjk2NzYuMDUzNjg4NzUzNywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNS0wNi0wMSxNYXkgLSBKdWwsNjg5OTEuNzY2MzU2OTU0NDUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTUtMDctMDEsSnVuIC0gQWdvLDcxMDk2LjQyNDE1NzQyODc5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE1LTA4LTAxLEp1bCAtIFNlcCw3Mjc2NC4zOTM5Mzk3MDU5OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNS0wOS0wMSxBZ28gLSBPY3QsNzcxMjYuNjIxNjEyMTM0NTgsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTUtMTAtMDEsU2VwIC0gTm92LDgxMjc3LjQzNjU2MTAxMzkyLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE1LTExLTAxLE9jdCAtIERpYyw5NTQ0Ni4zMTQ0ODUyMjY3NywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNS0xMi0wMSxOb3YgLSBFbmUsOTkwMzYuMDA2MzQ1OTY2MzQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTYtMDEtMDEsRGljIC0gRmViLDEwNDg0MS44NTc5NjgyNzYzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE2LTAyLTAxLEVuZSAtIE1hciwxMDIyMTYuMjA5OTUwNzQwNjEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTYtMDMtMDEsRmViIC0gQWJyLDEwMTMxNC4xMjAxNzUxODE2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE2LTA0LTAxLE1hciAtIE1heSw5MjAxMy4xMzE3NDA4NzcxOSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNi0wNS0wMSxBYnIgLSBKdW4sODIxMDQuMzQ2MDMwMzE1MDUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTYtMDYtMDEsTWF5IC0gSnVsLDc5MjIwLjgzMTIyNzcwMjgzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE2LTA3LTAxLEp1biAtIEFnbyw4MTQ4Ni45ODM2MzM5NTM0MSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNi0wOC0wMSxKdWwgLSBTZXAsODIxMTQuMDc0MjQwODY0NSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNi0wOS0wMSxBZ28gLSBPY3QsODE4NTYuNzIwMjIwOTM5NzQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTYtMTAtMDEsU2VwIC0gTm92LDg1NjQ4LjY5NTc0ODgzMzM5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE2LTExLTAxLE9jdCAtIERpYyw5NjY0Ny41MDEwNzI0MTM5NywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNi0xMi0wMSxOb3YgLSBFbmUsOTg3NDkuMDc4MTg0MTc0MzcsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTctMDEtMDEsRGljIC0gRmViLDEwMDQyNC44NTMxMDI4MjI4OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNy0wMi0wMSxFbmUgLSBNYXIsMTA0NDIzLjI5NjgzMjM1ODIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTctMDMtMDEsRmViIC0gQWJyLDEwMjE4OC4wMzU5NjY0MTY0LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE3LTA0LTAxLE1hciAtIE1heSw5MDg5MS41NTg2NDE4NjY1OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNy0wNS0wMSxBYnIgLSBKdW4sNzUwNzcuNTg4MjYyNTIyMjMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTctMDYtMDEsTWF5IC0gSnVsLDc0ODU1LjY5NzUwMDY3MDc4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE3LTA3LTAxLEp1biAtIEFnbyw3ODc3OC42ODUwNDc2NTM4MSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNy0wOC0wMSxKdWwgLSBTZXAsODA5NzIuODg0MTE2NTU2NDIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTctMDktMDEsQWdvIC0gT2N0LDgyOTQ4LjczNjcxODk5Nzk5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE3LTEwLTAxLFNlcCAtIE5vdiw5MDE1Ni4wNTM3MjExMDExNCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxNy0xMS0wMSxPY3QgLSBEaWMsMTA1MzYyLjM4NjMxNjE4MDQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTctMTItMDEsTm92IC0gRW5lLDEwNTU4Ni43NzMwODcxNzY5OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOC0wMS0wMSxEaWMgLSBGZWIsMTAzOTIxLjEwMjczODk1MDMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTgtMDItMDEsRW5lIC0gTWFyLDk0ODQ3LjgyODE5NDA2OTcyLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE4LTAzLTAxLEZlYiAtIEFiciw5NzM4NC44MTMzOTAwMTUxNywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOC0wNC0wMSxNYXIgLSBNYXksODg4MDcuNDIyOTg2MzI3NTcsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTgtMDUtMDEsQWJyIC0gSnVuLDc3NzE1LjMzMTI5NDE4MTI5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE4LTA2LTAxLE1heSAtIEp1bCw3MjQwMS40Njg0NTk3NjQ4NywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOC0wNy0wMSxKdW4gLSBBZ28sNzg0MjkuNjY4MzM5NzQ1OTEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTgtMDgtMDEsSnVsIC0gU2VwLDcyMjgzLjE5MTMwNTMwNjIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTgtMDktMDEsQWdvIC0gT2N0LDc2NjA0LjU2MTM3NTgxNjgzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE4LTEwLTAxLFNlcCAtIE5vdiw4NDMwNy45NTE5OTU4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE4LTExLTAxLE9jdCAtIERpYywxMDYzMzAuMDk0NjcxMzI1MSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOC0xMi0wMSxOb3YgLSBFbmUsMTExMjQ4LjgzNDQ4NjY1NTcsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTktMDEtMDEsRGljIC0gRmViLDEwOTUyMy42MjQ4NzkxMDI4OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOS0wMi0wMSxFbmUgLSBNYXIsOTYxNTIuNDcyNDkxMDEyMjUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTktMDMtMDEsRmViIC0gQWJyLDg5NjU0LjgzNzE4OTM0ODQ5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE5LTA0LTAxLE1hciAtIE1heSw4MjE3Mi44NDIyNDY0NTE2OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOS0wNS0wMSxBYnIgLSBKdW4sNzg2NjkuNjI2MTc1NzUxODIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTktMDYtMDEsTWF5IC0gSnVsLDgwMTczLjg2NTI1Nzk3MDk2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE5LTA3LTAxLEp1biAtIEFnbyw4NTU4NC45NTQyNzM1NDYzNiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOS0wOC0wMSxKdWwgLSBTZXAsODI2NjIuMTUzNzE5OTc1MzgsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMTktMDktMDEsQWdvIC0gT2N0LDg1MDI1LjA4MTAyMDUxNzMzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE5LTEwLTAxLFNlcCAtIE5vdiw5MzY1MS44NTcwNDQ0NTQ2MiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAxOS0xMS0wMSxPY3QgLSBEaWMsMTA2OTQwLjI5NjI2ODQ3NjE3LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDE5LTEyLTAxLE5vdiAtIEVuZSwxMDM1MjAuNDE5NTMwOTI1NTQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjAtMDEtMDEsRGljIC0gRmViLDk0Nzg3LjA4ODcwMDE0NzM3LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIwLTAyLTAxLEVuZSAtIE1hciw4NzEzMC4zNDY4NjkyMjQ0MiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMC0wMy0wMSxGZWIgLSBBYnIsNzQzMjkuMTAyNzczOTQ0NjQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjAtMDQtMDEsTWFyIC0gTWF5LDU3MjQ4LjAxMzk1ODE3NTc3NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMC0wNS0wMSxBYnIgLSBKdW4sNTA3NTMuOTg0MDc4NzM2NzcsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjAtMDYtMDEsTWF5IC0gSnVsLDQ5NDI1LjMwOTQwMjc3NjUzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIwLTA3LTAxLEp1biAtIEFnbyw0OTIxNy4xOTE3NTkyMDM3NSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMC0wOC0wMSxKdWwgLSBTZXAsNTc2MDUuOTAxOTE5NDY3Njk1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIwLTA5LTAxLEFnbyAtIE9jdCw2NTI2NC45NTg1ODM1MzYyOTYsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjAtMTAtMDEsU2VwIC0gTm92LDc3NjM4Ljg2NzI0MDk3NTk1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIwLTExLTAxLE9jdCAtIERpYyw4NjkwNS4zODUxODIxOTMxNSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMC0xMi0wMSxOb3YgLSBFbmUsOTAzOTUuNjUwOTk0NDc1MDYsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjEtMDEtMDEsRGljIC0gRmViLDk0NjcxLjYyMjcwOTYzNzY0LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIxLTAyLTAxLEVuZSAtIE1hciw4NzExMi4xNjA0NTg4NjEyMSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMS0wMy0wMSxGZWIgLSBBYnIsODQwMzcuMjk0NDcyMzgzNCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMS0wNC0wMSxNYXIgLSBNYXksNzE1ODMuOTc1Mzc1NjMwNjMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjEtMDUtMDEsQWJyIC0gSnVuLDY2MTUyLjk2OTg5OTk5NDQ4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIxLTA2LTAxLE1heSAtIEp1bCw2NzUzOC40NTA5MDAyMDcxLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIxLTA3LTAxLEp1biAtIEFnbyw2NzIxNS4zNjcxNTgxNDc5NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMS0wOC0wMSxKdWwgLSBTZXAsNzA1NzEuMTk0OTQ3MzE5MDMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjEtMDktMDEsQWdvIC0gT2N0LDY4ODY3LjY0NzA1OTYwOTI1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIxLTEwLTAxLFNlcCAtIE5vdiw3MzY2MC43NTg0Mzc1MzY5NSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMS0xMS0wMSxPY3QgLSBEaWMsODM3MjAuMTk3Mzg0NTk0MzQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjEtMTItMDEsTm92IC0gRW5lLDg2NzE3LjIzNzYzNzg5NTMzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIyLTAxLTAxLERpYyAtIEZlYiw4ODk3MS4yOTU3MTcyMjA5NCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMi0wMi0wMSxFbmUgLSBNYXIsODI5NjYuNzAwMDA3MTk3MTQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjItMDMtMDEsRmViIC0gQWJyLDg0MDUwLjgyNTc5NTczODM1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIyLTA0LTAxLE1hciAtIE1heSw3OTM1My42MTcyMTgwOTI5NywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMi0wNS0wMSxBYnIgLSBKdW4sNzE1NjQuNjk5Mzk3NTAzMDMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjItMDYtMDEsTWF5IC0gSnVsLDcxNjAzLjI0NDcyMTYwODIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjItMDctMDEsSnVuIC0gQWdvLDcyMjMzLjY4MDU0ODI1MTg0LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIyLTA4LTAxLEp1bCAtIFNlcCw3NjIyMS41ODkyNjcxMjU4MiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMi0wOS0wMSxBZ28gLSBPY3QsNzU1ODAuMTQyNTM5NTU4MjIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjItMTAtMDEsU2VwIC0gTm92LDc3NzYwLjM2Nzg3NzQzNTk2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIyLTExLTAxLE9jdCAtIERpYyw4NTc0OC42MDI2NDA5NzAwOSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMi0xMi0wMSxOb3YgLSBFbmUsODgyOTUuNzU1NDYwMjA3NSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMy0wMS0wMSxEaWMgLSBGZWIsOTEyMDcuMDg5ODE4NDA4MTMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjMtMDItMDEsRW5lIC0gTWFyLDg3NjEzLjMwMTIzNDMxMDMzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIzLTAzLTAxLEZlYiAtIEFiciw4NjE2Ny4xNDk0MDcyNjQ5OCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMy0wNC0wMSxNYXIgLSBNYXksNzYxMjguMzQyNzM1NTA4NDYsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjMtMDUtMDEsQWJyIC0gSnVuLDcwNDczLjk0NDg5MTI5NzUyLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIzLTA2LTAxLE1heSAtIEp1bCw2NjMyOC41MDc0OTY4NjQ4MywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMy0wNy0wMSxKdW4gLSBBZ28sNjgyMTYuNjk0MTA2NDEzNDQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjMtMDgtMDEsSnVsIC0gU2VwLDcwNzgyLjg0MTkzNDExMDEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjMtMDktMDEsQWdvIC0gT2N0LDc1NDg1Ljc0MjkxNjczMDc0LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIzLTEwLTAxLFNlcCAtIE5vdiw4MDgzNS40MDI3NTA5Mjc4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDIzLTExLTAxLE9jdCAtIERpYyw4MTk2Mi43NzU5Njk2MDU3NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyMy0xMi0wMSxOb3YgLSBFbmUsODMzNjkuNDI5ODc1OTg4ODMsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjQtMDEtMDEsRGljIC0gRmViLDc5NzYzLjU4OTgyODYzNDk4LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI0LTAyLTAxLEVuZSAtIE1hciw3OTE0Ny4xMjQwMTA3NjAwNiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNC0wMy0wMSxGZWIgLSBBYnIsNzQ5OTkuNzQ1NjYzODA2ODQsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjQtMDQtMDEsTWFyIC0gTWF5LDY2OTc4LjQ4Mjc1MTQ0ODk0LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI0LTA1LTAxLEFiciAtIEp1biw2MzIxNy44NDI3ODUyNDM0MjUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjQtMDYtMDEsTWF5IC0gSnVsLDY0NDYyLjIxNjM3ODcxNDMzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI0LTA3LTAxLEp1biAtIEFnbyw2ODgxNS4xNTg4NDIwNjE0NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNC0wOC0wMSxKdWwgLSBTZXAsNzA1NzQuNzk1MzAwNjY3NjEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjQtMDktMDEsQWdvIC0gT2N0LDY3NjEzLjI2NzEyMzM4MjQ3LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI0LTEwLTAxLFNlcCAtIE5vdiw3ODE3MS4zMDc0OTQyODgxNSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNC0xMS0wMSxPY3QgLSBEaWMsODY5NTguNTg5ODQ0MTkyMjksLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjQtMTItMDEsTm92IC0gRW5lLDg5ODk5LjA4MjA4MTIwNjU1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI1LTAxLTAxLERpYyAtIEZlYiw4MTIxMy43MTczODg2Mjg1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI1LTAyLTAxLEVuZSAtIE1hciw3NzA3My40NjAyODQxNjU3OSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNS0wMy0wMSxGZWIgLSBBYnIsNzQ3MDcuMzA3NjM5NzIwMTEsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjUtMDQtMDEsTWFyIC0gTWF5LDcwNjAxLjg1ODc5NjM0MTk2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI1LTA1LTAxLEFiciAtIEp1biw2NTc5OS4yODY4NDQ3MjA5NSwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNS0wNi0wMSxNYXkgLSBKdWwsNjM1MzYuMTM0NjI3MTcyNjgsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjUtMDctMDEsSnVuIC0gQWdvLDY2NTY5Ljk4NTA5NzA0MTgsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjUtMDgtMDEsSnVsIC0gU2VwLDY3NDc1LjQxMjg0NTIwOTY5LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI1LTA5LTAxLEFnbyAtIE9jdCw3MDI0OC40MTExNjA2ODc3NiwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNS0xMC0wMSxTZXAgLSBOb3YsNzU5MzcuNDk5NTI5MjA0NCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNS0xMS0wMSxPY3QgLSBEaWMsODA4MzIuNzEzNTc4NDE5NzUsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjUtMTItMDEsTm92IC0gRW5lLDgxODg3LjMzMDQ1MTA1NzgzLCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI2LTAxLTAxLERpYyAtIEZlYiw3OTY0OC45NTIyNDE3MzE1MywsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNi0wMi0wMSxFbmUgLSBNYXIsNzg4NTIuNzM0ODcxNjExMjIsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjYtMDMtMDEsRmViIC0gQWJyLDczMDg0LjM3OTk0NTAyNzI2LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI2LTA0LTAxLE1hciAtIE1heSw2NzA3OS4wMjAwNDY3NTY4NCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0KMjAyNi0wNS0wMSxBYnIgLSBKdW4sNjM2OTAuMTA1NDkwNjczMjgsLFJlZ2nDs24gZGUgT+KAmUhpZ2dpbnMNCjIwMjYtMDYtMDEsTWF5IC0gSnVsLDYzNzk3LjA0MjY4NzAwNTg1LCxSZWdpw7NuIGRlIE/igJlIaWdnaW5zDQoyMDI2LTA3LTAxLEp1biAtIEFnbyw2NzY5OS40OTczNzE5NzM5OCwsUmVnacOzbiBkZSBP4oCZSGlnZ2lucw0K", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactEmpleo.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type datetime}, {"Trimestre", type text}, {"Ocupados_agro", type number}, {"Nota_INE", type number}, {"Territorio", type text}}, "en-US")
in Tipos