let
    Binario = if RutaDatos = "" then Binary.FromText("77u/VGVtcG9yYWRhLFByb2R1Y3RvLFRvbmVsYWRhcyxVU0RfRk9CLFVTRF9rZyxDdW90YV9DaGluYV92YWxvcixDYW1iaW9fdmFsb3JfdW5pdGFyaW8NCjIwMjEtMjAyMixBY2VpdHVuYSwwLjk5NjksMjA4NS4yLDIuMDkxNjg0MjIxMDg1MzY0LDEuMCwNCjIwMTYtMjAxNyxBcsOhbmRhbm9zIHkgbWlydGlsb3MsMTA2MTE3Ljg2MjYwMDAwMDAxLDU0Mjc3OTExOC45NCw1LjExNDg3MDQ0MzQ5ODczNywwLjExNDc2OTMzMzAyMzgxOTEzLA0KMjAxNy0yMDE4LEFyw6FuZGFub3MgeSBtaXJ0aWxvcywxMDkyNzcuMDg4NDk5OTk5OTgsNjI1ODU4MzczLjc4LDUuNzI3MjYwNjk0NTQxNjU2LDAuMTAwMDUwODQxNjQ5Mzc3OTgsMC4xMTk3Mjc0MjE4MDAzNTA1Ng0KMjAxOC0yMDE5LEFyw6FuZGFub3MgeSBtaXJ0aWxvcywxMTA5NjAuNzk1NTAwMDAwMDEsNTc1NTM1NDM4LjYxLDUuMTg2ODM1OTA5MTc0Nzg2LDAuMTE4MjY5MDU4MzY0ODQwMjIsLTAuMDk0MzYwMDgxNDA1Mzk0OTgNCjIwMTktMjAyMCxBcsOhbmRhbm9zIHkgbWlydGlsb3MsMTA5MTM3LjQyMTcsNTUxODM0MDA0LjAzLDUuMDU2MzIyNTI4MzcwNjY5LDAuMDk3ODcwNDkzODkwNTIxMjcsLTAuMDI1MTYyNDI3MTY5Mzc2NTU2DQoyMDIwLTIwMjEsQXLDoW5kYW5vcyB5IG1pcnRpbG9zLDExNzc5Mi4xMTMxOTk5OTk5OSw2MDYyMjU5MjguODY5OTk5OSw1LjE0NjU3NDg2MzEyOTI5MSwwLjA3MzQ0MzExNDgwMjA4NDk3LDAuMDE3ODQ5NDAyMjU4NzAxNDYzDQoyMDIxLTIwMjIsQXLDoW5kYW5vcyB5IG1pcnRpbG9zLDEwNzIxNi4zMzAzLDQ1MTI2NzczMS40NTAwMDAwNSw0LjIwODk0NTg3NzgwOTA2NCwwLjA3MzM5NjQwMDgwOTcyNiwtMC4xODIxODUwNDczODcwNTMzMg0KMjAyMi0yMDIzLEFyw6FuZGFub3MgeSBtaXJ0aWxvcyw4NzMyOS44NjkxMDAwMDAwMSwzODU3OTQzNjAuMzEwMDAwMDYsNC40MTc2Njc5MTAwMjc4MTksMC4wNjc0Njk1Mjg5NDU2Mzk0MywwLjA0OTU5MDA5NjQ5NDA0Mjc4DQoyMDIzLTIwMjQsQXLDoW5kYW5vcyB5IG1pcnRpbG9zLDg2MzU1LjIzMjcsNDc1ODY4NjY3LjI2LDUuNTEwNTk0NDY0MDY4ODgxLDAuMDU2OTQzMzM4MjQ1MDM0NiwwLjI0NzM5ODk4NDMyODQwMzI0DQoyMDI0LTIwMjUsQXLDoW5kYW5vcyB5IG1pcnRpbG9zLDkwODAxLjgwODQsNDQwMTQzNTQyLjY3LDQuODQ3Mjk5MzA0MTE4MjY1LDAuMDI2NzcwNDc5NjQ1MTY5NDM1LC0wLjEyMDM2NzI2MDYwNjAxMDIyDQoyMDE2LTIwMTcsQ2VyZXphLDk1Mzk4LjgwNzEsNjc5NjMwNjk4LjE5OTk5OTgsNy4xMjQxMDA1OTI2NTgyNDYsMC44NDE1MzI2MzUxNDI1MjUxLA0KMjAxNy0yMDE4LENlcmV6YSwxODUyMTkuNjQ1ODk5OTk5OTcsMTA5Nzc3NjU5OS45LDUuOTI2ODkwNzE3MDUwMDEyLDAuODc4ODk5NzYzMjY1MDMwNCwtMC4xNjgwNTA2Njk3MDAyNTk2MQ0KMjAxOC0yMDE5LENlcmV6YSwxNzk5NzUuMjY2MzAwMDAwMDIsMTMzMzc0NjI1NS42NCw3LjQxMDcxOTcyMzEwMjMwNywwLjkwODM0MzQwMjIzMDMyOTEsMC4yNTAzNTUzODQ3ODYxMTI4Ng0KMjAxOS0yMDIwLENlcmV6YSwyMjg5NDguOTU2Njk5OTk5OTgsMTU1ODg0MDQ1NS41NTAwMDA0LDYuODA4NjgxMTkyNjA1NzYsMC45MjAwODMxOTIzMTM1OCwtMC4wODEyMzg4NzQ2MjkxMDU1DQoyMDIwLTIwMjEsQ2VyZXphLDM1MzI5MC42MjMzMDAwMDAwNCwxODA1ODEzMzU5LjgsNS4xMTE0MTAzODIwMDMxOTUsMC45MDA3Mzk2ODg0MDg0MTIyLC0wLjI0OTI4MDQwNTc5MjIxMTkNCjIwMjEtMjAyMixDZXJlemEsMzU1Njc4LjgyNTg5OTk5OTk0LDIxMjE5MTczMTMuNDY5OTk5OCw1Ljk2NTgyNDEwNTc4MDcxLDAuOTAwODU5OTk0MjcyODI4NSwwLjE2NzE1ODExNDg2OTAwNTExDQoyMDIyLTIwMjMsQ2VyZXphLDQxNDY2Mi40NjQyLDI1NDY3NDU2OTEuMTE5OTk5NCw2LjE0MTczMTkxNjkwNTkyMywwLjkwOTIwOTA0MzkwNzk4NjcsMC4wMjk0ODU5MTk4MDAyMTA2NDcNCjIwMjMtMjAyNCxDZXJlemEsNDEzNjkwLjgxMDcsMzA0Njc4NDk0MC43Miw3LjM2NDg4NDI2MTE4MTg3MzQsMC45MjUxOTY0ODc2MDEwNzcxLDAuMTk5MTU0MzAzODM4ODAyMTcNCjIwMjQtMjAyNSxDZXJlemEsNjI1MzMwLjU4MjUsMjg0NTQzOTAwOC4yMjk5OTk1LDQuNTUwMjk1NjE2MjA3MTI4LDAuOTA1MjIyODM1Mzc5NzEzNiwtMC4zODIxNjMzMjMzMDAyMTkzDQoyMDE2LTIwMTcsQ2hpcmltb3lhLDMzNi4xMDM1MDAwMDAwMDAwNSwxNDM1NDkzLjEyLDQuMjcwOTg1MzM2MzYyMTYzLDAuMCwNCjIwMTctMjAxOCxDaGlyaW1veWEsMzA3Ljg2NCwxNDY3Mjk0LjUwOTk5OTk5OTgsNC43NjYwNDc3MDI4ODE3OTEsMC4wLDAuMTE1OTEyOTE2NDY1NjE4NTINCjIwMTgtMjAxOSxDaGlyaW1veWEsMjY0LjM4MSwxMzQzMzUzLjEyLDUuMDgxMTI1Nzk5NTA5MDQzLDAuMCwwLjA2NjEwODg4NDM5ODQzNzY1DQoyMDE5LTIwMjAsQ2hpcmltb3lhLDI5OC40ODE3LDEzMDA2ODkuMSw0LjM1NzY4NDU3NDk2NzI0MywwLjAsLTAuMTQyMzc4MTM2ODcxMTA0OA0KMjAyMC0yMDIxLENoaXJpbW95YSwyNjkuNzk3LDEwMDM1NjUuNDYsMy43MTk3MDU3Nzg3ODkyMzc0LDAuMCwtMC4xNDY0MDMxNjA5NDUzNTE1NQ0KMjAyMS0yMDIyLENoaXJpbW95YSwzODUuMTIxNSwxNzg0NDM4Ljc4OTk5OTk5OTgsNC42MzM0NDM3MDU0MjgwMjYsMC4wLDAuMjQ1NjQ3OTAzNjE4OTI4MDgNCjIwMjItMjAyMyxDaGlyaW1veWEsNDk5LjQwNzUsMjUwMzU5NC4wNiw1LjAxMzEyODY3NzQ4MjgxNjUsMC4wLDAuMDgxOTQ0NDQ0ODIxODkyMjMNCjIwMjMtMjAyNCxDaGlyaW1veWEsNDYyLjUxNzgsMjU3NzIyNC43Nyw1LjU3MjE2MzQyODA4ODYwNSwwLjAsMC4xMTE1MTQxNDM0NzYyNjMyDQoyMDI0LTIwMjUsQ2hpcmltb3lhLDUyNi4xMTI1LDI5NDgwMzcuMTMsNS42MDM0MzQ4NzM3MTk5NzUsMC4wLDAuMDA1NjEyMDgzMzU1OTQyNzY1DQoyMDE2LTIwMTcsQ2lydWVsbyw5ODc1NC41NzM0LDEzOTg3OTA3MC44NywxLjQxNjQzMTMyMTE0NDI2MjMsMC4zNDgxNDMyMjA0NzY5MTE5MywNCjIwMTctMjAxOCxDaXJ1ZWxvLDEyMDQ0MS4wOTksMTczODQ1NjAzLjgsMS40NDM0MDc2NTEwNzEwMDE5LDAuMzc3NTEwMTI3NTgxMzc5NzUsMC4wMTkwNDUyNzkxNjMyMzMxNzUNCjIwMTgtMjAxOSxDaXJ1ZWxvLDE1NTQ1OC40MzMyOTk5OTk5OCwyMTM4Njc5NjAuNiwxLjM3NTcyNDQwNDY1MzQ0NjUsMC41NjEyNzgzNjQ4MDYxNzc1LC0wLjA0Njg5MTI4OTc2NjUwMTM2NQ0KMjAxOS0yMDIwLENpcnVlbG8sMTI1Njk3LjQ5NDMsMTk0MTg5ODg2LjAyOTk5OTk3LDEuNTQ0ODk4NjI0MzYzNDI5LDAuNTQ5MDExODE1MDMxMDM0NSwwLjEyMjk3MTAxMDEzNjcyNzYyDQoyMDIwLTIwMjEsQ2lydWVsbywxMjA0NTUuNzYwNiwyMTE1OTYzNDYuNTQ5OTk5OTgsMS43NTY2MzExOTM4NTkyMzMyLDAuNjM2MjYyMDkwMjcyODQzNiwwLjEzNzA1MjcyNzA1NzEyMTgNCjIwMjEtMjAyMixDaXJ1ZWxvLDE1ODExNS4yMjI4LDIxNzQwOTgxOC42NzAwMDAwMiwxLjM3NTAwODc3NDEwNzczOSwwLjY3OTEyNDAxMjY3NDQ3MzEsLTAuMjE3MjQ2NzUxMTAyNjUzNjgNCjIwMjItMjAyMyxDaXJ1ZWxvLDEzNzIyNS43NjY4MDAwMDAwNCwyOTMyNzE5OTIuMjYsMi4xMzcxNDk1OTczMzA1Nzg3LDAuNzIxNDgxNjA3OTA3NTY1OSwwLjU1NDI4MDY5ODExMjIwMTMNCjIwMjMtMjAyNCxDaXJ1ZWxvLDE3MDE2Ny4yNDQzMDAwMDAwMiwzMDk5ODc1MjQuNjEsMS44MjE2NjM4OTIzOTY5NDU3LDAuNjIyNjE0MDg5NTkyMjE2NSwtMC4xNDc2MTk4NTA5MTE1NTY1DQoyMDI0LTIwMjUsQ2lydWVsbywxNTQwMzcuNjM1NiwyODM2MzYyODUuNTEsMS44NDEzNDQwNjExNzgyNTM5LDAuNjExNDQzMTIxNjY2MDU5MiwwLjAxMDgwMzQwMjc5MjA1NTYwNQ0KMjAxNi0yMDE3LERhbWFzY28sOTM0LjIzMDU5OTk5OTk5OTksMTg3NjQwMC43NSwyLjAwODQ5ODQ5MDYyOTYxNTUsMC4wLA0KMjAxNy0yMDE4LERhbWFzY28sMTI2Ni42OTkyMDAwMDAwMDAyLDI2ODQ0NDkuMiwyLjExOTI0NzU2ODc5OTI4NSwwLjA2NTg0MzY5NzA5ODA4NjI3LDAuMDU1MTQwMjM0NzAwODc0Nw0KMjAxOC0yMDE5LERhbWFzY28sODc5LjYyOTIsMjM2MjMwMi45MDk5OTk5OTk3LDIuNjg1NTY2NzI1MTYxMDExLDAuMDE5MzEyMzQ1NTExMTg1OTUsMC4yNjcyMjY1MjE2NjcxMTYzNg0KMjAxOS0yMDIwLERhbWFzY28sOTAzLjA5MDgsMjQ0MjE2MC4yNywyLjcwNDIyNDUwMzIyODI0NywwLjA0MDM4NjkyMzUwMDMxNTU2LDAuMDA2OTQ3NDI2NzM1ODI4OTMyDQoyMDIwLTIwMjEsRGFtYXNjbywxMDIzLjU3MTIsMjYwNDk3My4xNywyLjU0NDk4NDgyMzcyMzA1OSwwLjAsLTAuMDU4ODg1NTI0OTY4NDY3MzMNCjIwMjEtMjAyMixEYW1hc2NvLDEwMzUuMjA4NSwxODEyNDQwLjg1MDAwMDAwMDMsMS43NTA3OTc4ODI3NDUzNjAzLDAuMCwtMC4zMTIwNTk1OTc5ODg0NDAxDQoyMDIyLTIwMjMsRGFtYXNjbyw3MjkuNDcwNjAwMDAwMDAwMSwxOTk4OTMzLjM5LDIuNzQwMjUyMTYzNjkyNDA5LDAuMCwwLjU2NTE0NDc3ODEwMjgzOTgNCjIwMjMtMjAyNCxEYW1hc2NvLDEwMTYuOTUyNSwyODA5NDA5LjM2MDAwMDAwMDMsMi43NjI1NzY3NzcxODQ3NzUzLDAuMDYwNDAyOTg0NDkwNjYxNzU0LDAuMDA4MTQ2OTE5MzkyMzY4ODkNCjIwMjQtMjAyNSxEYW1hc2NvLDE0MDMuMTcwMywzNTIxNDQzLjgxLDIuNTA5NjMzOTQxMDgzMjc0NCwwLjAsLTAuMDkxNTYwNDcyODg1NDg2NDENCjIwMTYtMjAxNyxEdXJhem5vLDI2MjQxLjIwNzcsMzYxMTcxMTMuNjMsMS4zNzYzNTEwNDQ2MjA1NTcxLDYuNTA2OTcwNjk1NTk4MTkxZS0wNSwNCjIwMTctMjAxOCxEdXJhem5vLDMxMjY2LjU5ODEwMDAwMDAwMyw0NTYzNzI1OC4zNzAwMDAwMDUsMS40NTk2MTcwMDgwMzAwNDg2LDAuMDAwNDcwOTU3MzAwNDA4OTI4OSwwLjA2MDQ5NzYyMDY3MjM4MjE4DQoyMDE4LTIwMTksRHVyYXpubywyOTUxNS45ODQ5OTk5OTk5OTcsNDEzMDU5NzUuODkwMDAwMDEsMS4zOTk0NDQyNjM1MDY3MDcsMC4wLC0wLjA0MTIyNTAyMjg2MDMxMzgyDQoyMDE5LTIwMjAsRHVyYXpubywyODk4Mi44NzgyOTk5OTk5OTcsNDE0MzYwMjEuNDEsMS40Mjk2NzI0MDgwMDIzNDgsMC4wMDA5OTIyNTUwMTM4OTY2MTU1LDAuMDIxNjAwMTA2MDQ0ODc3ODMNCjIwMjAtMjAyMSxEdXJhem5vLDI2OTg3LjMwOTQwMDAwMDAwMiw0MDc3NjE2Ni44MDk5OTk5OTUsMS41MTA5Mzg1NzUwNzcwNjkyLDAuMDA0MjUxNTY4ODM0NTA1NjU5LDAuMDU2ODQyNTA5MjQ4ODY1MzYNCjIwMjEtMjAyMixEdXJhem5vLDI2NzkzLjg4MzEsMzU1ODQ4MTEuNTk5OTk5OTk0LDEuMzI4MDk0NjA1Mjk0NDQ1LDAuMDAzMDMwNjg3OTU3ODkyNjg3MywtMC4xMjEwMTM1MDI5OTY1MDUyNg0KMjAyMi0yMDIzLER1cmF6bm8sMjI4MDUuMTM1NywzNDUzNTIyMi44MSwxLjUxNDM2MTY0NDg2NDA1NiwwLjAwODE0NTUwMTUyMzExNTg0MywwLjE0MDI1MTMzMzYyMjY2Mzg0DQoyMDIzLTIwMjQsRHVyYXpubywyMjMxMi45NTYxLDQwNTUyNTY4LjgzLDEuODE3NDQ0OTI1MTkzMDM2MiwwLjAxMTA1MTM3MTQxNTY3MzY0NiwwLjIwMDEzOTMwMDUxNDQzNDMNCjIwMjQtMjAyNSxEdXJhem5vLDI0Nzc1Ljc3NDEsMzg2MzA0NDguNTYsMS41NTkyMDI0ODU2MjQ4NTksMC4wMDEyOTY0NTI0NTgyNzgxNTk2LC0wLjE0MjA5MDkyOTk1ODAyODA4DQoyMDE2LTIwMTcsRnJhbWJ1ZXNhLDg4LjAsMzExMzAwLjAsMy41Mzc1LDAuMCwNCjIwMTctMjAxOCxGcmFtYnVlc2EsMjA5Ljg1Mjk5OTk5OTk5OTk4LDc2OTQyMi42NDk5OTk5OTk5LDMuNjY2NDgzOTE5Njk2MTY4LDAuMCwwLjAzNjQ2MTg4NTQyNjQ3ODY2DQoyMDE4LTIwMTksRnJhbWJ1ZXNhLDAuMDA1LDE1MC4wLDMwLjAsMC4wLDcuMTgyMjI1OTg0NjM5MjYxNQ0KMjAxOS0yMDIwLEZyYW1idWVzYSwwLjAwMTUsMzYuMCwyNC4wLDAuMCwtMC4xOTk5OTk5OTk5OTk5OTk5Ng0KMjAyMS0yMDIyLEZyYW1idWVzYSwzNS41MTYsMTYyMTI2LjAsNC41NjQ4NzIxNzAyODk0NDcsMC4wLC0wLjgwOTc5Njk5MjkwNDYwNjQNCjIwMjItMjAyMyxGcmFtYnVlc2EsMC4wMDgsOTYuMCwxMi4wLDAuMCwxLjYyODc3MDIxNTc1ODExNDMNCjIwMjQtMjAyNSxGcmFtYnVlc2EsOC42MjQ4LDkzOTg2LjQsMTAuODk3MjI2NjAyMzU1OTk0LDAuMCwtMC4wOTE4OTc3ODMxMzcwMDA0OA0KMjAxNi0yMDE3LEZydXRpbGxhLDIzLjA3MDYwMDAwMDAwMDAwMiwxMzg3NTMuNyw2LjAxNDMwODI1Mzc5NDg3MywwLjAsDQoyMDE3LTIwMTgsRnJ1dGlsbGEsNy4zODg3OTk5OTk5OTk5OTksNDc5OTQuNjQsNi40OTU1OTMzMzA0NDYwODIsMC4wLDAuMDgwMDIzMzQ3MDQ4Njg2ODUNCjIwMTgtMjAxOSxGcnV0aWxsYSwwLjMxNSwzNDgwLjAsMTEuMDQ3NjE5MDQ3NjE5MDQ3LDAuMCwwLjcwMDc4Njc0NjU4MzUyNjkNCjIwMTktMjAyMCxGcnV0aWxsYSwwLjI1NiwyMzMzLjk3LDkuMTE3MDcwMzEyNDk5OTk3LDAuMCwtMC4xNzQ3NDc5NDU4NTEyOTMyNw0KMjAyMC0yMDIxLEZydXRpbGxhLDAuMDI4LDIyMi4wLDcuOTI4NTcxNDI4NTcxNDI5LDAuMCwtMC4xMzAzNTk3MzY1MzcxOTM1Nw0KMjAyMS0yMDIyLEZydXRpbGxhLDAuMDEsMTAwLjAsMTAuMCwwLjAsMC4yNjEyNjEyNjEyNjEyNjEyNg0KMjAyMi0yMDIzLEZydXRpbGxhLDI0LjAwOTIsNDY5NTkuNjcsMS45NTU5MDMxNTM3OTEwNDY3LDAuMCwtMC44MDQ0MDk2ODQ2MjA4OTUzDQoyMDI0LTIwMjUsRnJ1dGlsbGEsMjMuOCw2NTIxMi4wLDIuNzQsMC4wLDAuNDAwODg3MzU3MTcyNjU0OA0KMjAxNi0yMDE3LEhpZ28sOTYuNTc5MDAwMDAwMDAwMDEsNjM0OTc1LjksNi41NzQ2Nzg3NjAzOTMwNDYsMC4wLA0KMjAxNy0yMDE4LEhpZ28sOTUuODcyNiw2MDQyODIuMiw2LjMwMjk3MDgxNzUyMjQyLDAuMCwtMC4wNDEzMjY0MjEwNzI4MzQ3OTYNCjIwMTgtMjAxOSxIaWdvLDgxLjY1MDYsNTMxMDc3LjUzLDYuNTA0MjY5Nzc4Nzg5MTMzNSwwLjAsMC4wMzE5MzcxNTU4NDE5ODc2NA0KMjAxOS0yMDIwLEhpZ28sMjIuODM0NDAwMDAwMDAwMDAyLDEyODk3MC40NCw1LjY0ODA3NjU4NjIwMzI3MiwwLjAsLTAuMTMxNjM1NTU5NjcxNTgxNDcNCjIwMjAtMjAyMSxIaWdvLDkwLjE2MTUsNjAwODU3LjM1LDYuNjY0MjM0MTc5Nzc3Mzk5LDAuMCwwLjE3OTkxMjE0ODUxMDIyNDg2DQoyMDIxLTIwMjIsSGlnbyw3OC43NTUsNTYxNzc1LjY1LDcuMTMzMjA2MTQ1NjQxNTQ4LDAuMCwwLjA3MDM3MTQ3MTUzMTkwNDM3DQoyMDIyLTIwMjMsSGlnbyw5Mi42MDYwMDAwMDAwMDAwMSw3MTc0OTYuOSw3Ljc0Nzg0NDYzMjA5NzI3MiwwLjAsMC4wODYxNjU4MTAxNDI5MjkwMQ0KMjAyMy0yMDI0LEhpZ28sMTIwLjI3MSw5Njk1NTguNCw4LjA2MTQ0Nzg5NjgzMjk4NiwwLjAsMC4wNDA0NzYxOTQzMDAwOTQ2NA0KMjAyNC0yMDI1LEhpZ28sMTAzLjk5Nyw4MjI1NTEuNzEwMDAwMDAwMSw3LjkwOTM3OTIxMjg2MTkxMSwwLjAsLTAuMDE4ODYzNjkzNzA4Mjc1MDENCjIwMTYtMjAxNyxLaXdpLDE4MzcyMi4xODg3LDIwNjIxNzcyNC4xNzAwMDAwMiwxLjEyMjQ0MzIxNTEwMTk3NjMsMC4xMDk1ODgwMDQ1Mjc1MzUzNywNCjIwMTctMjAxOCxLaXdpLDE3MzQyNi45MDk4LDE5ODEwNDUwMC44NiwxLjE0MjI5Mzg5ODI2NzkxNDcsMC4wODk5NzE2Mjc2MTM4MzIxMSwwLjAxNzY4NTI0NDkxODI3ODQ5OA0KMjAxOC0yMDE5LEtpd2ksMTY1NTUzLjYyOTgsMTk4MTMyNTA5LjA0LDEuMTk2Nzg3NDY1NjY1MDk4NywwLjE0NjE5MTQ2MTk2ODI3NDY4LDAuMDQ3NzA1MzgyNTQ2MzA3ODUNCjIwMTktMjAyMCxLaXdpLDE0NTgzMy41MTI3MDAwMDAwMiwyMDM5ODUzODUuMTMsMS4zOTg3NTUyMDYyMTY3MzkyLDAuMDYxNzMwNzI1OTE0MzgzNTUsMC4xNjg3NTgyMzUxNDY5NTYxDQoyMDIwLTIwMjEsS2l3aSwxNDEzNjYuNTAwMSwyMzUyNDk2MzYuMTYsMS42NjQxMTE2MjQ3MDMwODYsMC4wMzA2NDUxNDYxODQ2MTIwNiwwLjE4OTcwODk3NjQ1Nzc2NDQNCjIwMjEtMjAyMixLaXdpLDEzMjc5OC43NDk1OTk5OTk5OCwxODY2MTAxODEuMjQsMS40MDUyMTAzNzg4Nzg0NDc0LDAuMDI1ODU1NjkxMzAyMjU4NzY3LC0wLjE1NTU3OTI1NDQwODk4OTgNCjIwMjItMjAyMyxLaXdpLDE0MDExMS41NDczOTk5OTk5OCwyNTExMDI2MzguMTQwMDAwMDIsMS43OTIxNjIzMzYzNjQyOTA3LDAuMDM4MjE2ODEyMTQxMzc0ODIsMC4yNzUzNjk0MTMyMjI0NDINCjIwMjMtMjAyNCxLaXdpLDEzMDMyNC4zMzMyLDI2MjE3MDE3MC44MSwyLjAxMTY3NDc1MzA3NjczNCwwLjAsMC4xMjI0ODQ2NzI0MzA4MjU3Mw0KMjAyNC0yMDI1LEtpd2ksMTU0MTUyLjAyOTQsMzI3Njc3Nzg3LjQyOTk5OTk1LDIuMTI1Njc5MzYxNTA2OTk4LDAuMDAwMTI1OTk5MTcyMzA4MzE1MDYsMC4wNTY2NzE0OTEzODA5NTA1MQ0KMjAxNi0yMDE3LExpbcOzbiw4NTQ4Ni4xODAyLDEwNzIyMzgyMy42MDk5OTk5OCwxLjI1NDI4MjU0NDM3MzE3NzgsMC4wLA0KMjAxNy0yMDE4LExpbcOzbiw4MjI0NC4yODIzLDEyNTAxMzcwNC41MTAwMDAwMiwxLjUyMDAyOTEyNTU5OTE2NjUsMC4wLDAuMjExODcxMzg2MDkwOTE4MDUNCjIwMTgtMjAxOSxMaW3Ds24sOTc1NzMuOTQwOTk5OTk5OTksMTAwNDkzMjQyLjM1MDAwMDAxLDEuMDI5OTE4ODYyNzYyNzUzNiwxLjY3MTc1NDIwMDI5NjIzNWUtMDYsLTAuMzIyNDM0Nzg0MDMyOTg0MQ0KMjAxOS0yMDIwLExpbcOzbiw4MDA1NC4zNzU3LDg4NDI0ODUwLjE0OTk5OTk5LDEuMTA0NTU5ODYxNjc5MTE2LDAuMDUyNDM0NTU5NDI2ODQ0NTYsMC4wNzI0NzI2OTgyMDQ3Mjg1Nw0KMjAyMC0yMDIxLExpbcOzbiw5ODA0Ny44NDc5LDg5OTA4MjQ2LjE2MDAwMDAxLDAuOTE2OTgzMzcxNzQ4MjM0MiwwLjA3ODA5MTM1NzEzMjA4NTMyLC0wLjE2OTgyMDEyMTUxNDk0ODA3DQoyMDIxLTIwMjIsTGltw7NuLDczMTQ3LjE0ODIwMDAwMDAxLDU2NTQ0NjUxLjI0OTk5OTk5LDAuNzczMDI2MDUyODQ2MTcyMSwwLjA0NzU2NDM1ODYxODI2OTg1LC0wLjE1Njk5MDEwODM2NzYyMTQNCjIwMjItMjAyMyxMaW3Ds24sNjI4MzMuOTk2NTk5OTk5OTksNjgyOTIyNTAuNDIwMDAwMDIsMS4wODY4Njc4NDQwODY4MTExLDAuMDA5OTE1NjAyNTE0NzEzNTU2LDAuNDA1OTkxMjIxMjMzOTAwMw0KMjAyMy0yMDI0LExpbcOzbiw4MzI4MC45NjM0MDAwMDAwMiw4NDY5ODIxMi43Nzk5OTk5OSwxLjAxNzAxNzY4NzE0MTY5MjcsMC4wMDA5Nzc1ODg1MTQzNTM1Mzc2LC0wLjA2NDI2NzM4NzU0NDA3MzI0DQoyMDI0LTIwMjUsTGltw7NuLDEyNDg4MS4yNSwxMjMyNjYzMzQuODgsMC45ODcwNjgzOTQwMTQzMTM2LDAuMDYyMDg4NjU4NzM1OTg1MjksLTAuMDI5NDQ4MTUzNjYxNDY3ODAyDQoyMDE2LTIwMTcsTWFuZGFyaW5hLDExNTQxNC4zMzgyOTk5OTk5OSwxNzA3MzEwOTIuNTMsMS40NzkyODg0MDU5NzA5NTksMC4wLA0KMjAxNy0yMDE4LE1hbmRhcmluYSwxMjU0MjMuNjUzMywxODA5NTY3OTMuODEsMS40NDI3NjQ0OTQ5NjQ2ODMyLDAuMCwtMC4wMjQ2OTAxODk0NTc4ODUxNDgNCjIwMTgtMjAxOSxNYW5kYXJpbmEsMTYzODIwLjA3OTIsMjAyOTg1MDQ2LjMwMDAwMDA0LDEuMjM5MDczMDU2ODAyNjczMywxLjQwODk3MDc4NDg1OTIzODhlLTA2LC0wLjE0MTE4MTM0OTMyODI1MzMyDQoyMDE5LTIwMjAsTWFuZGFyaW5hLDE1ODE2MS4zNDEyMDAwMDAwMiwyMjIxNzEzMTAuNTkwMDAwMDMsMS40MDQ3MTMxMTcwMjU1OTA5LDAuMDAxMjYyNjEzNjA3NzM4MzYxNywwLjEzMzY4MDYyNDY1MjA1OQ0KMjAyMC0yMDIxLE1hbmRhcmluYSwxNzg1MjMuMDI2MTAwMDAwMDIsMTk2OTQwMzU3LjYwMDAwMDAyLDEuMTAzMTY1MDE5Njc0NzM2NywwLjAwNDg0NDcwNTAyNDU0MjkyMiwtMC4yMTQ2Njg4MTI5MzgzNzkyNQ0KMjAyMS0yMDIyLE1hbmRhcmluYSwxNjQ1ODUuNTk0Mjk5OTk5OTcsMTkyMjU2NTA4Ljg2LDEuMTY4MTI0NzY2MTkwNDI3NSwwLjAwMTUwNDQwMjkwMjc0MTg1OTMsMC4wNTg4ODQ4ODYwODQyNjMyMw0KMjAyMi0yMDIzLE1hbmRhcmluYSwxODMxMDguMjQ5MywyMDkxNjg3MTMuMCwxLjE0MjMyMjcxNzg0MzgyMTYsMC4wMDAyODA3MjIzODUwOTIwNzYzNSwtMC4wMjIwODg0MzUzMjI0OTg0OQ0KMjAyMy0yMDI0LE1hbmRhcmluYSwyMTI5MTguMjA1OSwyNzQ4NDMzNTUuMDEsMS4yOTA4NDAwODUwMzc1NTY4LDAuMDAwMTQ0MDczOTU4MDQ5ODgzNTgsMC4xMzAwMTM0OTM0NDk2MTYNCjIwMjQtMjAyNSxNYW5kYXJpbmEsMjExNTkzLjU2NjYwMDAwMDAyLDI0NTgyOTc1Mi4yMywxLjE2MTgwMTYzNzgyOTE5MDksMC4wLC0wLjA5OTk2NDcwNDE1MjAzNDA3DQoyMDE2LTIwMTcsTWFuZ29zIHkgZ3VheWFiYXMsMjYuNzg4LDMxOTcyLjE4LDEuMTkzNTI2MjA1NzYzNzc1LDAuMCwNCjIwMTctMjAxOCxNYW5nb3MgeSBndWF5YWJhcyw4LjM2NywyMDY2MS4wLDIuNDY5MzQzODUwODQyNTk1OCwwLjAsMS4wNjg5NDgxNjI5NDU3Njg3DQoyMDE4LTIwMTksTWFuZ29zIHkgZ3VheWFiYXMsOC40NjUsMzczMzcuOTc5OTk5OTk5OTk2LDQuNDEwODY1OTE4NDg3ODkwNCwwLjAsMC43ODYyNTAxODgyNzY4NTg5DQoyMDE5LTIwMjAsTWFuZ29zIHkgZ3VheWFiYXMsMC41NDcsMTg3Ny41LDMuNDMyMzU4MzE4MDk4NzIsMC4wLC0wLjIyMTg0MDI1MDUyNDkxNjc0DQoyMDIxLTIwMjIsTWFuZ29zIHkgZ3VheWFiYXMsMC4wNCwxODkuMCw0LjcyNSwwLjAsMC4zNzY2MDQ1MjcyOTY5Mzc0DQoyMDIyLTIwMjMsTWFuZ29zIHkgZ3VheWFiYXMsMC4xOSw5NDMuODQ5OTk5OTk5OTk5OSw0Ljk2NzYzMTU3ODk0NzM2OCwwLjAsMC4wNTEzNTA1OTg3MTkwMTk3DQoyMDIzLTIwMjQsTWFuZ29zIHkgZ3VheWFiYXMsMC4wOTQsNzQwLjAsNy44NzIzNDA0MjU1MzE5MTUsMC4wLDAuNTg0NzI3MTA3OTYzMTk3NQ0KMjAxNi0yMDE3LE1hbnphbmEsNzE4NDA3LjA2NTAwMDAwMDEsNjY5NDk4MzAwLjM4LDAuOTMxOTIwNTQwNTkyMTIyMywwLjAyMTE5NzUwMDI5NTI4ODIwNSwNCjIwMTctMjAxOCxNYW56YW5hLDc3MjgxOC41NDM1LDc0MjQ0MDA3NS4zNTk5OTk5LDAuOTYwNjkxMzMxMjM3NDQ3LDAuMDE5NjMyNTcyNjY2NDYzNzIyLDAuMDMwODcyNTc5MTQzOTczNDU1DQoyMDE4LTIwMTksTWFuemFuYSw3MTAzOTcuNzUzOSw2NDcwNjI1NzYuNTMsMC45MTA4NDU0NzA2OTI1ODQsMC4wNjI4MTQwNjU4NjM1NTk2LC0wLjA1MTg4NTQwNjgxNDk2MjY3Ng0KMjAxOS0yMDIwLE1hbnphbmEsNjIyODQ3Ljc2NDksNTU5MjQwMDA1LjU3OTk5OTksMC44OTc4NzU5MTMwMTY3MDI0LDAuMDI0NjI1NjcxMzYyMTg1NzUsLTAuMDE0MjM5MDMxODU5MDcwMjcyDQoyMDIwLTIwMjEsTWFuemFuYSw2Mzg3MzguNTMwNyw2MDE3NzgzNDkuNjEsMC45NDIxMzU2NjM3OTExMDU3LDAuMDE0NDM4MDExNTI5NzExNjAzLDAuMDQ5MjkzODM5MDg0ODQ0NTI2DQoyMDIxLTIwMjIsTWFuemFuYSw1OTUwOTUuMDUzMDk5OTk5OSw1MDg3NzUzNzAuNzQsMC44NTQ5NDgwNzYwOTI0ODQ4LDAuMDIyOTM1MTY1MDY3MTA2MDkyLC0wLjA5MjU0MjQ5NzkxMTM3NTU5DQoyMDIyLTIwMjMsTWFuemFuYSw1MjM3ODUuMzcwNyw1NDcwMzE1MzQuOTksMS4wNDQzODEwODczNTA1OTQsMC4wMTk3NzUwMjI1MTM0NjAzMSwwLjIyMTU3MjUzMzUzMTk4NjI1DQoyMDIzLTIwMjQsTWFuemFuYSw0OTY3NzkuOTYxMjk5OTk5OTcsNTQwMDE4NDQ0LjI5MDAwMDEsMS4wODcwMzc0OTQxNzkyMTY1LDAuMDE3Mzg4NDQ2NzI2NzUxNzA2LDAuMDQwODQzNzE4MjAzMzE3ODkNCjIwMjQtMjAyNSxNYW56YW5hLDU3ODMwNC41MjkyOTk5OTk5LDYzMzE5NDQ3Ny4wMiwxLjA5NDkxNTI5OTcwNjI2NTIsMC4wMTU0ODQyNzYxOTkyMjI2MjMsMC4wMDcyNDcwNDEyMTkxMjI3ODUNCjIwMTYtMjAxNyxNZW1icmlsbG8sMzc4Ljk5NDIsNzY4NjAwLjgyMDAwMDAwMDEsMi4wMjgwMDE1MzY2OTg5Nzg4LDAuMCwNCjIwMTctMjAxOCxNZW1icmlsbG8sNDc1LjA4NTc5OTk5OTk5OTk1LDg4ODU3NC4wOCwxLjg3MDM0NDQzMDQxNjU2OSwwLjAsLTAuMDc3NzQwMTMxNTY3NjY3MTMNCjIwMTgtMjAxOSxNZW1icmlsbG8sNDI0LjI5NjQwMDAwMDAwMDA2LDY5ODM4NS40NywxLjY0NTk4NDkwNTgzNDY5NDUsMC4wLC0wLjExOTk1NjI2MDk2MDkzMTM3DQoyMDE5LTIwMjAsTWVtYnJpbGxvLDQxNS40MTI3OTk5OTk5OTk5NSw3MDA4NjUuOTIsMS42ODcxNTUzMzA3OTM4NTE2LDAuMCwwLjAyNTAxMjYzODIxNjMxNDA1NA0KMjAyMC0yMDIxLE1lbWJyaWxsbywzMjkuMjQwODAwMDAwMDAwMDQsNTg2MjQ1LjU0LDEuNzgwNTk4MDkxMTIzNTc4OCwwLjAsMC4wNTUzODQ3OTk4NjA1Nzk0MjYNCjIwMjEtMjAyMixNZW1icmlsbG8sMzk5Ljg5OTUsMjc5NzQ4LjI5LDAuNjk5NTQ2NDg2MDU0NjIxMSwwLjAsLTAuNjA3MTI4MzYzNDc0MDk2DQoyMDIyLTIwMjMsTWVtYnJpbGxvLDM4Mi42NzEyLDYzODI0MC43OSwxLjY2Nzg1Njg3MDMzNjcyNzgsMC4wLDEuMzg0MTk3MzM4NjgzMzY1Nw0KMjAyMy0yMDI0LE1lbWJyaWxsbywzMTIuNjc2NCw1OTQ5NTIuODQwMDAwMDAwMSwxLjkwMjc3NTAwOTU2MjYwMjQsMC4wLDAuMTQwODUwMjk5MjA5Njk1Ng0KMjAyNC0yMDI1LE1lbWJyaWxsbywyOTEuNzU0Niw0ODIwODYuODUsMS42NTIzNzEwMzM3Mzg2Mjg0LDAuMCwtMC4xMzE1OTkzNjEyMzA1OTMwMQ0KMjAxNi0yMDE3LE1vcmEsNjk3LjQwNzk5OTk5OTk5OTksMTQyMTk0Ni4wNSwyLjAzODkwMTI2MDA5NDUyMiwwLjAsDQoyMDE5LTIwMjAsTW9yYSwyMTMuNzMzOSw2NDM0NTguMCwzLjAxMDU1NjU4NDYxMjkyMjcsMC4wLDAuNDc2NTU4MzAzMDExMzc1Ng0KMjAyMC0yMDIxLE1vcmEsNDY0LjUyOCwxNjA1NDAwLjAsMy40NTU5ODExMjQ5MjY4MDcsMC4wLDAuMTQ3OTU0MjE2MzY5OTc4NzQNCjIwMjEtMjAyMixNb3JhLDE0Ny4wMyw3MzgwMDAuMCw1LjAxOTM4Mzc5OTIyNDY0OCwwLjAsMC40NTIzNzU5Mjk2NjYyNjg0DQoyMDIyLTIwMjMsTW9yYSwyMjguNzY3LDEwNzE1NDcuOTAwMDAwMDAwMSw0LjY4NDAxNDMwMjc2MjIsMC4wLC0wLjA2NjgxNDg3NDA3MTY0NDY2DQoyMDIzLTIwMjQsTW9yYSwxMDUuNzYzLDQ4MTU5Ny45LDQuNTUzNTU3NDgyMjk1MzIxLDAuMCwtMC4wMjc4NTE0OTkxNzAyNjI1MjgNCjIwMTYtMjAxNyxOYXJhbmphLDgzMTU5Ljc3NTcsODA0NjIxNTIuMDEsMC45Njc1NjA5NTUxOTM4NzAzLDAuMCwNCjIwMTctMjAxOCxOYXJhbmphLDg0MjMxLjA3MTAwMDAwMDAxLDcxMjEwNzE2LjI5OTk5OTk4LDAuODQ1NDIxMDAwMjg2MjI0MSwwLjAsLTAuMTI2MjM0ODk0Mjk5OTM4OTUNCjIwMTgtMjAxOSxOYXJhbmphLDkzMTEzLjM1OTgsNzQ1OTM1NDMuMTcsMC44MDExMDQ2MjQ4MzgxNjQyLDEuOTMwNDYxOTkyODI3MjAwM2UtMDYsLTAuMDUyNDE5Mjk4MTE2NjI2MTU2DQoyMDE5LTIwMjAsTmFyYW5qYSw5ODkwMy45NTI0MDAwMDAwMSw5NjA5OTMyNy4xMzAwMDAwMSwwLjk3MTY0Mjk0MDQyOTE0MzEsMC4wMDA5NTUzMjkzNzM2OTkwMTgzLDAuMjEyODc4OTU1MjYxODQyNjQNCjIwMjAtMjAyMSxOYXJhbmphLDg2NjU5Ljc3MDYsMTAzNDk2MDU5LjM1LDEuMTk0MjgwMzI5MDc4MDkyMywwLjAwNTc1MDk5MDY1MzUzOTMxMywwLjIyOTEzNDk4MzAxMTk4NzU0DQoyMDIxLTIwMjIsTmFyYW5qYSwxMDA4OTkuMzk0Niw5MDM2MDE3NC4yNiwwLjg5NTU0NzIzOTA5MTE2NSwtOC4wODg2Mjk4MTkzMzc4NDVlLTA1LC0wLjI1MDEzNjQ5MDMzMDk4NDYNCjIwMjItMjAyMyxOYXJhbmphLDk0NjM2LjkyMSw5ODMzNzM2OS42NjAwMDAwMSwxLjAzOTEwMTUzMjY4ODI4MzgsMC4wLDAuMTYwMjk3ODQ2MjAwNTAwOTINCjIwMjMtMjAyNCxOYXJhbmphLDEwMzY2MS4wNzE0OTk5OTk5OSwxMTI0NTE2MDUuOTc5OTk5OTksMS4wODQ4MDA3Mjk0NjE4Nzg5LDAuMCwwLjA0Mzk3OTUyOTc1MzMyOTg2DQoyMDI0LTIwMjUsTmFyYW5qYSwxMTY0NDkuNDMwNzAwMDAwMDEsMTE1MDI2NDYxLjE2OTk5OTk5LDAuOTg3NzgwMzY1MDc4MjQ2NiwwLjAsLTAuMDg5NDM2MTE2NDY2OTkzNjgNCjIwMTYtMjAxNyxOZWN0YXLDrW4sNjE1MDguMTgyLDc4OTY4NDM3LjM1LDEuMjgzODY4ODI0OTYzODA3LDAuMDYxMDI5NzUzMDQ3Mjc4NzE1LA0KMjAxNy0yMDE4LE5lY3RhcsOtbiw2NjAyOC4wNDc0MDAwMDAwMSw5Njg3OTM3Ny4zNzAwMDAwMiwxLjQ2NzI0NTgzMjQxMjcyNywwLjI1MDc3NDUzNDc4MjcwNjMsMC4xNDI4MzE1NzU4NDU4MzQyOA0KMjAxOC0yMDE5LE5lY3RhcsOtbiw2NzA1OS4xOTg3LDEwMjcxMTMxNi4wMiwxLjUzMTY1MTQwNjY4NDY0MzIsMC4zODAwMzIxMzA1NjI5MDA3NSwwLjA0Mzg5NTU1NzgxOTM3OTE1DQoyMDE5LTIwMjAsTmVjdGFyw61uLDczMTE2LjIzMzAwMDAwMDAxLDk3OTU4NzczLjkzLDEuMzM5NzY3NzkwNDE2NjY0NSwwLjM4NTcxNjAwNzUwMTI3OTIsLTAuMTI1Mjc4OTA4MzkyOTUwMg0KMjAyMC0yMDIxLE5lY3RhcsOtbiw3MjA5My40ODgxLDEwMzU2MzUwNi4xNjAwMDAwMSwxLjQzNjUxNjc5MDc1ODUyNjMsMC40MDYwMjU2ODYxNjI0MTk5LDAuMDcyMjEzMjYwNDEyNjY2ODUNCjIwMjEtMjAyMixOZWN0YXLDrW4sODQ3OTMuNzIyNjAwMDAwMDIsODc2NDQyNTIuMTEwMDAwMDEsMS4wMzM2MTcyMjMzMzQ0MDc0LDAuMzU1NzQ1MjgwMzczNTI2NTQsLTAuMjgwNDY5NzkzMzMzNDgwNzcNCjIwMjItMjAyMyxOZWN0YXLDrW4sODExMTIuODc0NSwxMjQ4NjYxMjkuMjc5OTk5OTksMS41Mzk0MTE5NjIwMzA3NjIyLDAuNTAwNjMzODcyOTM2MjExLDAuNDg5MzQ0MzQwNzA3MzY3DQoyMDIzLTIwMjQsTmVjdGFyw61uLDkyNjg1LjgxMzQ5OTk5OTk5LDEzMDczODAyMy41MDAwMDAwMSwxLjQxMDU1MDUzMTU1NDY0ODcsMC40MjcxMDY3MjMyNDAzMTI3LC0wLjA4MzcwODIxNjkzODk2ODEzDQoyMDI0LTIwMjUsTmVjdGFyw61uLDExNjQxNi4xNDk3LDEzNjM4MTUwNC43MjAwMDAwMywxLjE3MTQ5OTg3NDEyNzg1OTMsMC40MjIxMTA1MDU4Nzk3NDQ3LC0wLjE2OTQ3MzMwMjg1NTI0NjINCjIwMTYtMjAxNyxPdHJvcyBiZXJyaWVzLDM4Mi43MDQyLDM1MzMyNjMuNzYwMDAwMDAwMiw5LjIzMjM2MjEyMTk3MzA1NCwwLjAsDQoyMDE3LTIwMTgsT3Ryb3MgYmVycmllcyw0NTYuODA3NSw3MDU0MDk1LjU5MDAwMDAwMSwxNS40NDIxNjIzNzY5MzEyMDIsMC4wLDAuNjcyNjEyMjkyODE0OTQ1Mg0KMjAxOC0yMDE5LE90cm9zIGJlcnJpZXMsMzUzLjI2MzksMzY1MTc1NS44NTk5OTk5OTk0LDEwLjMzNzE4OTQ0OTU4NzEyLDAuMCwtMC4zMzA1ODY2NjI4NDc4MzUzMw0KMjAxOS0yMDIwLE90cm9zIGJlcnJpZXMsNDcxLjYxMjg5OTk5OTk5OTk3LDIwNjUzNDMuMzEsNC4zNzkzMTg5NDk5MjY5NDMsMC4wLC0wLjU3NjM1MzAzMzc0NDQwMzUNCjIwMjAtMjAyMSxPdHJvcyBiZXJyaWVzLDM2OS45MTY3MDAwMDAwMDAwNSwyNDc4MzQ3LjYyLDYuNjk5NzQ1MTU4ODQyNTE3LDAuMCwwLjUyOTg2MDA2MTY3NzkyMDENCjIwMjEtMjAyMixPdHJvcyBiZXJyaWVzLDQzMy4wMTU1LDQ2MjYwNjcuOTg5OTk5OTk5LDEwLjY4MzM3NzM2MTc4MDM1MiwwLjAwMjkxMTk3NjIyNDU0MzEyNDcsMC41OTQ1OTQ1ODY1ODM2NTg2DQoyMDIyLTIwMjMsT3Ryb3MgYmVycmllcyw1MTAuMzM4ODAwMDAwMDAwMDUsNDMzNzU5Ni40NzAwMDAwMDEsOC40OTk0NDQ4MTk3OTQyMjQsMC4wLC0wLjIwNDQyMzQyMDQyNDk5NzczDQoyMDIzLTIwMjQsT3Ryb3MgYmVycmllcyw0NTEuNDA1NDk5OTk5OTk5OTYsNDk5NzUzMC40NiwxMS4wNzEwNDQ2ODE1NTU3MTksMC4wLDAuMzAyNTYwOTIyMDcwMTcyOA0KMjAyNC0yMDI1LE90cm9zIGJlcnJpZXMsOTI5Ljc4NjMwMDAwMDAwMDEsMTAzMjE0NTQuNzYwMDAwMDAyLDExLjEwMDg4OTI2ODg1NjcyNiwwLjAsMC4wMDI2OTU3MzM2MTQ5NzkzMjMNCjIwMTYtMjAxNyxPdHJvcyBjw610cmljb3MsMC41MjQsMzQwNi4wLDYuNSwwLjAsDQoyMDE3LTIwMTgsT3Ryb3MgY8OtdHJpY29zLDI0LjAsMjAxOTYuNzYsMC44NDE1MzE2NjY2NjY2NjY3LDAuMCwtMC44NzA1MzM1ODk3NDM1ODk3DQoyMDE4LTIwMTksT3Ryb3MgY8OtdHJpY29zLDEyMC40NDAwMDAwMDAwMDAwMSwxMjQyMjUuNTE5OTk5OTk5OTksMS4wMzE0MzA3NTM5MDIzNTc3LDAuMCwwLjIyNTY1ODg3MjY5MzI3MjkNCjIwMTktMjAyMCxPdHJvcyBjw610cmljb3MsMjUuMjYsMTAyNDM1LjQ2LDQuMDU1MjQzODYzODE2MzEsMC4wLDIuOTMxNjY4NTU2OTc2MzQ4Mw0KMjAyMC0yMDIxLE90cm9zIGPDrXRyaWNvcyw5Ni4wLDE2MTQ2My4zNSwxLjY4MTkwOTg5NTgzMzMzMzQsMC4wLC0wLjU4NTI1MDYxNTY2ODE0ODUNCjIwMTYtMjAxNyxPdHJvcyBmcnV0b3MsNTMxMS4yNjM2OTk5OTk5OTk1LDEwODc5ODg4LjcyLDIuMDQ4NDU1NzYwMTYxMTgzNSwwLjAsDQoyMDE3LTIwMTgsT3Ryb3MgZnJ1dG9zLDYwMjIuMTQwNzk5OTk5OTk5LDEyMDkwNzI0LjYyMDAwMDAwMSwyLjAwNzcxMjA0NDg1OTUyOTYsMC4wLC0wLjAxOTg4OTk2NTk0MTE5NjYzDQoyMDE4LTIwMTksT3Ryb3MgZnJ1dG9zLDM5ODcuNDIyODAwMDAwMDAwMyw4OTg5ODgxLjkyMDAwMDAwMiwyLjI1NDU1OTQ5MTQwODgzNywwLjAwMDE5MzI3MjgzODg5Mzk3MjksMC4xMjI5NDk2MjY3NTYxNTA5NQ0KMjAxOS0yMDIwLE90cm9zIGZydXRvcywzNjg0LjkzMjksODI4NTcwMC43OCwyLjI0ODUzNTA0OTMwODQ5NywwLjAsLTAuMDAyNjcyMTE0OTQwMTAxMTExMw0KMjAyMC0yMDIxLE90cm9zIGZydXRvcywzOTI5Ljg4MzAwMDAwMDAwMDMsMTAzNTk2MjMuMzEsMi42MzYxMTQ5NDU0MDY3NzE2LDAuMDAwMjg5NTIzMDc1MzMyNzQ1OCwwLjE3MjM2OTk1OTgxNzgyNDENCjIwMjEtMjAyMixPdHJvcyBmcnV0b3MsMjQ0NC42MjE3LDc4MDU4MDYuMDcsMy4xOTMwNTI3NjE0OTY3OTksMC4wLDAuMjExMjcyMjA0NTk4MDc2ODMNCjIwMjItMjAyMyxPdHJvcyBmcnV0b3MsMzYzOC44NjI5LDEwNDE1MzA4LjU1LDIuODYyMjQyNjM5MDM5Nzk0NiwwLjAsLTAuMTAzNjAzMDg2ODE1ODY5NQ0KMjAyMy0yMDI0LE90cm9zIGZydXRvcywxNzM0LjA1NjQ5OTk5OTk5OTcsNTk4MjEwMC4yMSwzLjQ0OTc3MjM3NDc3NTU2MzMsMC4wLDAuMjA1MjY5MDE3OTc5ODU1NTMNCjIwMjQtMjAyNSxPdHJvcyBmcnV0b3MsMzQ2NC40NDk5LDk2MzEyODcuMzQsMi43ODAwMzM2NjEzMzI0OTYzLDAuMCwtMC4xOTQxMzk5NzIzNDcyMDEzNw0KMjAxNi0yMDE3LFBhbHRhLDE1ODc2OS44OTg5MDAwMDAwMyw0MTE5ODU2NjIuMDksMi41OTQ4NjAwMTQwNDc2NjIsMC4wOTY4NTY3ODAxMzA1NzM3OSwNCjIwMTctMjAxOCxQYWx0YSwxNDkxNDYuMjY5MDk5OTk5OTgsNDM5NDAyNTk3LjI0OTk5OTk0LDIuOTQ2MTE4NTk4MjE1NzQzLDAuMDgzOTkwNDgzOTAwMTI2NzQsMC4xMzUzNjcwNjQ5OTI1MjAwNQ0KMjAxOC0yMDE5LFBhbHRhLDE1Mjc5NC4wNTQwOTk5OTk5OCwzNTk5NDcyMDIuMzgsMi4zNTU3NjcwNzgxMTE3MTMzLDAuMDgxNTc1MzQ5MDExODg0NywtMC4yMDAzODI4MDg5MTM5MjYzNQ0KMjAxOS0yMDIwLFBhbHRhLDEyNjg0OC44NDQyLDMzOTk5MzAyNy43NiwyLjY4MDMwMDU1Njk2Nzk0NCwwLjA2OTQ0MjUxODk3MDMxOTAxLDAuMTM3NzYxMjc2MDkyMDE2Ng0KMjAyMC0yMDIxLFBhbHRhLDc0MjgyLjIwMDc5OTk5OTk5LDIzNjA5NzIwMy4yOCwzLjE3ODM4MTkxMDMwMDEwNTQsMC4wNTA0NzkyMzA2OTE1NDYyLDAuMTg1ODMwNDEwNzExNzAzNw0KMjAyMS0yMDIyLFBhbHRhLDEyNjUyMC44NDE1MDAwMDAwMSwzMDQ4MjIxNTkuNzI5OTk5OTYsMi40MDkyNjQ0MDM1MjUxNjg3LDAuMDc4MTk3NDU1MTM2MTc5NDQsLTAuMjQxOTgzOTgwNjc5NzUyOQ0KMjAyMi0yMDIzLFBhbHRhLDg4NjM1LjA3MDksMjExNzEyMTE5LjU2LDIuMzg4NTgxODI2Njk5OTMyNCwwLjA4NzAzNTg0Nzg2ODc3NDcsLTAuMDA4NTg0NjAyMzM1NDU3MzI1DQoyMDIzLTIwMjQsUGFsdGEsOTExNDIuNzEwMywyNzQwNjYwMTYuNDYwMDAwMDQsMy4wMDY5OTg3NTU2NjQ2MSwwLjA4NzAwOTkwMjIwNTM3MDI2LDAuMjU4OTA1NDgxOTI3MzU5MDcNCjIwMjQtMjAyNSxQYWx0YSwxMzMwNTUuMzUwODAwMDAwMDQsMzc4ODQwMTYxLjA5OTk5OTk2LDIuODQ3MjM3MzI1MDg0NzExLDAuMDYyNjAxMTgxOTg5NjI1MTIsLTAuMDUzMTI5ODYyNTUxMTM2Mzg2DQoyMDE3LTIwMTgsUGFwYXlhLDAuNjIsOTMwLjAsMS41LDAuMCwNCjIwMjMtMjAyNCxQYXBheWEsMS4xNTEsNDg4Mi43LDQuMjQyMTM3MjcxOTM3NDQ1NSwwLjAsMS44MjgwOTE1MTQ2MjQ5NjM3DQoyMDE2LTIwMTcsUGVyYSwxNTMxMzMuNTM2OCwxNDA4MDE3MTkuMjQsMC45MTk0NzAxNzA4MjE1MjMyLDAuMCwNCjIwMTctMjAxOCxQZXJhLDEyOTQxMi44MjU5MDAwMDAwMywxMjkzMjE2MTQuMzgwMDAwMDEsMC45OTkyOTUxODk0ODg2MzMyLDAuMDAwMjY4NTQwMDI4NDEyODQzNTMsMC4wODY4MTYzMjIyNjkzNjU2NA0KMjAxOC0yMDE5LFBlcmEsMTMwNzA0LjM5ODAwMDAwMDAyLDEyODM3MDE2NS44Mzk5OTk5OSwwLjk4MjE0MTEzNTI5Njc2MzEsMC4wMTEyMzQ1MTAyOTczMzQzNjcsLTAuMDE3MTY2MTUzMDc2OTk4NTM2DQoyMDE5LTIwMjAsUGVyYSwxMTUyNjAuMTY4Mjk5OTk5OTksMTI0MDQzNTg4LjAsMS4wNzYyMDUxNjExNTQ1MzIyLDAuMDIxODY1ODcxMDUxNzE0NDk2LDAuMDk1Nzc0NDQ4NzgwNTY4NTENCjIwMjAtMjAyMSxQZXJhLDEyMTIzMy40MDcxLDEyNjY4NTQ0Ni4wNDk5OTk5OCwxLjA0NDk3MTQyMzk2OTgyMDcsMC4wMzExOTI0ODgyNzA4MzQwMTYsLTAuMDI5MDIyMTAzMTM4MDM0MjE2DQoyMDIxLTIwMjIsUGVyYSwxMTc2ODYuMjY1MDAwMDAwMDEsMTI1OTUwNjUwLjI2LDEuMDcwMjIzODcyNDI4OTUzMiwwLjAzNTQ4NDcyOTY5OTg3ODI1LDAuMDI0MTY1NjgzMjcxMjIyMDM4DQoyMDIyLTIwMjMsUGVyYSwxMDg0MjkuODE3MSwxMjI3MTk4NTkuNTE5OTk5OTgsMS4xMzE3OTA3MDg1MTcyMDUyLDAuMDU0NzIwOTgyMzc2MTcwMTgsMC4wNTc1MjcwNjI5NTc4ODUwMQ0KMjAyMy0yMDI0LFBlcmEsMTAxNDYzLjg0NTA5OTk5OTk5LDExNDc0MjIxMi4yNiwxLjEzMDg2Nzk2NzI3MzU5NiwwLjAxNzY3MzI5OTU2NDgxMDA1LC0wLjAwMDgxNTI5MzE3ODAyNzc1MzkNCjIwMjQtMjAyNSxQZXJhLDEwOTk4Ny40MDk5LDEyMTY2MjM4Ni4xOSwxLjEwNjE0ODI5NzM0MjUzMDcsMC4wMDkyMDA1MzUzMDk2NzE2MjMsLTAuMDIxODU5MDIzOTA1OTEzNDMzDQoyMDE2LTIwMTcsUGnDsWEsMi4zNDk1OTk5OTk5OTk5OTk3LDU2MjgyLjg2LDIzLjk1NDIzMDUwNzMyMDM5NiwwLjAsDQoyMDE3LTIwMTgsUGnDsWEsMS42NDMwMDAwMDAwMDAwMDAyLDE1MTg0Ljc2LDkuMjQyMDkzNzMwOTc5OTE0LDAuMCwtMC42MTQxNzY5NzI2OTk4NTINCjIwMTgtMjAxOSxQacOxYSw0LjI4NzAwMDAwMDAwMDAwMSw5NDk3MC41NCwyMi4xNTMxNDY3MjI2NDk4NjUsMC4wLDEuMzk2OTgzNTU4ODY1MTg2Nw0KMjAxOS0yMDIwLFBpw7FhLDYuNjM2LDE3NDA5OC43NywyNi4yMzU0OTg3OTQ0NTQ0OSwwLjAsMC4xODQyNzg2NTQ1MzY3MjcyDQoyMDIwLTIwMjEsUGnDsWEsMS4wNzYsNjIzMi4yOCw1Ljc5MjA4MTc4NDM4NjYxNywwLjAsLTAuNzc5MjI3MzA0NTg1ODQxOA0KMjAyMS0yMDIyLFBpw7FhLDAuMjA2NCw2NTc1LjU4LDMxLjg1ODQzMDIzMjU1ODE0LDAuMCw0LjUwMDM0MTkxODI0MzgxNA0KMjAyMi0yMDIzLFBpw7FhLDAuMDk0LDY4Ni42NCw3LjMwNDY4MDg1MTA2MzgyOTUsMC4wLC0wLjc3MDcxNDM1MTAyOTE3NTQNCjIwMTYtMjAxNyxQbHVtY290cyw3MTkuMjEyMzAwMDAwMDAwMSw5NTg4NjAuODA5OTk5OTk5OSwxLjMzMzIwOTY5MzQzODIyMzYsMC4wLA0KMjAxNy0yMDE4LFBsdW1jb3RzLDEwMDEuNzEwMywxNzkxMjg5LjUsMS43ODgyMzEwODgzNjk1NjE2LDAuMCwwLjM0MTI5NzY5NDcwNjg4NDY1DQoyMDE4LTIwMTksUGx1bWNvdHMsNDE1LjgyMTIwMDAwMDAwMDAzLDUyNzkzOS4xNTk5OTk5OTk5LDEuMjY5NjMwMjE2MDY0MDE5NiwwLjA3NjkxNzk5MTgzODMwMTk3LC0wLjI5MDAwNzc0ODgxODYyODIzDQoyMDE5LTIwMjAsUGx1bWNvdHMsMjU2LjczNTIsMzAyMjczLjI1LDEuMTc3MzczNjEyOTY3NzU4LDAuMDQ2NjMzMzAyODE0NTg5MTIsLTAuMDcyNjY0MTUyMDcyNzcxMzMNCjIwMjAtMjAyMSxQbHVtY290cywyMjkuMzYzNywyODQzMjQuOTYsMS4yMzk2MjQ5Mjc1NzEzNjQsMC4wLDAuMDUyODczMDMzNjA0NTkzNQ0KMjAyMS0yMDIyLFBsdW1jb3RzLDQwLjU0Miw2OTE1Mi43NiwxLjcwNTcwNjY3NDU1OTcxNTYsMC4wLDAuMzc1OTg2MTA0MDM5OTQxMjYNCjIwMjItMjAyMyxQbHVtY290cywxNTEuMjY2MDAwMDAwMDAwMDIsMjQ3MTUwLjA3LDEuNjMzODc3MjA5NjgzNjAzNCwwLjAsLTAuMDQyMTExMjY0NDY3MzUyMjUNCjIwMjMtMjAyNCxQbHVtY290cyw1MC4xMTIsNzUxMDcuMCwxLjQ5ODc4MjcyNjY5MjIwOTYsMC4wLC0wLjA4MjY4MzM3NTU4NzA1MTk3DQoyMDI0LTIwMjUsUGx1bWNvdHMsNDMwLjE1NDksODY5MzI5LjQ5LDIuMDIwOTY4NDY5NzMwMzIzLDAuMCwwLjM0ODQwNjU2NjAzNDEzNzENCjIwMTYtMjAxNyxQbMOhdGFubywzOC4wOTI0LDU2MDc4NC45NzAwMDAwMDAxLDE0LjcyMTcwMjIyOTMxNjA4OCwwLjAsDQoyMDE3LTIwMTgsUGzDoXRhbm8sMzguOTAwNDAwMDAwMDAwMDA1LDQzNzg1Ny44OSwxMS4yNTU4NzExNDc4NTQ1MTksMC4wLC0wLjIzNTQyMzI1NjU5NTk1ODA5DQoyMDE4LTIwMTksUGzDoXRhbm8sMzIuNzA2NiwzOTAzOTQuNzMwMDAwMDAwMDQsMTEuOTM2MjY3NjAzNDgwNjQ0LDAuMCwwLjA2MDQ0ODEzODI4MTY2NTk1DQoyMDE5LTIwMjAsUGzDoXRhbm8sMjguOTM1LDM4MjU0Mi4xMSwxMy4yMjA3Mzk5MzQzMzU1OCwwLjAsMC4xMDc2MTA4ODU4NzUyNzgyMw0KMjAyMC0yMDIxLFBsw6F0YW5vLDMwLjE3MTYsMTYwMzYzLjIyLDUuMzE1MDM4NjQ1NjEzNzU2LDAuMCwtMC41OTc5NzcyMTgyMTgzMTg1DQoyMDIxLTIwMjIsUGzDoXRhbm8sMTguMzc1OTk5OTk5OTk5OTk4LDI2NzY4OS43LDE0LjU2NzM1NDE1NzU5Njg2OSwwLjAsMS43NDA3ODA0Nzc2MDE3Mg0KMjAyMi0yMDIzLFBsw6F0YW5vLDI4LjU3NTUsMzU5ODA5LjM2OTk5OTk5OTk0LDEyLjU5MTUzMzY1NjQ1Mzk1MywwLjAsLTAuMTM1NjMzNDQ5OTU3MTc4ODUNCjIwMjMtMjAyNCxQbMOhdGFubywyLjE4LDU3NzAuMCwyLjY0Njc4ODk5MDgyNTY4OCwwLjAsLTAuNzg5Nzk2MTM4OTczOTgwOQ0KMjAyNC0yMDI1LFBsw6F0YW5vLDAuMjA0LDMzODIuOTQsMTYuNTgzMDM5MjE1Njg2Mjc3LDAuMCw1LjI2NTM0MjM3MjY1MDk2Nw0KMjAxNi0yMDE3LFBvbWVsbywxNTg2LjQzLDEyNDg3NDEuNzMwMDAwMDAwMiwwLjc4NzEzOTUwODIwMzk1NDgsMC4wLA0KMjAxNy0yMDE4LFBvbWVsbywyNDQwLjI5ODkwMDAwMDAwMDcsMjMxMTAzMy42OSwwLjk0NzAyODk0Mzg3MjQwODEsMC4wLDAuMjAzMTI3MTg5MDIwNTA2NDINCjIwMTgtMjAxOSxQb21lbG8sMTA0Mi45MjM2LDgwMTk3OC45NCwwLjc2ODk3MTg5Nzg0NTYzMywwLjAsLTAuMTg4MDE2NDc3NDA0MjY4NzQNCjIwMTktMjAyMCxQb21lbG8sMTgzMy4xOTI0OTk5OTk5OTk5LDExODM3OTUuNjQsMC42NDU3NTYzMTg1NTM1NjE2LDAuMCwtMC4xNjAyMzQxNzcxMzYwODg1Ng0KMjAyMC0yMDIxLFBvbWVsbywyMDUzLjkxOTksMTQ3ODM0Mi4yNjAwMDAwMDAyLDAuNzE5NzY2MjY3NDE4NzA1MywwLjEyMjE1Nzk3NzEzODUyODEyLDAuMTE0NjA5NzE2OTE0NDUzOTkNCjIwMjEtMjAyMixQb21lbG8sOTgyLjUyMTUsODQwNzczLjYzLDAuODU1NzMwNTE1ODIwNzczNCwwLjAsMC4xODg5MDA1NTY0MTIxMTk3OA0KMjAyMi0yMDIzLFBvbWVsbyw3ODkuMTU4MTAwMDAwMDAwMSw3ODE5NTEuOTQwMDAwMDAwMSwwLjk5MDg2ODU0NzEyNjM2MTYsMC4wLDAuMTU3OTIxMjQ4MzQ1MzA0OTcNCjIwMjMtMjAyNCxQb21lbG8sODQ5LjIyMTQsODk4OTE1LjUyOTk5OTk5OTksMS4wNTg1MTcyODQxODUyNTQ4LDAuMCwwLjA2ODI3MjE2MTA4MDM4MDAzDQoyMDI0LTIwMjUsUG9tZWxvLDE0MTAuNDk5NDk5OTk5OTk5NywxMzcxNDM0LjYzMDAwMDAwMDEsMC45NzIzMDQyMjk4MTM2MjMxLDAuMCwtMC4wODE0NDY5OTcyODU0NDM4DQoyMDE2LTIwMTcsVXZhLDczMTAyOS43MzAyLDEyNzg3NjQ4NjQuNywxLjc0OTI2NTE5NjU3NDM1NDIsMC4xNDUyMjQ3MjgxMDAwODU0LA0KMjAxNy0yMDE4LFV2YSw3Mjg4MzUuNDgxNTk5OTk5OSwxMjQzMDk4MzQxLjgzLDEuNzA1NTk1MjU4NzU1ODU0NywwLjE2Mjc5NDM3MTY3NjI0NzUsLTAuMDI0OTY0NzMyNTY1NDMzNjM0DQoyMDE4LTIwMTksVXZhLDY1NDQ5MS40MzcsMTI1NDQ5MzI1Ny42NiwxLjkxNjc0NTEwNDI3NTUyMDEsMC4xNjQwODYwOTA3NjQ2MTc5LDAuMTIzNzk4MzMwNDg2NTAwNDYNCjIwMTktMjAyMCxVdmEsNjA0NzM0LjU5OCwxMDM1NDYzMzI1LjEyLDEuNzEyMjYwNzY0NTQ3ODIyNSwwLjE0ODc4NDc1MTQyNzIzNzUsLTAuMTA2NjgzMTE1NzAwNDUwNjQNCjIwMjAtMjAyMSxVdmEsNTI1NDM2LjQ4MzU5OTk5OTksOTE2NjM1ODU1LjMyLDEuNzQ0NTIyNjY2MjU5NzEzMywwLjE0ODgyNTYxOTI2NjYzNDMsMC4wMTg4NDE2OTg4Njk2Mjg5NDINCjIwMjEtMjAyMixVdmEsNjA4MTMyLjY0ODcsODcwNjk5ODk2LjcxLDEuNDMxNzU5ODI4MzM4OTEyNCwwLjExODYyNjI3MjgyOTgwMDk3LC0wLjE3OTI4Mjc1OTY3Mzk1MTM1DQoyMDIyLTIwMjMsVXZhLDQ5NjQwNS4xMTg0MDAwMDAwNCw4OTc1NDE4OTcuOTgsMS44MDgwODM0ODgwODUxNjI0LDAuMTMwOTEyNDIxMzYzNzc0ODcsMC4yNjI4Mzk5MzQ2NzE3NjAwMw0KMjAyMy0yMDI0LFV2YSw1MjgwODMuMTE4NSwxMzU3NjA5MDk3Ljk4LDIuNTcwODI0NjQ5NDE1NDg3NiwwLjA0ODQyNTA4Mjk0MDE2MTk4NCwwLjQyMTg1MDYzMTU0MjUxODM0DQoyMDI0LTIwMjUsVXZhLDU1Njk3My4yMzExLDk4Mzg3Njg3MS4zNiwxLjc2NjQ3MDY2MDM4ODYxOTMsMC4wNjE2NzAyODIwMzA0NDE4OSwtMC4zMTI4Nzc4MTEwOTgzNzYyDQo=", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactMercado.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Temporada", type text}, {"Producto", type text}, {"Toneladas", type number}, {"USD_FOB", type number}, {"USD_kg", type number}, {"Cuota_China_valor", type number}, {"Cambio_valor_unitario", type number}}, "en-US")
in Tipos