let
    Binario = if RutaDatos = "" then Binary.FromText("77u/Q1VULENvbXVuYSxFc3BlY2llLFJpZWdvLEhlY3RhcmVhcyxBbmlvDQowNjMwMSxTYW4gRmVybmFuZG8sQXLDoW5kYW5vIEFtZXJpY2FubyxHb3Rlbyw4LjQ4LDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxDZXJlem8sR290ZW8sMjg2OC41NCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sQ2VyZXpvLE1pY3JvIGFzcGVyc2nDs24sMTczLjcyLDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxDZXJlem8sU3VyY28sMTM3LjAsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLENlcmV6byxUZW5kaWRvLDQ3LjIzMDAwMDAwMDAwMDAwNCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sQ2lydWVsbyBFdXJvcGVvLEdvdGVvLDIwNS4zMjk5OTk5OTk5OTk5OCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sQ2lydWVsbyBKYXBvbsOpcyxHb3Rlbyw3Mi42OCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sQ2lydWVsbyBKYXBvbsOpcyxNaWNybyBhc3BlcnNpw7NuLDYuNCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sQ2lydWVsbyBKYXBvbsOpcyxTdXJjbywyNi41MywyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sRHVyYXpuZXJvIENvbnN1bW8gRnJlc2NvLEdvdGVvLDIuMDMsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLEtpd2ksR290ZW8sMjYzLjI3LDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxLaXdpLE1pY3JvIGFzcGVyc2nDs24sMTEwLjYyLDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxLaXdpLFN1cmNvLDMuMjIsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLEtpd2ksVGVuZGlkbywyOS4yLDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxLaXdpIEdvbGQgbyBLaXdpIEFtYXJpbGxvLEdvdGVvLDE5LjEyLDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxLaXdpIEdvbGQgbyBLaXdpIEFtYXJpbGxvLE1pY3JvIGFzcGVyc2nDs24sMi4zMSwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBSb2pvLEdvdGVvLDI3My42NCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBSb2pvLE1pY3JvIGFzcGVyc2nDs24sNDMuOSwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBSb2pvLFBsYXRhYmFuZGEsMS4yNywyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBSb2pvLFN1cmNvLDU1LjE4LDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxNYW56YW5vIFJvam8sVGVuZGlkbyw1MC43NiwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBWZXJkZSxHb3Rlbyw3Ny45OCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTWFuemFubyBWZXJkZSxNaWNybyBhc3BlcnNpw7NuLDkuNDUsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLE1hbnphbm8gVmVyZGUsUGxhdGFiYW5kYSwwLjEzLDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxNYW56YW5vIFZlcmRlLFN1cmNvLDgyLjQsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLE1hbnphbm8gVmVyZGUsVGVuZGlkbywzNy4xNSwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sTmVjdGFyaW5vLEdvdGVvLDM3LjgsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLE5lY3RhcmlubyxNaWNybyBhc3BlcnNpw7NuLDMuNzksMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLE5vZ2FsLEdvdGVvLDc0LjEsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLE5vZ2FsLE1pY3JvIGFzcGVyc2nDs24sMTAuMCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sT2xpdm8sR290ZW8sNTYuNzQsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLFBlcmFsLEdvdGVvLDIwNS4xMywyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sUGVyYWwsTWljcm8gYXNwZXJzacOzbiw0MS43MzAwMDAwMDAwMDAwMDQsMjAyNA0KMDYzMDEsU2FuIEZlcm5hbmRvLFBlcmFsLFN1cmNvLDI2Ljg0MDAwMDAwMDAwMDAwMywyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sUGVyYWwsVGVuZGlkbyw2MS4xOCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sUGx1b3RzLEdvdGVvLDEuMiwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sUGx1b3RzLE1pY3JvIGFzcGVyc2nDs24sMS43MywyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sVmlkIGRlIE1lc2EsR290ZW8sNDMyLjc4LDIwMjQNCjA2MzAxLFNhbiBGZXJuYW5kbyxWaWQgZGUgTWVzYSxTdXJjbywyMC40NCwyMDI0DQowNjMwMSxTYW4gRmVybmFuZG8sVmlkIGRlIE1lc2EsVGVuZGlkbywyMS4xNiwyMDI0DQowNjMwMixDaMOpcGljYSxBbG1lbmRybyxHb3RlbywwLjg2LDIwMjQNCjA2MzAyLENow6lwaWNhLEFyw6FuZGFubyBBbWVyaWNhbm8sR290ZW8sOS4xMSwyMDI0DQowNjMwMixDaMOpcGljYSxDZXJlem8sR290ZW8sNzMzLjM2LDIwMjQNCjA2MzAyLENow6lwaWNhLENlcmV6byxTdXJjbyw1LjgzLDIwMjQNCjA2MzAyLENow6lwaWNhLENpcnVlbG8gRXVyb3BlbyxHb3Rlbyw1NzcuNjUsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsQ2lydWVsbyBFdXJvcGVvLFN1cmNvLDI0LjM5LDIwMjQNCjA2MzAyLENow6lwaWNhLENpcnVlbG8gRXVyb3BlbyxUZW5kaWRvLDU5LjQxLDIwMjQNCjA2MzAyLENow6lwaWNhLENpcnVlbG8gSmFwb27DqXMsR290ZW8sMzcuMDEsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsRGFtYXNjbyxHb3Rlbyw0LjM5LDIwMjQNCjA2MzAyLENow6lwaWNhLER1cmF6bmVybyBDb25zdW1vIEZyZXNjbyxHb3RlbywwLjQzLDIwMjQNCjA2MzAyLENow6lwaWNhLER1cmF6bmVybyBUaXBvIENvbnNlcnZlcm8sR290ZW8sMTI5LjksMjAyNA0KMDYzMDIsQ2jDqXBpY2EsRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxUZW5kaWRvLDEyLjIsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsTGltb25lcm8sVGVuZGlkbywxLjQ3MDAwMDAwMDAwMDAwMDIsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsTWFuZGFyaW5vLEdvdGVvLDIzLjIxLDIwMjQNCjA2MzAyLENow6lwaWNhLE1hbnphbm8gUm9qbyxHb3RlbywzNy45MzAwMDAwMDAwMDAwMSwyMDI0DQowNjMwMixDaMOpcGljYSxNYW56YW5vIFZlcmRlLEdvdGVvLDIzLjc2LDIwMjQNCjA2MzAyLENow6lwaWNhLE5hcmFuam8sR290ZW8sMzUuMCwyMDI0DQowNjMwMixDaMOpcGljYSxOZWN0YXJpbm8sR290ZW8sMjguNjQsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsTm9nYWwsR290ZW8sMTQxLjYxLDIwMjQNCjA2MzAyLENow6lwaWNhLFBhbHRvLEdvdGVvLDIxLjMsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsUGFsdG8sVGVuZGlkbywwLjk5LDIwMjQNCjA2MzAyLENow6lwaWNhLFBlcmFsLEdvdGVvLDY3Ljg4LDIwMjQNCjA2MzAyLENow6lwaWNhLFBlcmFsLFN1cmNvLDIuMSwyMDI0DQowNjMwMixDaMOpcGljYSxQZXJhbCxUZW5kaWRvLDcuNTMsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsVmlkIGRlIE1lc2EsR290ZW8sMzE3LjI4LDIwMjQNCjA2MzAyLENow6lwaWNhLFZpZCBkZSBNZXNhLFN1cmNvLDkuOTcsMjAyNA0KMDYzMDIsQ2jDqXBpY2EsVmlkIGRlIE1lc2EsVGVuZGlkbyw2MC45OSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxBbG1lbmRybyxUZW5kaWRvLDAuODksMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sQXLDoW5kYW5vIEFtZXJpY2FubyxHb3Rlbyw1Ni4wMTk5OTk5OTk5OTk5OTYsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sQXZlbGxhbm8sR290ZW8sMS4zNywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxDZXJlem8sR290ZW8sMzk0OS42NSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxDZXJlem8sTWljcm8gYXNwZXJzacOzbiw1MDcuODMsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sQ2VyZXpvLFN1cmNvLDQ4Ny44OCwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxDZXJlem8sVGVuZGlkbywzNy4zLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLENpcnVlbG8gRXVyb3BlbyxHb3RlbywxODQuOTEsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sQ2lydWVsbyBFdXJvcGVvLFRlbmRpZG8sMTIuNSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxDaXJ1ZWxvIEphcG9uw6lzLEdvdGVvLDY4LjM5LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLER1cmF6bmVybyBDb25zdW1vIEZyZXNjbyxTdXJjbywyLjcsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxHb3RlbywxODEuNTksMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxUZW5kaWRvLDEyLjAsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sRnJhbWJ1ZXNhLEdvdGVvLDQ2LjY5LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLEZyYW1idWVzYSxTdXJjbyw2LjEsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sRnJhbWJ1ZXNhLFRlbmRpZG8sMC4yLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLEhhcmR5IEtpd2kgbyBCYWJ5IEtpd2ksR290ZW8sMi41LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLEhhcmR5IEtpd2kgbyBCYWJ5IEtpd2ksTWljcm8gYXNwZXJzacOzbiwxLjUsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sSGFyZHkgS2l3aSBvIEJhYnkgS2l3aSxUZW5kaWRvLDAuODUwMDAwMDAwMDAwMDAwMSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxIaWd1ZXJhLEdvdGVvLDIuNSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxLaXdpLEdvdGVvLDI5OS4yODAwMDAwMDAwMDAwMywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxLaXdpLE1pY3JvIGFzcGVyc2nDs24sMjQ2Ljc3LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLEtpd2ksU3VyY28sMTAxLjM4LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLEtpd2ksVGVuZGlkbyw5LjEyMDAwMDAwMDAwMDAwMSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxLaXdpIEdvbGQgbyBLaXdpIEFtYXJpbGxvLE1pY3JvIGFzcGVyc2nDs24sNS4zNCwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxNYW5kYXJpbm8sR290ZW8sNS4wLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE1hbnphbm8gUm9qbyxHb3RlbywzNTkuNjksMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWFuemFubyBSb2pvLE1pY3JvIGFzcGVyc2nDs24sMjgxLjM1LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE1hbnphbm8gUm9qbyxTdXJjbyw0MDcuNzYsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWFuemFubyBSb2pvLFRlbmRpZG8sMjUuODgsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWFuemFubyBWZXJkZSxHb3Rlbyw2OC42NywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxNYW56YW5vIFZlcmRlLE1pY3JvIGFzcGVyc2nDs24sNDcuMDQsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWFuemFubyBWZXJkZSxTdXJjbywxNTkuNDYsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWFuemFubyBWZXJkZSxUZW5kaWRvLDUuNzEsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTWVtYnJpbGxvLEdvdGVvLDEzLjg5LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE1lbWJyaWxsbyxTdXJjbywxMy44NCwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxNb3JhcyBDdWx0aXZhZGFzIGUgSMOtYnJpZG9zLEdvdGVvLDUuMDcsMjAyNA0KMDYzMDMsQ2hpbWJhcm9uZ28sTW9yYXMgQ3VsdGl2YWRhcyBlIEjDrWJyaWRvcyxTdXJjbywyMC4wMiwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxNb3JhcyBDdWx0aXZhZGFzIGUgSMOtYnJpZG9zLFRlbmRpZG8sMC4yLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE5hcmFuam8sR290ZW8sMS4yLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE5lY3RhcmlubyxHb3Rlbyw0My44NSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxOZWN0YXJpbm8sU3VyY28sMi4yLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLE5lY3RhcmlubyxUZW5kaWRvLDMuMCwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxOb2dhbCxHb3RlbywyNDAuMywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxOb2dhbCxNaWNybyBhc3BlcnNpw7NuLDE5My4yNywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxOb2dhbCxTdXJjbywyLjY1LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFBhbHRvLEdvdGVvLDIuMCwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxQYWx0byxNaWNybyBhc3BlcnNpw7NuLDIuNjk5OTk5OTk5OTk5OTk5NywyMDI0DQowNjMwMyxDaGltYmFyb25nbyxQZXJhbCxHb3Rlbyw5Ni43NSwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxQZXJhbCxNaWNybyBhc3BlcnNpw7NuLDU5LjQ2LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFBlcmFsLFN1cmNvLDQxLjIyLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFBlcmFsLFRlbmRpZG8sNy41LDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFBsdW90cyxHb3RlbywzLjIyLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFR1bmEsU3VyY28sMy4wLDIwMjQNCjA2MzAzLENoaW1iYXJvbmdvLFZpZCBkZSBNZXNhLEdvdGVvLDExMS4zNiwyMDI0DQowNjMwMyxDaGltYmFyb25nbyxWaWQgZGUgTWVzYSxNaWNybyBhc3BlcnNpw7NuLDIuNCwyMDI0DQowNjMwNCxMb2xvbCxBbG1lbmRybyxHb3RlbywyMzIuOTUsMjAyNA0KMDYzMDQsTG9sb2wsQXLDoW5kYW5vIEFtZXJpY2FubyxHb3Rlbyw0Mi4xOSwyMDI0DQowNjMwNCxMb2xvbCxDZXJlem8sR290ZW8sMTM5LjA5LDIwMjQNCjA2MzA0LExvbG9sLENpcnVlbG8gRXVyb3BlbyxHb3RlbywxMDk1LjM0LDIwMjQNCjA2MzA0LExvbG9sLENpcnVlbG8gRXVyb3BlbyxNaWNybyBhc3BlcnNpw7NuLDE2Ljc1LDIwMjQNCjA2MzA0LExvbG9sLER1cmF6bmVybyBUaXBvIENvbnNlcnZlcm8sR290ZW8sODAuNDgsMjAyNA0KMDYzMDQsTG9sb2wsS2l3aSxHb3RlbywzMS4wMSwyMDI0DQowNjMwNCxMb2xvbCxMaW1vbmVybyxHb3RlbywxMC4yMSwyMDI0DQowNjMwNCxMb2xvbCxMaW1vbmVybyxTdXJjbywwLjE0LDIwMjQNCjA2MzA0LExvbG9sLE1hbmRhcmlubyxHb3Rlbyw3OC4xNzk5OTk5OTk5OTk5OSwyMDI0DQowNjMwNCxMb2xvbCxOYXJhbmpvLEdvdGVvLDcuOCwyMDI0DQowNjMwNCxMb2xvbCxOYXJhbmpvLFN1cmNvLDAuMTQsMjAyNA0KMDYzMDQsTG9sb2wsTmVjdGFyaW5vLEdvdGVvLDcuNywyMDI0DQowNjMwNCxMb2xvbCxOb2dhbCxHb3RlbywxNjUuNzksMjAyNA0KMDYzMDQsTG9sb2wsT2xpdm8sR290ZW8sNzg1Ljg0LDIwMjQNCjA2MzA0LExvbG9sLE9saXZvLFN1cmNvLDAuODUwMDAwMDAwMDAwMDAwMSwyMDI0DQowNjMwNCxMb2xvbCxQYWx0byxHb3RlbywxMzUuMzgsMjAyNA0KMDYzMDQsTG9sb2wsUGFsdG8sU3VyY28sMC4zLDIwMjQNCjA2MzA0LExvbG9sLFZpZCBkZSBNZXNhLEdvdGVvLDQ2LjI2LDIwMjQNCjA2MzA1LE5hbmNhZ3VhLEFyw6FuZGFubyBBbWVyaWNhbm8sR290ZW8sMTAuMjMsMjAyNA0KMDYzMDUsTmFuY2FndWEsQ2VyZXpvLEdvdGVvLDQwNC4xLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLENlcmV6byxUZW5kaWRvLDIxLjUyLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLENpcnVlbG8gRXVyb3BlbyxHb3RlbywzMjcuNzgsMjAyNA0KMDYzMDUsTmFuY2FndWEsQ2lydWVsbyBFdXJvcGVvLFRlbmRpZG8sMjA2LjgxLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLENpcnVlbG8gSmFwb27DqXMsR290ZW8sMzQuNTEsMjAyNA0KMDYzMDUsTmFuY2FndWEsQ2lydWVsbyBKYXBvbsOpcyxUZW5kaWRvLDEwLjksMjAyNA0KMDYzMDUsTmFuY2FndWEsRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxHb3RlbywyMC43NTk5OTk5OTk5OTk5OTgsMjAyNA0KMDYzMDUsTmFuY2FndWEsRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxUZW5kaWRvLDI2LjEsMjAyNA0KMDYzMDUsTmFuY2FndWEsS2l3aSxHb3RlbywxMjcuNDcsMjAyNA0KMDYzMDUsTmFuY2FndWEsTWFuZGFyaW5vLEdvdGVvLDk5LjIyOTk5OTk5OTk5OTk5LDIwMjQNCjA2MzA1LE5hbmNhZ3VhLE5hcmFuam8sR290ZW8sMjguODQsMjAyNA0KMDYzMDUsTmFuY2FndWEsTmVjdGFyaW5vLEdvdGVvLDQ0LjUsMjAyNA0KMDYzMDUsTmFuY2FndWEsTmVjdGFyaW5vLFRlbmRpZG8sMS4yLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLE5vZ2FsLEdvdGVvLDYyLjI2LDIwMjQNCjA2MzA1LE5hbmNhZ3VhLFBlcmFsLEdvdGVvLDMuMCwyMDI0DQowNjMwNSxOYW5jYWd1YSxQZXJhbCxUZW5kaWRvLDIxLjQxLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLFBsdW90cyxHb3RlbywyLjMzLDIwMjQNCjA2MzA1LE5hbmNhZ3VhLFZpZCBkZSBNZXNhLEdvdGVvLDQ3OC40MSwyMDI0DQowNjMwNSxOYW5jYWd1YSxWaWQgZGUgTWVzYSxUZW5kaWRvLDEzNC4zNywyMDI0DQowNjMwNixQYWxtaWxsYSxBdmVsbGFubyxHb3RlbywxNS42NCwyMDI0DQowNjMwNixQYWxtaWxsYSxDZXJlem8sR290ZW8sMTE4OC4yOSwyMDI0DQowNjMwNixQYWxtaWxsYSxDZXJlem8sTWljcm8gYXNwZXJzacOzbiwyMy4xNiwyMDI0DQowNjMwNixQYWxtaWxsYSxDaXJ1ZWxvIEV1cm9wZW8sR290ZW8sODgzLjEsMjAyNA0KMDYzMDYsUGFsbWlsbGEsQ2lydWVsbyBFdXJvcGVvLE1pY3JvIGFzcGVyc2nDs24sMTMuMjMsMjAyNA0KMDYzMDYsUGFsbWlsbGEsQ2lydWVsbyBFdXJvcGVvLFN1cmNvLDUxLjkxLDIwMjQNCjA2MzA2LFBhbG1pbGxhLENpcnVlbG8gRXVyb3BlbyxUZW5kaWRvLDE1LjMsMjAyNA0KMDYzMDYsUGFsbWlsbGEsQ2lydWVsbyBKYXBvbsOpcyxHb3RlbywxNjYuNiwyMDI0DQowNjMwNixQYWxtaWxsYSxEdXJhem5lcm8gVGlwbyBDb25zZXJ2ZXJvLEdvdGVvLDYuMzcsMjAyNA0KMDYzMDYsUGFsbWlsbGEsS2l3aSxHb3Rlbyw3MS45MywyMDI0DQowNjMwNixQYWxtaWxsYSxLaXdpIEdvbGQgbyBLaXdpIEFtYXJpbGxvLEdvdGVvLDIuMzgsMjAyNA0KMDYzMDYsUGFsbWlsbGEsTGltb25lcm8sR290ZW8sODYuMzksMjAyNA0KMDYzMDYsUGFsbWlsbGEsTGltb25lcm8sU3VyY28sMC42OSwyMDI0DQowNjMwNixQYWxtaWxsYSxNYW5kYXJpbm8sR290ZW8sMjQ5Ljg0LDIwMjQNCjA2MzA2LFBhbG1pbGxhLE5hcmFuam8sR290ZW8sMTUxLjU0OTk5OTk5OTk5OTk4LDIwMjQNCjA2MzA2LFBhbG1pbGxhLE5hcmFuam8sU3VyY28sNy42OCwyMDI0DQowNjMwNixQYWxtaWxsYSxOZWN0YXJpbm8sR290ZW8sMTEzLjQxLDIwMjQNCjA2MzA2LFBhbG1pbGxhLE5vZ2FsLEdvdGVvLDQ5LjY2LDIwMjQNCjA2MzA2LFBhbG1pbGxhLFBhbHRvLEdvdGVvLDc5LjYyLDIwMjQNCjA2MzA2LFBhbG1pbGxhLFBhbHRvLE1pY3JvIGFzcGVyc2nDs24sNzIuMDYsMjAyNA0KMDYzMDYsUGFsbWlsbGEsUGVyYWwsR290ZW8sMi42NCwyMDI0DQowNjMwNixQYWxtaWxsYSxQZXJhbCxTdXJjbywyMy4zMiwyMDI0DQowNjMwNixQYWxtaWxsYSxQbHVvdHMsR290ZW8sMTQuNzQsMjAyNA0KMDYzMDYsUGFsbWlsbGEsVmlkIGRlIE1lc2EsR290ZW8sMjc0Ljc1LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxBbG1lbmRybyxHb3RlbywxMzIuNzQsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLEFyw6FuZGFubyBBbWVyaWNhbm8sR290ZW8sOS44OTk5OTk5OTk5OTk5OTksMjAyNA0KMDYzMDcsUGVyYWxpbGxvLEF2ZWxsYW5vLEdvdGVvLDExLjk1LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxDZXJlem8sR290ZW8sMzk3LjcyLDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxDZXJlem8sTWljcm8gYXNwZXJzacOzbiw2Mi4yOSwyMDI0DQowNjMwNyxQZXJhbGlsbG8sQ2VyZXpvLFN1cmNvLDkuNDgsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLENpcnVlbG8gRXVyb3BlbyxHb3Rlbyw5NTAuNDYsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLENpcnVlbG8gRXVyb3BlbyxTdXJjbywxMDUuMTEsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLENpcnVlbG8gSmFwb27DqXMsR290ZW8sNTMuNDU5OTk5OTk5OTk5OTk0LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxDaXJ1ZWxvIEphcG9uw6lzLFN1cmNvLDQuMzMsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLER1cmF6bmVybyBUaXBvIENvbnNlcnZlcm8sR290ZW8sNDkuNDcsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLEtpd2ksR290ZW8sMTUuNzQsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLE1hbnphbm8gUm9qbyxHb3RlbywzNy4wOCwyMDI0DQowNjMwNyxQZXJhbGlsbG8sTWFuemFubyBWZXJkZSxHb3RlbywxLjkzMDAwMDAwMDAwMDAwMDIsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLE1lbWJyaWxsbyxTdXJjbywxNC44MSwyMDI0DQowNjMwNyxQZXJhbGlsbG8sTmFyYW5qbyxHb3Rlbyw0Mi40OSwyMDI0DQowNjMwNyxQZXJhbGlsbG8sTmFyYW5qbyxTdXJjbywxLjYzLDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxOZWN0YXJpbm8sR290ZW8sNi4zMiwyMDI0DQowNjMwNyxQZXJhbGlsbG8sTmVjdGFyaW5vLFN1cmNvLDIuMCwyMDI0DQowNjMwNyxQZXJhbGlsbG8sTm9nYWwsR290ZW8sMTE5LjE0LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxPbGl2byxHb3RlbywyMC4zNCwyMDI0DQowNjMwNyxQZXJhbGlsbG8sUGVyYWwsR290ZW8sMzcuNjEsMjAyNA0KMDYzMDcsUGVyYWxpbGxvLFBlcmFsLFN1cmNvLDM2LjM4LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxQbHVvdHMsR290ZW8sMS42NywyMDI0DQowNjMwNyxQZXJhbGlsbG8sVmlkIGRlIE1lc2EsR290ZW8sMjEyLjA4LDIwMjQNCjA2MzA3LFBlcmFsaWxsbyxWaWQgZGUgTWVzYSxTdXJjbywxMC40LDIwMjQNCjA2MzA4LFBsYWNpbGxhLEFyw6FuZGFubyBBbWVyaWNhbm8sR290ZW8sMzAuMjMsMjAyNA0KMDYzMDgsUGxhY2lsbGEsQ2VyZXpvLEdvdGVvLDczOS42MywyMDI0DQowNjMwOCxQbGFjaWxsYSxDZXJlem8sU3VyY28sMTExLjk4LDIwMjQNCjA2MzA4LFBsYWNpbGxhLENpcnVlbG8gRXVyb3BlbyxHb3Rlbyw5OS41OCwyMDI0DQowNjMwOCxQbGFjaWxsYSxDaXJ1ZWxvIEV1cm9wZW8sU3VyY28sMTI0LjA4LDIwMjQNCjA2MzA4LFBsYWNpbGxhLENpcnVlbG8gSmFwb27DqXMsR290ZW8sMzMuMTgsMjAyNA0KMDYzMDgsUGxhY2lsbGEsQ2lydWVsbyBKYXBvbsOpcyxTdXJjbywxMS43NywyMDI0DQowNjMwOCxQbGFjaWxsYSxEdXJhem5lcm8gVGlwbyBDb25zZXJ2ZXJvLEdvdGVvLDAuMjYsMjAyNA0KMDYzMDgsUGxhY2lsbGEsRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxTdXJjbywxMC40OCwyMDI0DQowNjMwOCxQbGFjaWxsYSxLaXdpLEdvdGVvLDgzLjgsMjAyNA0KMDYzMDgsUGxhY2lsbGEsS2l3aSxNaWNybyBhc3BlcnNpw7NuLDAuMTMsMjAyNA0KMDYzMDgsUGxhY2lsbGEsS2l3aSxTdXJjbywxNy40MiwyMDI0DQowNjMwOCxQbGFjaWxsYSxLaXdpIEdvbGQgbyBLaXdpIEFtYXJpbGxvLEdvdGVvLDYuNjcsMjAyNA0KMDYzMDgsUGxhY2lsbGEsS2l3aSBHb2xkIG8gS2l3aSBBbWFyaWxsbyxNaWNybyBhc3BlcnNpw7NuLDIuMjksMjAyNA0KMDYzMDgsUGxhY2lsbGEsTGltb25lcm8sU3VyY28sMy4wNCwyMDI0DQowNjMwOCxQbGFjaWxsYSxNYW5kYXJpbm8sR290ZW8sNC43NiwyMDI0DQowNjMwOCxQbGFjaWxsYSxNYW56YW5vIFJvam8sR290ZW8sNDAuODM5OTk5OTk5OTk5OTk2LDIwMjQNCjA2MzA4LFBsYWNpbGxhLE1hbnphbm8gUm9qbyxNaWNybyBhc3BlcnNpw7NuLDkuMDcsMjAyNA0KMDYzMDgsUGxhY2lsbGEsTWFuemFubyBSb2pvLFN1cmNvLDE3OS4zNywyMDI0DQowNjMwOCxQbGFjaWxsYSxNYW56YW5vIFZlcmRlLEdvdGVvLDQuNzgsMjAyNA0KMDYzMDgsUGxhY2lsbGEsTWFuemFubyBWZXJkZSxNaWNybyBhc3BlcnNpw7NuLDEyLjIwOTk5OTk5OTk5OTk5OSwyMDI0DQowNjMwOCxQbGFjaWxsYSxNYW56YW5vIFZlcmRlLFN1cmNvLDMxLjU0LDIwMjQNCjA2MzA4LFBsYWNpbGxhLE5hcmFuam8sU3VyY28sNC40MSwyMDI0DQowNjMwOCxQbGFjaWxsYSxOZWN0YXJpbm8sR290ZW8sMy43OSwyMDI0DQowNjMwOCxQbGFjaWxsYSxOZWN0YXJpbm8sU3VyY28sNDMuMzIsMjAyNA0KMDYzMDgsUGxhY2lsbGEsUGFsdG8sR290ZW8sNC4zLDIwMjQNCjA2MzA4LFBsYWNpbGxhLFBlcmFsLEdvdGVvLDYwLjE2LDIwMjQNCjA2MzA4LFBsYWNpbGxhLFBlcmFsLE1pY3JvIGFzcGVyc2nDs24sMTQuMDUsMjAyNA0KMDYzMDgsUGxhY2lsbGEsUGVyYWwsU3VyY28sMTg4LjM0LDIwMjQNCjA2MzA4LFBsYWNpbGxhLFZpZCBkZSBNZXNhLEdvdGVvLDYxNS45OSwyMDI0DQowNjMwOCxQbGFjaWxsYSxWaWQgZGUgTWVzYSxTdXJjbywxMDUuMTQsMjAyNA0KMDYzMDksUHVtYW5xdWUsQXLDoW5kYW5vIEFtZXJpY2FubyxHb3Rlbyw1Mi4wMiwyMDI0DQowNjMwOSxQdW1hbnF1ZSxBdmVsbGFubyxHb3RlbywzNi43MiwyMDI0DQowNjMwOSxQdW1hbnF1ZSxDZXJlem8sR290ZW8sNTMuMDQsMjAyNA0KMDYzMDksUHVtYW5xdWUsQ2lydWVsbyBFdXJvcGVvLEdvdGVvLDEyMi40LDIwMjQNCjA2MzA5LFB1bWFucXVlLER1cmF6bmVybyBUaXBvIENvbnNlcnZlcm8sR290ZW8sMTMuNSwyMDI0DQowNjMwOSxQdW1hbnF1ZSxMaW1vbmVybyxHb3RlbywwLjIsMjAyNA0KMDYzMDksUHVtYW5xdWUsTWFuZGFyaW5vLEdvdGVvLDkwLjMsMjAyNA0KMDYzMDksUHVtYW5xdWUsTmVjdGFyaW5vLEdvdGVvLDMyLjksMjAyNA0KMDYzMDksUHVtYW5xdWUsT2xpdm8sR290ZW8sMTg5Ljc4LDIwMjQNCjA2MzA5LFB1bWFucXVlLFBhbHRvLEdvdGVvLDAuNSwyMDI0DQowNjMwOSxQdW1hbnF1ZSxQaXN0YWNobyxHb3Rlbyw3LjAsMjAyNA0KMDYzMDksUHVtYW5xdWUsVmlkIGRlIE1lc2EsR290ZW8sMTMxLjksMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixBbG1lbmRybyxHb3RlbywxOS4xOCwyMDI0DQowNjMxMCxTYW50YSBDcnV6LEFyw6FuZGFubyBBbWVyaWNhbm8sR290ZW8sNjYuNCwyMDI0DQowNjMxMCxTYW50YSBDcnV6LENlcmV6byxHb3Rlbyw4ODcuMDUsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixDZXJlem8sVGVuZGlkbywzLjAsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixDaXJ1ZWxvIEV1cm9wZW8sR290ZW8sOTM4LjkzLDIwMjQNCjA2MzEwLFNhbnRhIENydXosQ2lydWVsbyBFdXJvcGVvLFN1cmNvLDEwLjE5LDIwMjQNCjA2MzEwLFNhbnRhIENydXosQ2lydWVsbyBFdXJvcGVvLFRlbmRpZG8sMjE3LjIyLDIwMjQNCjA2MzEwLFNhbnRhIENydXosQ2lydWVsbyBKYXBvbsOpcyxHb3Rlbyw4MC44MiwyMDI0DQowNjMxMCxTYW50YSBDcnV6LERhbWFzY28sR290ZW8sNS42LDIwMjQNCjA2MzEwLFNhbnRhIENydXosRHVyYXpuZXJvIENvbnN1bW8gRnJlc2NvLEdvdGVvLDIxLjM5LDIwMjQNCjA2MzEwLFNhbnRhIENydXosRHVyYXpuZXJvIFRpcG8gQ29uc2VydmVybyxHb3Rlbyw1MS42OCwyMDI0DQowNjMxMCxTYW50YSBDcnV6LEtpd2ksR290ZW8sMTguNjEsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixMaW1vbmVybyxHb3RlbywyMS4yNzk5OTk5OTk5OTk5OTgsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixMaW1vbmVybyxTdXJjbywxLjEzLDIwMjQNCjA2MzEwLFNhbnRhIENydXosTWFuZGFyaW5vLEdvdGVvLDExNC42MSwyMDI0DQowNjMxMCxTYW50YSBDcnV6LE1hbnphbm8gUm9qbyxHb3RlbywxMS4wLDIwMjQNCjA2MzEwLFNhbnRhIENydXosTWFuemFubyBWZXJkZSxHb3Rlbyw2LjMsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixNYW56YW5vIFZlcmRlLFRlbmRpZG8sMi41NiwyMDI0DQowNjMxMCxTYW50YSBDcnV6LE5hcmFuam8sR290ZW8sMzguMDMsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixOZWN0YXJpbm8sR290ZW8sNzIuMTQsMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixOb2dhbCxHb3RlbywxMzguNTksMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixPbGl2byxHb3RlbywxLjU4LDIwMjQNCjA2MzEwLFNhbnRhIENydXosT2xpdm8sU3VyY28sMC44MjAwMDAwMDAwMDAwMDAxLDIwMjQNCjA2MzEwLFNhbnRhIENydXosUGFsdG8sR290ZW8sMjIyLjMxLDIwMjQNCjA2MzEwLFNhbnRhIENydXosUGVyYWwsR290ZW8sNjcuNjc5OTk5OTk5OTk5OTksMjAyNA0KMDYzMTAsU2FudGEgQ3J1eixQZXJhbCxUZW5kaWRvLDUyLjQ5LDIwMjQNCjA2MzEwLFNhbnRhIENydXosUGlzdGFjaG8sR290ZW8sMTMuOSwyMDI0DQowNjMxMCxTYW50YSBDcnV6LFBsdW90cyxHb3Rlbyw0LjQyLDIwMjQNCjA2MzEwLFNhbnRhIENydXosVmlkIGRlIE1lc2EsR290ZW8sMTgwLjAzLDIwMjQNCjA2MzEwLFNhbnRhIENydXosVmlkIGRlIE1lc2EsU3VyY28sMy4wMiwyMDI0DQo=", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactCultivo.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"CUT", type text}, {"Comuna", type text}, {"Especie", type text}, {"Riego", type text}, {"Hectareas", type number}, {"Anio", Int64.Type}}, "en-US")
in Tipos