let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RmVjaGEsQW5pbyxDVVQsQ29tdW5hLEVzdGFjaW9uLENvZGlnb19ETUMsTGx1dmlhX21tLE1heDI0aF9tbSxQYWdpbmFfUERGLEZ1ZW50ZSxFc3RhZG8NCjIwMTctMDYtMDEsMjAxNywwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCwxOTIuNCw0Mi45LDg3LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMTcucGRmLE9ic2VydmFkbw0KMjAxNy0wNy0wMSwyMDE3LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDgxLjksMjguMiw4NyxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE3LnBkZixPYnNlcnZhZG8NCjIwMTctMDgtMDEsMjAxNywwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCwxMTUuNywzMi4xLDg3LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMTcucGRmLE9ic2VydmFkbw0KMjAxNy0wNi0wMSwyMDE3LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwxNTIuMCwzNi41LDg3LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMTcucGRmLE9ic2VydmFkbw0KMjAxNy0wNy0wMSwyMDE3LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCw3MS41LDIxLjUsODcsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxNy5wZGYsT2JzZXJ2YWRvDQoyMDE3LTA4LTAxLDIwMTcsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDExNC4wLDI5LjAsODcsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxNy5wZGYsT2JzZXJ2YWRvDQoyMDE4LTA2LTAxLDIwMTgsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsOTcuOSwzMy4yLDgxLGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMTgucGRmLE9ic2VydmFkbw0KMjAxOC0wNy0wMSwyMDE4LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDg4LjYsNjEuMyw4MSxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE4LnBkZixPYnNlcnZhZG8NCjIwMTgtMDgtMDEsMjAxOCwwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCw0Ni4yLDE4LjIsODEsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxOC5wZGYsT2JzZXJ2YWRvDQoyMDE4LTA2LTAxLDIwMTgsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDEwMy41LDQyLjAsODEsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxOC5wZGYsT2JzZXJ2YWRvDQoyMDE4LTA3LTAxLDIwMTgsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDcxLjUsNDcuMCw4MSxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE4LnBkZixPYnNlcnZhZG8NCjIwMTgtMDgtMDEsMjAxOCwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsNDcuNSwxNy4wLDgxLGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMTgucGRmLE9ic2VydmFkbw0KMjAxOS0wNi0wMSwyMDE5LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDc2LjcsNDkuOCwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxOS5wZGYsT2JzZXJ2YWRvDQoyMDE5LTA3LTAxLDIwMTksMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsMjIuMiwxMy42LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE5LnBkZixPYnNlcnZhZG8NCjIwMTktMDgtMDEsMjAxOSwwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCwzLjUsMi40LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE5LnBkZixPYnNlcnZhZG8NCjIwMTktMDYtMDEsMjAxOSwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsNzYuNSwyOS4wLDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE5LnBkZixPYnNlcnZhZG8NCjIwMTktMDctMDEsMjAxOSwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsMjUuNSwxNy41LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDE5LnBkZixPYnNlcnZhZG8NCjIwMTktMDgtMDEsMjAxOSwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsMi41LDIuNSwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAxOS5wZGYsT2JzZXJ2YWRvDQoyMDIwLTA2LTAxLDIwMjAsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsMjg3LjUsNTQuMSwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMC5wZGYsT2JzZXJ2YWRvDQoyMDIwLTA3LTAxLDIwMjAsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsOTUuMSwzOC41LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDIwLnBkZixPYnNlcnZhZG8NCjIwMjAtMDgtMDEsMjAyMCwwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCwyNi44LDE4LjksMTA4LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjAucGRmLE9ic2VydmFkbw0KMjAyMC0wNi0wMSwyMDIwLDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwyODEuNSw1NC41LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDIwLnBkZixPYnNlcnZhZG8NCjIwMjAtMDctMDEsMjAyMCwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsMTA0LjUsMzcuMCwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMC5wZGYsT2JzZXJ2YWRvDQoyMDIwLTA4LTAxLDIwMjAsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDkuNSw4LjUsMTA4LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjAucGRmLE9ic2VydmFkbw0KMjAyMS0wNi0wMSwyMDIxLDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDU2LjIsMjIuNiwxMDksaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMS5wZGYsT2JzZXJ2YWRvDQoyMDIxLTA3LTAxLDIwMjEsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsMTAuNSw5LjQsMTA5LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjEucGRmLE9ic2VydmFkbw0KMjAyMS0wOC0wMSwyMDIxLDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDE1OC4wLDYwLjksMTA5LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjEucGRmLE9ic2VydmFkbw0KMjAyMS0wNi0wMSwyMDIxLDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCw1MC41LDEzLjAsMTA5LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjEucGRmLE9ic2VydmFkbw0KMjAyMS0wNy0wMSwyMDIxLDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwxNC4wLDE0LjAsMTA5LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjEucGRmLE9ic2VydmFkbw0KMjAyMS0wOC0wMSwyMDIxLDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwxODIuNSw2OC41LDEwOSxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDIxLnBkZixPYnNlcnZhZG8NCjIwMjItMDYtMDEsMjAyMiwwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCw0Ny43LDIwLjIsMTA4LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjIucGRmLE9ic2VydmFkbw0KMjAyMi0wNy0wMSwyMDIyLDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDEwOC4yLDI3LjMsMTA4LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjIucGRmLE9ic2VydmFkbw0KMjAyMi0wOC0wMSwyMDIyLDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDYxLjksMzQuNiwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMi5wZGYsT2JzZXJ2YWRvDQoyMDIyLTA2LTAxLDIwMjIsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDYxLjUsMjguMCwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMi5wZGYsT2JzZXJ2YWRvDQoyMDIyLTA3LTAxLDIwMjIsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDk3LjUsMzQuMCwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMi5wZGYsT2JzZXJ2YWRvDQoyMDIyLTA4LTAxLDIwMjIsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDY4LjAsMzIuNSwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMi5wZGYsT2JzZXJ2YWRvDQoyMDIzLTA2LTAxLDIwMjMsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsMTI4LjcsMjMuNiwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMy5wZGYsT2JzZXJ2YWRvDQoyMDIzLTA3LTAxLDIwMjMsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsODguNSw1Ny40LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDIzLnBkZixPYnNlcnZhZG8NCjIwMjMtMDgtMDEsMjAyMywwNjMwMyxDaGltYmFyb25nbyxTYW4gQmVuaXRvIGRlIENoaW1iYXJvbmdvLDM0MDA0NCwyNTEuMSw2OS43LDEwOCxodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDIzLnBkZixPYnNlcnZhZG8NCjIwMjMtMDYtMDEsMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsMTUzLjUsNDkuMCwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMy5wZGYsT2JzZXJ2YWRvDQoyMDIzLTA3LTAxLDIwMjMsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDg1LjAsNDMuNSwxMDgsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyMy5wZGYsT2JzZXJ2YWRvDQoyMDIzLTA4LTAxLDIwMjMsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LCwsMTA4LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjMucGRmLEZhbHRhbnRlIGVuIGZ1ZW50ZQ0KMjAyNC0wNi0wMSwyMDI0LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDM0My4yLDgyLjUsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjQucGRmLE9ic2VydmFkbw0KMjAyNC0wNy0wMSwyMDI0LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDAuMCwwLjAsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjQucGRmLE9ic2VydmFkbw0KMjAyNC0wOC0wMSwyMDI0LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDEyMy4yLDUzLjIsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjQucGRmLE9ic2VydmFkbw0KMjAyNC0wNi0wMSwyMDI0LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwzNDQuMCw3MS41LDI1NixodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDI0LnBkZixPYnNlcnZhZG8NCjIwMjQtMDctMDEsMjAyNCwwNjMwMSxTYW4gRmVybmFuZG8sU2FuIEZlcm5hbmRvIEV4LVNlbmRvcywzNDAwMzgsMy41LDMuNSwyNTYsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyNC5wZGYsT2JzZXJ2YWRvDQoyMDI0LTA4LTAxLDIwMjQsMDYzMDEsU2FuIEZlcm5hbmRvLFNhbiBGZXJuYW5kbyBFeC1TZW5kb3MsMzQwMDM4LDExMi41LDU5LjUsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjQucGRmLE9ic2VydmFkbw0KMjAyNS0wNi0wMSwyMDI1LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDk5LjQsNDMuNiwyNTYsaHR0cHM6Ly9jbGltYXRvbG9naWEubWV0ZW9jaGlsZS5nb2IuY2wvcHVibGljYWNpb25lcy9hbnVhcmlvL2FudWFyaW8tMjAyNS5wZGYsT2JzZXJ2YWRvDQoyMDI1LTA3LTAxLDIwMjUsMDYzMDMsQ2hpbWJhcm9uZ28sU2FuIEJlbml0byBkZSBDaGltYmFyb25nbywzNDAwNDQsMTEuMyw2LjEsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjUucGRmLE9ic2VydmFkbw0KMjAyNS0wOC0wMSwyMDI1LDA2MzAzLENoaW1iYXJvbmdvLFNhbiBCZW5pdG8gZGUgQ2hpbWJhcm9uZ28sMzQwMDQ0LDExOC4wLDczLjQsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjUucGRmLE9ic2VydmFkbw0KMjAyNS0wNi0wMSwyMDI1LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCw5Mi41LDMyLjUsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjUucGRmLE9ic2VydmFkbw0KMjAyNS0wNy0wMSwyMDI1LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCw0OC41LDM1LjUsMjU2LGh0dHBzOi8vY2xpbWF0b2xvZ2lhLm1ldGVvY2hpbGUuZ29iLmNsL3B1YmxpY2FjaW9uZXMvYW51YXJpby9hbnVhcmlvLTIwMjUucGRmLE9ic2VydmFkbw0KMjAyNS0wOC0wMSwyMDI1LDA2MzAxLFNhbiBGZXJuYW5kbyxTYW4gRmVybmFuZG8gRXgtU2VuZG9zLDM0MDAzOCwxMDIuMCw0OC41LDI1NixodHRwczovL2NsaW1hdG9sb2dpYS5tZXRlb2NoaWxlLmdvYi5jbC9wdWJsaWNhY2lvbmVzL2FudWFyaW8vYW51YXJpby0yMDI1LnBkZixPYnNlcnZhZG8NCg==", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactClima.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type datetime}, {"Anio", Int64.Type}, {"CUT", type text}, {"Comuna", type text}, {"Estacion", type text}, {"Codigo_DMC", Int64.Type}, {"Lluvia_mm", type number}, {"Max24h_mm", type number}, {"Pagina_PDF", Int64.Type}, {"Fuente", type text}, {"Estado", type text}}, "en-US")
in Tipos