let
    Binario = if RutaDatos = "" then Binary.FromText("77u/Q29tdW5hLEhhX2ZydXRhbGVzLEhISV9jdWx0aXZvcyxDdW90YV9jZXJlem8sQ3VvdGFfcmllZ29fZ3JhdmVkYWQsRW1wcmVzYXNfdG90YWwsRW1wcmVzYXNfYWdybyxFbXByZXNhc19yZWRfcG90ZW5jaWFsLFBZTUVfdG90YWxfY29tdW5hLE1pY3JvX3RvdGFsX2NvbXVuYSxEZXBlbmRlbmNpYV9hZ3JvLENVVCxJbmRpY2VfcHJpb3JpZGFkLFB1ZXN0byxNZWpvcl9wdWVzdG8sUGVvcl9wdWVzdG8sVG9wM19lc2NlbmFyaW9zLENsdXN0ZXIsQWNjaW9uDQpDaGltYmFyb25nbyw4NDU0LjkyLDAuMzc1MjkyNDk4NjQ0MTk4NTYsMC41ODkzMjA3NzQxNzY0NTU4LDAuMTYxMjUwNDkwODM4NDcwMzcsMzQyNywxMzE5LDQzMiw2MTIuMCwyMDE3LjAsMC4zODQ4ODQ3Mzg4Mzg2MzQ0LDA2MzAzLDg2LjUzNTIzOTAwODY4MzgzLDEsMSwyLDUsMixEaWFnbsOzc3RpY28gZGUgcmllZ28geSBjb250aW51aWRhZCBkZSBwcm92ZWVkb3Jlcw0KUGxhY2lsbGEsMjU5Ni42MSwwLjIxMjgwODk5MzIyNjM4NTEzLDAuMzI3OTY5OTMwMDI0MTQ2ODcsMC4zMTk5OTAyOTUwMzg1MzEsOTMzLDM4OCwxNDYsMTc4LjAsNTQ4LjAsMC40MTU4NjI4MDgxNDU3NjYzNywwNjMwOCw3MS40NTg3MTkzNDc5OTI5MSwyLDEsMyw1LDEsRGlhZ27Ds3N0aWNvIGRlIHJpZWdvIHkgY29udGludWlkYWQgZGUgcHJvdmVlZG9yZXMNClBhbG1pbGxhLDM1NjQuMjYsMC4yMDc3NTUxOTE3NDI2ODUzLDAuMzM5ODg4MjIzNjQyNDk1MiwwLjAyNzc0NzY5NTE3Mzc1Mjc1OCwxNDYxLDYwOSwyMTUsMjI2LjAsOTA5LjAsMC40MTY4Mzc3ODIzNDA4NjI0NCwwNjMwNiw1My4xNTc5MTA1NjkwMjA2NywzLDMsNiwyLDEsRGl2ZXJzaWZpY2FjacOzbiBjb21lcmNpYWwgeSBjb250aW51aWRhZCBkZSBwcm92ZWVkb3Jlcw0KQ2jDqXBpY2EsMjM3NC4yLDAuMjEwNjYxMjkxMzQzNDAyMzYsMC4zMTEzNDI3NjgwOTAzMDQxNSwwLjA3Nzg3MDQ0MDU2OTQ1NDk4LDE2NzUsNjYwLDI0NSwyNTUuMCwxMDkxLjAsMC4zOTQwMjk4NTA3NDYyNjg3LDA2MzAyLDUzLjA0MTkxMzg1OTc3Mzc2LDQsNCw1LDAsMSxEaXZlcnNpZmljYWNpw7NuIGNvbWVyY2lhbCB5IGNvbnRpbnVpZGFkIGRlIHByb3ZlZWRvcmVzDQpTYW4gRmVybmFuZG8sNTYwMi4xNiwwLjM1NjkyMTQ2MTk5NDIxNzU0LDAuNTc1OTM2NzgxNTI3MTI1MiwwLjEwNzA0NjIxMDc0NzI4MzIsNjg4Nyw2OTcsNjk1LDEzMTEuMCw0MDg3LjAsMC4xMDEyMDUxNjkxNTkyODU2MSwwNjMwMSw0OS4wNzM0NzI3ODYxNTIzMTUsNSwyLDksMiwyLERpYWduw7NzdGljbyBkZSByaWVnbyB5IGNvbnRpbnVpZGFkIGRlIHByb3ZlZWRvcmVzDQpQZXJhbGlsbG8sMjM0Ni41MywwLjI2MDAyMzI1MTIwNjg3NSwwLjIwMDA3ODQxMzY1NzYxMzU2LDAuMDc4NDczMzIwMTc5MTU4MTUsMTI4OCwzNzcsMTg4LDIwMy4wLDgyOS4wLDAuMjkyNzAxODYzMzU0MDM3MjUsMDYzMDcsNDMuNDMyNDQ2NTIxMzkyODgsNiw1LDcsMCwxLERpdmVyc2lmaWNhY2nDs24gY29tZXJjaWFsIHkgY29udGludWlkYWQgZGUgcHJvdmVlZG9yZXMNCk5hbmNhZ3VhLDIwNjUuNzMsMC4yMDYyOTExMTIzMzQxMDI5NywwLjIwNjAzODU0MzI3NTI1ODYsMC4yMDQ0MzYyMDQxNTA1OTA4MywxNjY3LDM4MiwyMTYsMjYwLjAsMTA1My4wLDAuMjI5MTU0MTY5MTY2MTY2NzcsMDYzMDUsMzguMjcxNjUxODU1NzE3MTMsNywzLDcsMSwxLERpYWduw7NzdGljbyBkZSByaWVnbyB5IGNvbnRpbnVpZGFkIGRlIHByb3ZlZWRvcmVzDQpMb2xvbCwyODc2LjQsMC4yNDA4NjQyMDc0OTAxNjA0NCwwLjA0ODM1NTU4MzM2ODA5OTAxLDAuMDAwNDk3MTQ5MjE0Mjk1NjQ3Myw5MzUsMzAwLDExMCwyMDAuMCw1NTMuMCwwLjMyMDg1NTYxNDk3MzI2MjA0LDA2MzA0LDMzLjg1ODA0MTcwODg4Mzc5LDgsNiw5LDAsMSxEaXZlcnNpZmljYWNpw7NuIGNvbWVyY2lhbCB5IGNvbnRpbnVpZGFkIGRlIHByb3ZlZWRvcmVzDQpTYW50YSBDcnV6LDMyNzEuOTYsMC4yMTUyNzE0MTA5MTM3NTQ5NiwwLjI3MjAyMzQ5NjYxOTc2MzA1LDAuMDg4NzYzMzEwMDY0OTE1MjIsNDg1Myw3ODIsNTUyLDkxMC4wLDI5MzguMCwwLjE2MTEzNzQ0MDc1ODI5Mzg0LDA2MzEwLDI2Ljk3NjU3ODEyNDcxNDYsOSw4LDEwLDAsMSxEaWFnbsOzc3RpY28gZGUgcmllZ28geSBjb250aW51aWRhZCBkZSBwcm92ZWVkb3Jlcw0KUHVtYW5xdWUsNzMwLjI2LDAuMTU4ODg3NjIzMDM5MDE0OTYsMC4wNzI2MzE2NjU0MzQyMjg5LDAuMCw0NzcsMTQ2LDMzLDc0LjAsMjY0LjAsMC4zMDYwNzk2NjQ1NzAyMzA2LDA2MzA5LDIzLjYxNTcxNzg5MTQ1NzQ0NywxMCw4LDEwLDAsMSxEaXZlcnNpZmljYWNpw7NuIGNvbWVyY2lhbCB5IGNvbnRpbnVpZGFkIGRlIHByb3ZlZWRvcmVzDQo=", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\FactPrioridad.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Comuna", type text}, {"Ha_frutales", type number}, {"HHI_cultivos", type number}, {"Cuota_cerezo", type number}, {"Cuota_riego_gravedad", type number}, {"Empresas_total", Int64.Type}, {"Empresas_agro", Int64.Type}, {"Empresas_red_potencial", Int64.Type}, {"PYME_total_comuna", type number}, {"Micro_total_comuna", type number}, {"Dependencia_agro", type number}, {"CUT", type text}, {"Indice_prioridad", type number}, {"Puesto", Int64.Type}, {"Mejor_puesto", Int64.Type}, {"Peor_puesto", Int64.Type}, {"Top3_escenarios", Int64.Type}, {"Cluster", Int64.Type}, {"Accion", type text}}, "en-US")
in Tipos