let
    Binario = if RutaDatos = "" then Binary.FromText("77u/QW5pbyxDVVQsQ29tdW5hLExsdXZpYV9KSkEsTWF4MjRoX0pKQSxNZXNlc192YWxpZG9zLFJlZmVyZW5jaWFfMjAxN18yMDIyLEFub21hbGlhX2xsdXZpYSxUZW1wb3JhZGEsRW1wbGVvX3ZlcmFub19PSGlnZ2lucyxDYW1iaW9fZW1wbGVvX2ludGVyYW51YWwNCjIwMTcsMDYzMDEsU2FuIEZlcm5hbmRvLDMzNy41LDM2LjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsMC4zMjAwNzgyMjY4NTc4ODc5LDIwMTctMjAxOCwxMDE0NTEuOTAxMzQwMDY1NjgsMC4wMDI0OTgyOTY1Mjc3MzgyNTMNCjIwMTcsMDYzMDMsQ2hpbWJhcm9uZ28sMzkwLjAsNDIuOSwzLDI2Mi44MzMzMzMzMzMzMzMzLDAuNDgzODMwMDU3MDcwMzg2ODQsMjAxNy0yMDE4LDEwMTQ1MS45MDEzNDAwNjU2OCwwLjAwMjQ5ODI5NjUyNzczODI1Mw0KMjAxOCwwNjMwMSxTYW4gRmVybmFuZG8sMjIyLjUsNDcuMCwzLDI1NS42NjY2NjY2NjY2NjY2NiwtMC4xMjk3MjYyMDU5OTczOTIzNywyMDE4LTIwMTksMTA1NjQxLjY0Mzk1MjI1Njk0LDAuMDQxMjk3ODIyNDgzODUxNjENCjIwMTgsMDYzMDMsQ2hpbWJhcm9uZ28sMjMyLjcsNjEuMywzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjExNDY0ODA2NTk0ODAwMjQ4LDIwMTgtMjAxOSwxMDU2NDEuNjQzOTUyMjU2OTQsMC4wNDEyOTc4MjI0ODM4NTE2MQ0KMjAxOSwwNjMwMSxTYW4gRmVybmFuZG8sMTA0LjUsMjkuMCwzLDI1NS42NjY2NjY2NjY2NjY2NiwtMC41OTEyNjQ2Njc1MzU4NTM5LDIwMTktMjAyMCw5NTE0NS45NTE3MDAwOTkxMiwtMC4wOTkzNTE4NDUxNTc3Nzg3Mw0KMjAxOSwwNjMwMyxDaGltYmFyb25nbywxMDIuNCw0OS44LDMsMjYyLjgzMzMzMzMzMzMzMzMsLTAuNjEwMzk5NDkyNzA3NjcyOCwyMDE5LTIwMjAsOTUxNDUuOTUxNzAwMDk5MTIsLTAuMDk5MzUxODQ1MTU3Nzc4NzMNCjIwMjAsMDYzMDEsU2FuIEZlcm5hbmRvLDM5NS41LDU0LjUsMywyNTUuNjY2NjY2NjY2NjY2NjYsMC41NDY5MzYxMTQ3MzI3MjUsMjAyMC0yMDIxLDkwNzI2LjQ3ODA1NDMyNDYzLC0wLjA0NjQ0OTQxMzQyMDE4MTE2DQoyMDIwLDA2MzAzLENoaW1iYXJvbmdvLDQwOS40MDAwMDAwMDAwMDAwMyw1NC4xLDMsMjYyLjgzMzMzMzMzMzMzMzMsMC41NTc2NDEwOTA2Nzg1MDM2LDIwMjAtMjAyMSw5MDcyNi40NzgwNTQzMjQ2MywtMC4wNDY0NDk0MTM0MjAxODExNg0KMjAyMSwwNjMwMSxTYW4gRmVybmFuZG8sMjQ3LjAsNjguNSwzLDI1NS42NjY2NjY2NjY2NjY2NiwtMC4wMzM4OTgzMDUwODQ3NDU2NywyMDIxLTIwMjIsODYyMTguNDExMTIwNzcxMTQsLTAuMDQ5Njg4NTQ3NzEyMTA0MjkNCjIwMjEsMDYzMDMsQ2hpbWJhcm9uZ28sMjI0LjcsNjAuOSwzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjE0NTA4NTYwNTU4MDIxNTU1LDIwMjEtMjAyMiw4NjIxOC40MTExMjA3NzExNCwtMC4wNDk2ODg1NDc3MTIxMDQyOQ0KMjAyMiwwNjMwMSxTYW4gRmVybmFuZG8sMjI3LjAsMzQuMCwzLDI1NS42NjY2NjY2NjY2NjY2NiwtMC4xMTIxMjUxNjI5NzI2MjA1NCwyMDIyLTIwMjMsODkwMzguNzE1NTA0MzA4NjUsMC4wMzI3MTExNjE2NTE4NTM2MTUNCjIwMjIsMDYzMDMsQ2hpbWJhcm9uZ28sMjE3LjgsMzQuNiwzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjE3MTMzNzk4MzUxMjk5OTIzLDIwMjItMjAyMyw4OTAzOC43MTU1MDQzMDg2NSwwLjAzMjcxMTE2MTY1MTg1MzYxNQ0KMjAyMywwNjMwMSxTYW4gRmVybmFuZG8sLCwyLDI1NS42NjY2NjY2NjY2NjY2NiwsMjAyMy0yMDI0LDgwNzYwLjA0NzkwNTEyNzk3LC0wLjA5Mjk3ODI5MDk4NjAxNTczDQoyMDIzLDA2MzAzLENoaW1iYXJvbmdvLDQ2OC4yOTk5OTk5OTk5OTk5NSw2OS43LDMsMjYyLjgzMzMzMzMzMzMzMzMsMC43ODE3Mzc0NzYyMjA2NzIxLDIwMjMtMjAyNCw4MDc2MC4wNDc5MDUxMjc5NywtMC4wOTI5NzgyOTA5ODYwMTU3Mw0KMjAyNCwwNjMwMSxTYW4gRmVybmFuZG8sNDYwLjAsNzEuNSwzLDI1NS42NjY2NjY2NjY2NjY2NiwwLjc5OTIxNzczMTQyMTEyMTMsMjAyNC0yMDI1LDgyNzI4Ljc1MzI1MTMzMzYyLDAuMDI0Mzc3MjE4NjUyOTQ1Mzk4DQoyMDI0LDA2MzAzLENoaW1iYXJvbmdvLDQ2Ni40LDgyLjUsMywyNjIuODMzMzMzMzMzMzMzMywwLjc3NDUwODU2MDU1ODAyMTUsMjAyNC0yMDI1LDgyNzI4Ljc1MzI1MTMzMzYyLDAuMDI0Mzc3MjE4NjUyOTQ1Mzk4DQoyMDI1LDA2MzAxLFNhbiBGZXJuYW5kbywyNDMuMCw0OC41LDMsMjU1LjY2NjY2NjY2NjY2NjY2LC0wLjA0OTU0MzY3NjY2MjMyMDczNSwyMDI1LTIwMjYsODAxMjkuNjcyNTIxNDY2ODUsLTAuMDMxNDE2ODk3MTIxMjU0MDYNCjIwMjUsMDYzMDMsQ2hpbWJhcm9uZ28sMjI4LjcsNzMuNCwzLDI2Mi44MzMzMzMzMzMzMzMzLC0wLjEyOTg2NjgzNTc2NDEwOTA3LDIwMjUtMjAyNiw4MDEyOS42NzI1MjE0NjY4NSwtMC4wMzE0MTY4OTcxMjEyNTQwNg0K", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\ParesClimaEmpleo.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Anio", Int64.Type}, {"CUT", type text}, {"Comuna", type text}, {"Lluvia_JJA", type number}, {"Max24h_JJA", type number}, {"Meses_validos", Int64.Type}, {"Referencia_2017_2022", type number}, {"Anomalia_lluvia", type number}, {"Temporada", type text}, {"Empleo_verano_OHiggins", type number}, {"Cambio_empleo_interanual", type number}}, "en-US")
in Tipos