let
    Binario = if RutaDatos = "" then Binary.FromText("77u/Q29tdW5hLEVzY2VuYXJpbyxJbmRpY2UsUHVlc3RvDQpDaGltYmFyb25nbyxCYXNlLDg2LjUzNTIzOTAwODY4MzgzLDENCkNow6lwaWNhLEJhc2UsNTMuMDQxOTEzODU5NzczNzYsNA0KTG9sb2wsQmFzZSwzMy44NTgwNDE3MDg4ODM3OSw4DQpOYW5jYWd1YSxCYXNlLDM4LjI3MTY1MTg1NTcxNzEzLDcNClBhbG1pbGxhLEJhc2UsNTMuMTU3OTEwNTY5MDIwNjcsMw0KUGVyYWxpbGxvLEJhc2UsNDMuNDMyNDQ2NTIxMzkyODgsNg0KUGxhY2lsbGEsQmFzZSw3MS40NTg3MTkzNDc5OTI5MSwyDQpQdW1hbnF1ZSxCYXNlLDIzLjYxNTcxNzg5MTQ1NzQ0NywxMA0KU2FuIEZlcm5hbmRvLEJhc2UsNDkuMDczNDcyNzg2MTUyMzE1LDUNClNhbnRhIENydXosQmFzZSwyNi45NzY1NzgxMjQ3MTQ2LDkNCkNoaW1iYXJvbmdvLElndWFsZXMsODUuMDY3MjAzNTc5NjA5NTcsMQ0KQ2jDqXBpY2EsSWd1YWxlcyw0Ny40MTIwMDgzNzc1NTcxOCw0DQpMb2xvbCxJZ3VhbGVzLDI2LjkwNjc1NTcxNDUwNjEyNiw5DQpOYW5jYWd1YSxJZ3VhbGVzLDM4Ljg2OTc1NDkyNjIxMTksNw0KUGFsbWlsbGEsSWd1YWxlcyw0Ni4yODYwNDE1MjM1Mjc2Myw1DQpQZXJhbGlsbG8sSWd1YWxlcywzOS45OTM4ODgxODgzMzE1Nyw2DQpQbGFjaWxsYSxJZ3VhbGVzLDY5LjA3NDAxMTI2Njc0Mjg5LDINClB1bWFucXVlLElndWFsZXMsMTcuMzQ5MTc4ODI0MjI0MDc2LDEwDQpTYW4gRmVybmFuZG8sSWd1YWxlcyw1NS42MjI0MTU4MDc5NjMxLDMNClNhbnRhIENydXosSWd1YWxlcywyOC41MzIwNTI1Nzc5MjY4Niw4DQpDaGltYmFyb25nbyxBZ3JvLDg2Ljk5MDkyNTIwMTA4ODg3LDENCkNow6lwaWNhLEFncm8sNjUuNTU2NzY0NjA0MDgzNjgsNA0KTG9sb2wsQWdybyw0My45ODAyNzAxNzQ0ODI4NzUsNg0KTmFuY2FndWEsQWdybywzOS41MzY3ODA2NDg2NzQzNSw3DQpQYWxtaWxsYSxBZ3JvLDY3Ljc3MTYyNDkxNDExNjU5LDMNClBlcmFsaWxsbyxBZ3JvLDQ4LjI2NDYzNTUxNTEyNDIzLDUNClBsYWNpbGxhLEFncm8sODEuMzIwODQ4NjU0Mjc2MDgsMg0KUHVtYW5xdWUsQWdybywzNi4zNzMxNzM1MTM0MDk2MSw4DQpTYW4gRmVybmFuZG8sQWdybywzMy4zNzM0NDk0ODQ3Nzc4Niw5DQpTYW50YSBDcnV6LEFncm8sMjQuNzE0NDI1MzM4MDMwMjAzLDEwDQpDaGltYmFyb25nbyxBZ3VhLDczLjE3MTQ1NDg2OTIyNjc5LDINCkNow6lwaWNhLEFndWEsNDEuNjAzMjM3NzI0ODcwNTMsNQ0KTG9sb2wsQWd1YSwxOS42Nzc5NTc4NjYzOTYwMTQsOQ0KTmFuY2FndWEsQWd1YSw0Ny43MDk2MDY5MDc0MzAwMywzDQpQYWxtaWxsYSxBZ3VhLDM1LjgwNjYyMTExOTEyNDYzLDYNClBlcmFsaWxsbyxBZ3VhLDM1LjYxMzE1MDQ0NjYwNjQyNiw3DQpQbGFjaWxsYSxBZ3VhLDgxLjQyODk2MTk5NjgyNDUzLDENClB1bWFucXVlLEFndWEsMTMuNjU0OTY1NTcxODkzODQzLDEwDQpTYW4gRmVybmFuZG8sQWd1YSw0NS4wODE5ODM4ODE3NDY4OSw0DQpTYW50YSBDcnV6LEFndWEsMjcuNzc3NDEyMjU2OTg0OTYzLDgNCkNoaW1iYXJvbmdvLE1lcmNhZG8sOTAuNTM0MTQ3NTI5NDMxMTIsMQ0KQ2jDqXBpY2EsTWVyY2Fkbyw1MC4xMDA5NTMxMDc3ODA3Myw1DQpMb2xvbCxNZXJjYWRvLDE5LjYyMzU4MDUyMTkyNjA3Niw5DQpOYW5jYWd1YSxNZXJjYWRvLDM1LjU1MDY3NTg4MzM4MjA1Niw3DQpQYWxtaWxsYSxNZXJjYWRvLDUxLjYzMzU0NTM5MDY1NzIzLDQNClBlcmFsaWxsbyxNZXJjYWRvLDM2Ljg0NjIxMjI1MjIxMjg1LDYNClBsYWNpbGxhLE1lcmNhZG8sNjQuNTE5Nzc4NzQyOTc3NTIsMw0KUHVtYW5xdWUsTWVyY2FkbywxNS4yMjU2MDc5ODQyOTE3NzUsMTANClNhbiBGZXJuYW5kbyxNZXJjYWRvLDY3LjUwNzUxNjI0MDQ4NDI5LDINClNhbnRhIENydXosTWVyY2FkbywzMi41Mzk3NTk1OTE1NjEyNCw4DQo=", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\Sensibilidad.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Comuna", type text}, {"Escenario", type text}, {"Indice", type number}, {"Puesto", Int64.Type}}, "en-US")
in Tipos