let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RmVjaGEsUmVhbCxQcm9ub3N0aWNvLExJOTUsTFM5NSxNb2RlbG8NCjIwMTMtMDItMDEsMTE4MDY4LjM2MzUyODQwMDg4LCwsLA0KMjAxMy0wMy0wMSwxMTM3NjMuNjAyMDkzNTQ4LCwsLA0KMjAxMy0wNC0wMSwxMDEzMjkuNDY1MTM1NzEzNywsLCwNCjIwMTMtMDUtMDEsODU4MDMuMTUwNTUzODUyNDUsLCwsDQoyMDEzLTA2LTAxLDg0MTUyLjEzOTU5NjM2MzUsLCwsDQoyMDEzLTA3LTAxLDg0OTIzLjI1ODY1NDA5MjE2LCwsLA0KMjAxMy0wOC0wMSw4MDc0My4wOTI5NzU5MDYyNywsLCwNCjIwMTMtMDktMDEsNzYyNDkuODI2NDk3MTAyNjQsLCwsDQoyMDEzLTEwLTAxLDc0NTkyLjA0NTA1NzM4MTI3LCwsLA0KMjAxMy0xMS0wMSw4NDA0MS4xNzUzNDkwMjUwNywsLCwNCjIwMTMtMTItMDEsOTI1NzcuMDQyNjQzMzEyNDIsLCwsDQoyMDE0LTAxLTAxLDk5NzE2LjQyOTM4OTk2NjUyLCwsLA0KMjAxNC0wMi0wMSw5NzY2MC42MzUxNzQ3MDI2NiwsLCwNCjIwMTQtMDMtMDEsOTcwMzIuMTM2MTEyNzMzNzEsLCwsDQoyMDE0LTA0LTAxLDg4NzUwLjI4MjI1MzgxMDE5LCwsLA0KMjAxNC0wNS0wMSw3NzgzMC4zOTI4MjAxNzcwOCwsLCwNCjIwMTQtMDYtMDEsNzMyNzcuNTkyMTYwNDY1OTcsLCwsDQoyMDE0LTA3LTAxLDc0NjA5LjcyODY0MzM0Njk5LCwsLA0KMjAxNC0wOC0wMSw3NTgxNy43MzIwODM5NzMxLCwsLA0KMjAxNC0wOS0wMSw3NjU1OS41NzYxNDIwNTk5LCwsLA0KMjAxNC0xMC0wMSw4NjM0MC4yMDcwMzg1NTM0MywsLCwNCjIwMTQtMTEtMDEsOTQ4MDUuMTA3MzU1ODU5NDQsLCwsDQoyMDE0LTEyLTAxLDk4MDM2LjQ5MjI4MzYzMDUyLCwsLA0KMjAxNS0wMS0wMSw5OTc1NC45NTM1MjY1NzY0OSwsLCwNCjIwMTUtMDItMDEsMTAzODEwLjI3MTU0MTc4MTQsLCwsDQoyMDE1LTAzLTAxLDk2OTkzLjIxMjg2ODYxNTI2LCwsLA0KMjAxNS0wNC0wMSw4NDM0NS41ODg4ODQ4MDk5OSwsLCwNCjIwMTUtMDUtMDEsNjk2NzYuMDUzNjg4NzUzNywsLCwNCjIwMTUtMDYtMDEsNjg5OTEuNzY2MzU2OTU0NDUsLCwsDQoyMDE1LTA3LTAxLDcxMDk2LjQyNDE1NzQyODc5LCwsLA0KMjAxNS0wOC0wMSw3Mjc2NC4zOTM5Mzk3MDU5OSwsLCwNCjIwMTUtMDktMDEsNzcxMjYuNjIxNjEyMTM0NTgsLCwsDQoyMDE1LTEwLTAxLDgxMjc3LjQzNjU2MTAxMzkyLCwsLA0KMjAxNS0xMS0wMSw5NTQ0Ni4zMTQ0ODUyMjY3NiwsLCwNCjIwMTUtMTItMDEsOTkwMzYuMDA2MzQ1OTY2MzQsLCwsDQoyMDE2LTAxLTAxLDEwNDg0MS44NTc5NjgyNzYzLCwsLA0KMjAxNi0wMi0wMSwxMDIyMTYuMjA5OTUwNzQwNiwsLCwNCjIwMTYtMDMtMDEsMTAxMzE0LjEyMDE3NTE4MTYsLCwsDQoyMDE2LTA0LTAxLDkyMDEzLjEzMTc0MDg3NzIsLCwsDQoyMDE2LTA1LTAxLDgyMTA0LjM0NjAzMDMxNTA1LCwsLA0KMjAxNi0wNi0wMSw3OTIyMC44MzEyMjc3MDI4MywsLCwNCjIwMTYtMDctMDEsODE0ODYuOTgzNjMzOTUzNDEsLCwsDQoyMDE2LTA4LTAxLDgyMTE0LjA3NDI0MDg2NDUsLCwsDQoyMDE2LTA5LTAxLDgxODU2LjcyMDIyMDkzOTc0LCwsLA0KMjAxNi0xMC0wMSw4NTY0OC42OTU3NDg4MzMzOSwsLCwNCjIwMTYtMTEtMDEsOTY2NDcuNTAxMDcyNDEzOTYsLCwsDQoyMDE2LTEyLTAxLDk4NzQ5LjA3ODE4NDE3NDM2LCwsLA0KMjAxNy0wMS0wMSwxMDA0MjQuODUzMTAyODIyODgsLCwsDQoyMDE3LTAyLTAxLDEwNDQyMy4yOTY4MzIzNTgyLCwsLA0KMjAxNy0wMy0wMSwxMDIxODguMDM1OTY2NDE2NCwsLCwNCjIwMTctMDQtMDEsOTA4OTEuNTU4NjQxODY2NiwsLCwNCjIwMTctMDUtMDEsNzUwNzcuNTg4MjYyNTIyMjMsLCwsDQoyMDE3LTA2LTAxLDc0ODU1LjY5NzUwMDY3MDc4LCwsLA0KMjAxNy0wNy0wMSw3ODc3OC42ODUwNDc2NTM4MSwsLCwNCjIwMTctMDgtMDEsODA5NzIuODg0MTE2NTU2NDIsLCwsDQoyMDE3LTA5LTAxLDgyOTQ4LjczNjcxODk5Nzk5LCwsLA0KMjAxNy0xMC0wMSw5MDE1Ni4wNTM3MjExMDExNCwsLCwNCjIwMTctMTEtMDEsMTA1MzYyLjM4NjMxNjE4MDQsLCwsDQoyMDE3LTEyLTAxLDEwNTU4Ni43NzMwODcxNzcsLCwsDQoyMDE4LTAxLTAxLDEwMzkyMS4xMDI3Mzg5NTAzLCwsLA0KMjAxOC0wMi0wMSw5NDg0Ny44MjgxOTQwNjk3MiwsLCwNCjIwMTgtMDMtMDEsOTczODQuODEzMzkwMDE1MTYsLCwsDQoyMDE4LTA0LTAxLDg4ODA3LjQyMjk4NjMyNzU3LCwsLA0KMjAxOC0wNS0wMSw3NzcxNS4zMzEyOTQxODEyOSwsLCwNCjIwMTgtMDYtMDEsNzI0MDEuNDY4NDU5NzY0ODcsLCwsDQoyMDE4LTA3LTAxLDc4NDI5LjY2ODMzOTc0NTkxLCwsLA0KMjAxOC0wOC0wMSw3MjI4My4xOTEzMDUzMDYyLCwsLA0KMjAxOC0wOS0wMSw3NjYwNC41NjEzNzU4MTY4MywsLCwNCjIwMTgtMTAtMDEsODQzMDcuOTUxOTk1OCwsLCwNCjIwMTgtMTEtMDEsMTA2MzMwLjA5NDY3MTMyNTEsLCwsDQoyMDE4LTEyLTAxLDExMTI0OC44MzQ0ODY2NTU3LCwsLA0KMjAxOS0wMS0wMSwxMDk1MjMuNjI0ODc5MTAyODgsLCwsDQoyMDE5LTAyLTAxLDk2MTUyLjQ3MjQ5MTAxMjI1LCwsLA0KMjAxOS0wMy0wMSw4OTY1NC44MzcxODkzNDg0OSwsLCwNCjIwMTktMDQtMDEsODIxNzIuODQyMjQ2NDUxNjksLCwsDQoyMDE5LTA1LTAxLDc4NjY5LjYyNjE3NTc1MTgyLCwsLA0KMjAxOS0wNi0wMSw4MDE3My44NjUyNTc5NzA5NiwsLCwNCjIwMTktMDctMDEsODU1ODQuOTU0MjczNTQ2MzYsLCwsDQoyMDE5LTA4LTAxLDgyNjYyLjE1MzcxOTk3NTM4LCwsLA0KMjAxOS0wOS0wMSw4NTAyNS4wODEwMjA1MTczMywsLCwNCjIwMTktMTAtMDEsOTM2NTEuODU3MDQ0NDU0NjIsLCwsDQoyMDE5LTExLTAxLDEwNjk0MC4yOTYyNjg0NzYxNiwsLCwNCjIwMTktMTItMDEsMTAzNTIwLjQxOTUzMDkyNTU0LCwsLA0KMjAyMC0wMS0wMSw5NDc4Ny4wODg3MDAxNDczNiwsLCwNCjIwMjAtMDItMDEsODcxMzAuMzQ2ODY5MjI0NDIsLCwsDQoyMDIwLTAzLTAxLDc0MzI5LjEwMjc3Mzk0NDY0LCwsLA0KMjAyMC0wNC0wMSw1NzI0OC4wMTM5NTgxNzU3NzYsLCwsDQoyMDIwLTA1LTAxLDUwNzUzLjk4NDA3ODczNjc3LCwsLA0KMjAyMC0wNi0wMSw0OTQyNS4zMDk0MDI3NzY1MywsLCwNCjIwMjAtMDctMDEsNDkyMTcuMTkxNzU5MjAzNzUsLCwsDQoyMDIwLTA4LTAxLDU3NjA1LjkwMTkxOTQ2NzY5NSwsLCwNCjIwMjAtMDktMDEsNjUyNjQuOTU4NTgzNTM2Mjk2LCwsLA0KMjAyMC0xMC0wMSw3NzYzOC44NjcyNDA5NzU5NSwsLCwNCjIwMjAtMTEtMDEsODY5MDUuMzg1MTgyMTkzMTUsLCwsDQoyMDIwLTEyLTAxLDkwMzk1LjY1MDk5NDQ3NTA2LCwsLA0KMjAyMS0wMS0wMSw5NDY3MS42MjI3MDk2Mzc2NCwsLCwNCjIwMjEtMDItMDEsODcxMTIuMTYwNDU4ODYxMjEsLCwsDQoyMDIxLTAzLTAxLDg0MDM3LjI5NDQ3MjM4MzQsLCwsDQoyMDIxLTA0LTAxLDcxNTgzLjk3NTM3NTYzMDYzLCwsLA0KMjAyMS0wNS0wMSw2NjE1Mi45Njk4OTk5OTQ0OCwsLCwNCjIwMjEtMDYtMDEsNjc1MzguNDUwOTAwMjA3MSwsLCwNCjIwMjEtMDctMDEsNjcyMTUuMzY3MTU4MTQ3OTYsLCwsDQoyMDIxLTA4LTAxLDcwNTcxLjE5NDk0NzMxOTAzLCwsLA0KMjAyMS0wOS0wMSw2ODg2Ny42NDcwNTk2MDkyNSwsLCwNCjIwMjEtMTAtMDEsNzM2NjAuNzU4NDM3NTM2OTUsLCwsDQoyMDIxLTExLTAxLDgzNzIwLjE5NzM4NDU5NDM0LCwsLA0KMjAyMS0xMi0wMSw4NjcxNy4yMzc2Mzc4OTUzMywsLCwNCjIwMjItMDEtMDEsODg5NzEuMjk1NzE3MjIwOTQsLCwsDQoyMDIyLTAyLTAxLDgyOTY2LjcwMDAwNzE5NzE0LCwsLA0KMjAyMi0wMy0wMSw4NDA1MC44MjU3OTU3MzgzNSwsLCwNCjIwMjItMDQtMDEsNzkzNTMuNjE3MjE4MDkyOTcsLCwsDQoyMDIyLTA1LTAxLDcxNTY0LjY5OTM5NzUwMzAzLCwsLA0KMjAyMi0wNi0wMSw3MTYwMy4yNDQ3MjE2MDgyLCwsLA0KMjAyMi0wNy0wMSw3MjIzMy42ODA1NDgyNTE4NCwsLCwNCjIwMjItMDgtMDEsNzYyMjEuNTg5MjY3MTI1ODIsLCwsDQoyMDIyLTA5LTAxLDc1NTgwLjE0MjUzOTU1ODIyLCwsLA0KMjAyMi0xMC0wMSw3Nzc2MC4zNjc4Nzc0MzU5NiwsLCwNCjIwMjItMTEtMDEsODU3NDguNjAyNjQwOTcwMDksLCwsDQoyMDIyLTEyLTAxLDg4Mjk1Ljc1NTQ2MDIwNzUsLCwsDQoyMDIzLTAxLTAxLDkxMjA3LjA4OTgxODQwODEyLCwsLA0KMjAyMy0wMi0wMSw4NzYxMy4zMDEyMzQzMTAzMywsLCwNCjIwMjMtMDMtMDEsODYxNjcuMTQ5NDA3MjY0OTgsLCwsDQoyMDIzLTA0LTAxLDc2MTI4LjM0MjczNTUwODQ2LCwsLA0KMjAyMy0wNS0wMSw3MDQ3My45NDQ4OTEyOTc1MiwsLCwNCjIwMjMtMDYtMDEsNjYzMjguNTA3NDk2ODY0ODMsLCwsDQoyMDIzLTA3LTAxLDY4MjE2LjY5NDEwNjQxMzQ0LCwsLA0KMjAyMy0wOC0wMSw3MDc4Mi44NDE5MzQxMTAxLCwsLA0KMjAyMy0wOS0wMSw3NTQ4NS43NDI5MTY3MzA3NCwsLCwNCjIwMjMtMTAtMDEsODA4MzUuNDAyNzUwOTI3OCwsLCwNCjIwMjMtMTEtMDEsODE5NjIuNzc1OTY5NjA1NzYsLCwsDQoyMDIzLTEyLTAxLDgzMzY5LjQyOTg3NTk4ODgzLCwsLA0KMjAyNC0wMS0wMSw3OTc2My41ODk4Mjg2MzQ5OCwsLCwNCjIwMjQtMDItMDEsNzkxNDcuMTI0MDEwNzYwMDYsLCwsDQoyMDI0LTAzLTAxLDc0OTk5Ljc0NTY2MzgwNjg0LCwsLA0KMjAyNC0wNC0wMSw2Njk3OC40ODI3NTE0NDg5NCwsLCwNCjIwMjQtMDUtMDEsNjMyMTcuODQyNzg1MjQzNDMsLCwsDQoyMDI0LTA2LTAxLDY0NDYyLjIxNjM3ODcxNDMzLCwsLA0KMjAyNC0wNy0wMSw2ODgxNS4xNTg4NDIwNjE0NiwsLCwNCjIwMjQtMDgtMDEsNzA1NzQuNzk1MzAwNjY3NjEsLCwsDQoyMDI0LTA5LTAxLDY3NjEzLjI2NzEyMzM4MjQ3LCwsLA0KMjAyNC0xMC0wMSw3ODE3MS4zMDc0OTQyODgxNSwsLCwNCjIwMjQtMTEtMDEsODY5NTguNTg5ODQ0MTkyMjksLCwsDQoyMDI0LTEyLTAxLDg5ODk5LjA4MjA4MTIwNjU1LCwsLA0KMjAyNS0wMS0wMSw4MTIxMy43MTczODg2Mjg1LCwsLA0KMjAyNS0wMi0wMSw3NzA3My40NjAyODQxNjU3OSwsLCwNCjIwMjUtMDMtMDEsNzQ3MDcuMzA3NjM5NzIwMTEsLCwsDQoyMDI1LTA0LTAxLDcwNjAxLjg1ODc5NjM0MTk2LCwsLA0KMjAyNS0wNS0wMSw2NTc5OS4yODY4NDQ3MjA5NSwsLCwNCjIwMjUtMDYtMDEsNjM1MzYuMTM0NjI3MTcyNjgsLCwsDQoyMDI1LTA3LTAxLDY2NTY5Ljk4NTA5NzA0MTgsLCwsDQoyMDI1LTA4LTAxLDY3NDc1LjQxMjg0NTIwOTY5LCwsLA0KMjAyNS0wOS0wMSw3MDI0OC40MTExNjA2ODc3NiwsLCwNCjIwMjUtMTAtMDEsNzU5MzcuNDk5NTI5MjA0NCwsLCwNCjIwMjUtMTEtMDEsODA4MzIuNzEzNTc4NDE5NzUsLCwsDQoyMDI1LTEyLTAxLDgxODg3LjMzMDQ1MTA1NzgzLCwsLA0KMjAyNi0wMS0wMSw3OTY0OC45NTIyNDE3MzE1MywsLCwNCjIwMjYtMDItMDEsNzg4NTIuNzM0ODcxNjExMjIsLCwsDQoyMDI2LTAzLTAxLDczMDg0LjM3OTk0NTAyNzI2LCwsLA0KMjAyNi0wNC0wMSw2NzA3OS4wMjAwNDY3NTY4NCwsLCwNCjIwMjYtMDUtMDEsNjM2OTAuMTA1NDkwNjczMjgsLCwsDQoyMDI2LTA2LTAxLDYzNzk3LjA0MjY4NzAwNTg1LCwsLA0KMjAyNi0wNy0wMSw2NzY5OS40OTczNzE5NzM5OCwsLCwNCjIwMjYtMDgtMDEsLDYyMzIyLjA0NjAwNTU5OTI3LDQ0NTY1Ljc3MzQ0MjU3OTYyLDc2ODgzLjE4MDc1OTgxMDM2LFJlZ3Jlc2nDs24gZXN0YWNpb25hbA0KMjAyNi0wOS0wMSwsNjYxNzIuNTQ3MDM3NTM5NzksNDc0NTkuODQ3MTMzODM3NDgsODExMjMuNDg2ODA3OTUzODcsUmVncmVzacOzbiBlc3RhY2lvbmFsDQoyMDI2LTEwLTAxLCw3MTc1MS41MjQzMjQ0Mjc3NSw1MzI0Mi45NzY2MjkxNjU4Myw4NjQzOC4zMjUwMTUzNDA5OCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwNCjIwMjYtMTEtMDEsLDc4MjA1LjU4NTg4ODA4ODQ4LDU5NTcwLjc2MTEwNzMwNCw5Mjc3My41OTUxMjgxMzM4MyxSZWdyZXNpw7NuIGVzdGFjaW9uYWwNCjIwMjYtMTItMDEsLDgzNDYzLjc5MjEwMjY0NDk2LDY0NjcwLjA3OTQ2Mjk3MzgxNiw5ODIwNS42NTk4NzEyMzM1NCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwNCjIwMjctMDEtMDEsLDg1MDk5LjA0OTQ4NDM5ODU3LDY1OTk5LjcwMzU5NDk3NDk2LDEwMDA4Ni45OTM5MTE1MTQyMyxSZWdyZXNpw7NuIGVzdGFjaW9uYWwNCjIwMjctMDItMDEsLDgxOTYxLjUxNzk1MzE3MzQ2LDY0MzM5LjE2MTM0MzI4MjYwNSw5NjgxNS4wOTU4MDA2MjQyNCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwNCg==", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\SerieForecast.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type datetime}, {"Real", type number}, {"Pronostico", type number}, {"LI95", type number}, {"LS95", type number}, {"Modelo", type text}}, "en-US")
in Tipos