let
    Binario = if RutaDatos = "" then Binary.FromText("77u/RmVjaGEsRXRhcGEsTW9kZWxvLFJlYWwsUHJlZGljaG8sTEk5NSxMUzk1DQoyMDI0LTAxLTAxLFNlbGVjY2nDs24gMjAyNCxJbmdlbnVvIGVzdGFjaW9uYWwsNzk3NjMuNTg5ODI4NjM0OTgsOTEyMDcuMDg5ODE4NDA4MTMsNjQ1NjIuMTg0NjEwOTc5ODQsMTA2ODEzLjc4ODEyNTQ0OTc1DQoyMDI0LTAyLTAxLFNlbGVjY2nDs24gMjAyNCxJbmdlbnVvIGVzdGFjaW9uYWwsNzkxNDcuMTI0MDEwNzYwMDYsODc2MTMuMzAxMjM0MzEwMzMsNjM4MjcuNzg2MzIzMzg5NDEsMTA0MjgzLjAyMzk0NTE1NDgNCjIwMjQtMDMtMDEsU2VsZWNjacOzbiAyMDI0LEluZ2VudW8gZXN0YWNpb25hbCw3NDk5OS43NDU2NjM4MDY4NCw4NjE2Ny4xNDk0MDcyNjQ5OCw2MjM4MS42MzQ0OTYzNDQwNiwxMDI4MzYuODcyMTE4MTA5NDYNCjIwMjQtMDQtMDEsU2VsZWNjacOzbiAyMDI0LEluZ2VudW8gZXN0YWNpb25hbCw2Njk3OC40ODI3NTE0NDg5NCw3NjEyOC4zNDI3MzU1MDg0Niw0OTQ4My40Mzc1MjgwODAxNyw5Mjc5OC4wNjU0NDYzNTI5NA0KMjAyNC0wNS0wMSxTZWxlY2Npw7NuIDIwMjQsSW5nZW51byBlc3RhY2lvbmFsLDYzMjE3Ljg0Mjc4NTI0MzQyNSw3MDQ3My45NDQ4OTEyOTc1Miw0MzgyOS4wMzk2ODM4NjkyMyw4NzE0My42Njc2MDIxNDINCjIwMjQtMDYtMDEsU2VsZWNjacOzbiAyMDI0LEluZ2VudW8gZXN0YWNpb25hbCw2NDQ2Mi4yMTYzNzg3MTQzMyw2NjMyOC41MDc0OTY4NjQ4MywzOTY4My42MDIyODk0MzY1NCw4Mjk5OC4yMzAyMDc3MDkzDQoyMDI0LTA3LTAxLFNlbGVjY2nDs24gMjAyNCxJbmdlbnVvIGVzdGFjaW9uYWwsNjg4MTUuMTU4ODQyMDYxNDYsNjgyMTYuNjk0MTA2NDEzNDQsNDE1NzEuNzg4ODk4OTg1MTU2LDg0ODg2LjQxNjgxNzI1NzkxDQoyMDI0LTA4LTAxLFNlbGVjY2nDs24gMjAyNCxJbmdlbnVvIGVzdGFjaW9uYWwsNzA1NzQuNzk1MzAwNjY3NjEsNzA3ODIuODQxOTM0MTEwMSw0NDEzNy45MzY3MjY2ODE4MSw4NjM4OS41NDAyNDExNTE3MQ0KMjAyNC0wOS0wMSxTZWxlY2Npw7NuIDIwMjQsSW5nZW51byBlc3RhY2lvbmFsLDY3NjEzLjI2NzEyMzM4MjQ3LDc1NDg1Ljc0MjkxNjczMDc0LDQ4ODQwLjgzNzcwOTMwMjQ1NCw5MTA5Mi40NDEyMjM3NzIzNg0KMjAyNC0xMC0wMSxTZWxlY2Npw7NuIDIwMjQsSW5nZW51byBlc3RhY2lvbmFsLDc4MTcxLjMwNzQ5NDI4ODE1LDgwODM1LjQwMjc1MDkyNzgsNTQxOTAuNDk3NTQzNDk5NTEsOTY0NDIuMTAxMDU3OTY5NDENCjIwMjQtMTEtMDEsU2VsZWNjacOzbiAyMDI0LEluZ2VudW8gZXN0YWNpb25hbCw4Njk1OC41ODk4NDQxOTIyOSw4NTc0OC42MDI2NDA5NzAwOSw1OTEwMy42OTc0MzM1NDE4LDEwMjQxOC4zMjUzNTE4MTQ1Ng0KMjAyNC0xMi0wMSxTZWxlY2Npw7NuIDIwMjQsSW5nZW51byBlc3RhY2lvbmFsLDg5ODk5LjA4MjA4MTIwNjU1LDg4Mjk1Ljc1NTQ2MDIwNzUsNjQ1MTAuMjQwNTQ5Mjg2NTcsMTA0OTY1LjQ3ODE3MTA1MTk3DQoyMDI0LTAxLTAxLFNlbGVjY2nDs24gMjAyNCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsNzk3NjMuNTg5ODI4NjM0OTgsOTIwODIuNDQ0MTk0MzU0NDIsNzIyNjMuNjk5MTc2NDY3NjYsMTA3Mjc4LjYzMDA1OTM3NDM3DQoyMDI0LTAyLTAxLFNlbGVjY2nDs24gMjAyNCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsNzkxNDcuMTI0MDEwNzYwMDYsODkzNDkuMjcwOTc2MTA4NTMsNzAyMDQuMDMyMzg3MTQzNywxMDQ2NzEuNjAxMDc0MzkwNDINCjIwMjQtMDMtMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw3NDk5OS43NDU2NjM4MDY4NCw4MjIwMC44ODcxMTk3MTMzOCw2MzA2Mi43MjQ3ODcwMDQ5OSw5NzgwOS40OTk4NDQ3NTg1Mg0KMjAyNC0wNC0wMSxTZWxlY2Npw7NuIDIwMjQsUmVncmVzacOzbiBlc3RhY2lvbmFsLDY2OTc4LjQ4Mjc1MTQ0ODk0LDczNjAwLjg5Mjc4ODUxMzEsNTQ4MjQuODY3NDU1MDY1NjIsODg4NTguMjI5Njk1NTc2NTgNCjIwMjQtMDUtMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw2MzIxNy44NDI3ODUyNDM0MjUsNjY3NzguNTA0NDEwNTg3ODUsNDgwMDEuNDk2NTI3MTU0NDcsODIwMjUuNjAyMjk4MDMxMzkNCjIwMjQtMDYtMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw2NDQ2Mi4yMTYzNzg3MTQzMyw2MzQwNi4wODkzMDk4NjE2Myw0NDc3NS41OTI3MTA0NjAyMTYsNzg0NzQuOTUwMDAwNTExMzcNCjIwMjQtMDctMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw2ODgxNS4xNTg4NDIwNjE0Niw2MzI3NC4zOTc4MjE5MjE1Myw0NDAyOS4yNTYxMTkxMTM3MSw3ODI5OS43MzM2ODI5MDMxNg0KMjAyNC0wOC0wMSxTZWxlY2Npw7NuIDIwMjQsUmVncmVzacOzbiBlc3RhY2lvbmFsLDcwNTc0Ljc5NTMwMDY2NzYxLDY1NDI5LjE3MjU5NzEyOTEsNDU5NTQuODY4OTEwOTk5NDk2LDc5NzAxLjgwNDc1NjkxNjg3DQoyMDI0LTA5LTAxLFNlbGVjY2nDs24gMjAyNCxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsNjc2MTMuMjY3MTIzMzgyNDcsNjkzODQuMDQwNTIxNjI5OTcsNTAwNDEuODEyMzQ5NTg1NzgsODQyNDYuNjY5MDk1NDE5NzENCjIwMjQtMTAtMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw3ODE3MS4zMDc0OTQyODgxNSw3NTEyNy40OTQ0MTA3MTgsNTU5NDYuMzcxMDc3NjU2OTYsODk5NDUuOTk0Mjk2NDY5NDUNCjIwMjQtMTEtMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw4Njk1OC41ODk4NDQxOTIyOSw4MjA0NS40MzUzMjUxNjkyNCw2MzA5Ni41Njk0MzQ1NTE3MDQsOTcyMDMuMzUyNzU1MTAwNzkNCjIwMjQtMTItMDEsU2VsZWNjacOzbiAyMDI0LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw4OTg5OS4wODIwODEyMDY1NSw4ODEyOC41MjA0NTEyNzgwNiw2ODY2Ny40MzQzMjYzNjUzMSwxMDM3ODYuNzQ4MjExNzI3MTYNCjIwMjUtMDEtMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxJbmdlbnVvIGVzdGFjaW9uYWwsODEyMTMuNzE3Mzg4NjI4NSw3OTc2My41ODk4Mjg2MzQ5OCw1NjM4OC42MDgyMjU0MTQ2LDk1NzgwLjgyMTQ0MzM3NzE1DQoyMDI1LTAyLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDc3MDczLjQ2MDI4NDE2NTc5LDc5MTQ3LjEyNDAxMDc2MDA2LDU1NzcyLjE0MjQwNzUzOTY4LDk1MTY0LjM1NTYyNTUwMjIxDQoyMDI1LTAzLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDc0NzA3LjMwNzYzOTcyMDExLDc0OTk5Ljc0NTY2MzgwNjg0LDUxNjI0Ljc2NDA2MDU4NjQ2LDkxMDE2Ljk3NzI3ODU0ODk5DQoyMDI1LTA0LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDcwNjAxLjg1ODc5NjM0MTk2LDY2OTc4LjQ4Mjc1MTQ0ODk0LDQzNjAzLjUwMTE0ODIyODU2LDgyOTk1LjcxNDM2NjE5MTENCjIwMjUtMDUtMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxJbmdlbnVvIGVzdGFjaW9uYWwsNjU3OTkuMjg2ODQ0NzIwOTUsNjMyMTcuODQyNzg1MjQzNDI1LDM5ODQyLjg2MTE4MjAyMzA0LDc5MjM1LjA3NDM5OTk4NTU4DQoyMDI1LTA2LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDYzNTM2LjEzNDYyNzE3MjY4LDY0NDYyLjIxNjM3ODcxNDMzLDQxMDg3LjIzNDc3NTQ5Mzk1LDgwNDc5LjQ0Nzk5MzQ1NjQ5DQoyMDI1LTA3LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDY2NTY5Ljk4NTA5NzA0MTgsNjg4MTUuMTU4ODQyMDYxNDYsNDUzNjguNjkyNDgxNDI4NDE0LDg0ODMyLjM5MDQ1NjgwMzYxDQoyMDI1LTA4LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDY3NDc1LjQxMjg0NTIwOTY5LDcwNTc0Ljc5NTMwMDY2NzYxLDQ3MTk5LjgxMzY5NzQ0NzIzLDg3NjU1LjA1MTMxOTIxMjYyDQoyMDI1LTA5LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDcwMjQ4LjQxMTE2MDY4Nzc2LDY3NjEzLjI2NzEyMzM4MjQ3LDQxMzc4Ljg5NTIyMzY1NDcyLDg0NjkzLjUyMzE0MTkyNzQ4DQoyMDI1LTEwLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDc1OTM3LjQ5OTUyOTIwNDQsNzgxNzEuMzA3NDk0Mjg4MTUsNTE5MzYuOTM1NTk0NTYwNDA0LDk1MjUxLjU2MzUxMjgzMzE2DQoyMDI1LTExLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDgwODMyLjcxMzU3ODQxOTc1LDgxOTYyLjc3NTk2OTYwNTc2LDU4NTE2LjMwOTYwODk3MjcyLDk3OTgwLjAwNzU4NDM0NzkxDQoyMDI1LTEyLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsSW5nZW51byBlc3RhY2lvbmFsLDgxODg3LjMzMDQ1MTA1NzgzLDgzMzY5LjQyOTg3NTk4ODgzLDU5OTk0LjQ0ODI3Mjc2ODQ1LDk5Mzg2LjY2MTQ5MDczMQ0KMjAyNS0wMS0wMSxQcnVlYmEgaW5kZXBlbmRpZW50ZSAyMDI1LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw4MTIxMy43MTczODg2Mjg1LDg5MDkwLjQ0MTY3MDgzMDMzLDY4OTkzLjA4NTAwMTQwNDEsMTAzODE2Ljk0MTMzMDAwNjENCjIwMjUtMDItMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsNzcwNzMuNDYwMjg0MTY1NzksODYyNjIuNzk2MjIyMDQ5NTEsNjcyMTIuNjUyMDA5MjE3ODEsMTAxMzgxLjkzNzQzMzE2ODc2DQoyMDI1LTAzLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsUmVncmVzacOzbiBlc3RhY2lvbmFsLDc0NzA3LjMwNzYzOTcyMDExLDc5MjQwLjQ4NDY4MDMwNjE1LDYwMjk0Ljk3MzkxNDM3ODA0LDk0Mzg5LjA5OTYyMzg0NDcxDQoyMDI1LTA0LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsUmVncmVzacOzbiBlc3RhY2lvbmFsLDcwNjAxLjg1ODc5NjM0MTk2LDcwOTI3LjIwMzc2NTQ3MTU0LDUyMzU2LjczMDk1NzE2MDQ5LDg2MjA2Ljk0NjMxODQ3NTQ3DQoyMDI1LTA1LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsUmVncmVzacOzbiBlc3RhY2lvbmFsLDY1Nzk5LjI4Njg0NDcyMDk1LDY0NDM4LjQwODc5NzYwNjcxLDQ1Njk4LjU2NzkzODM0MDk3LDc5MjY0LjU1OTYzODY5MzA0DQoyMDI1LTA2LTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsUmVncmVzacOzbiBlc3RhY2lvbmFsLDYzNTM2LjEzNDYyNzE3MjY4LDYxMzQzLjc2NDM3Mjc3NTY0LDQyNzQ3LjcyODk4NDcwMDcxLDc2NTIyLjg0MjgyNzA1NTkNCjIwMjUtMDctMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsNjY1NjkuOTg1MDk3MDQxOCw2MTM4MC43MDk2MDI5MjI4Miw0MjY5OC4yMjcyOTM3NTQyOSw3NjQ5Ni4wMTU0NTM2MzE3Mw0KMjAyNS0wOC0wMSxQcnVlYmEgaW5kZXBlbmRpZW50ZSAyMDI1LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw2NzQ3NS40MTI4NDUyMDk2OSw2MzU4MS43MzIyODE2OTg3Myw0NTUxMi4xMjExNzY2NTYyOSw3ODg1NC4yNjkyMDQ0OTk5OQ0KMjAyNS0wOS0wMSxQcnVlYmEgaW5kZXBlbmRpZW50ZSAyMDI1LFJlZ3Jlc2nDs24gZXN0YWNpb25hbCw3MDI0OC40MTExNjA2ODc3Niw2NzQ1Ni4zNzg1ODU5NDA4Miw0ODg5My4zMDk0MDc3MDY4Niw4MjUyOS43NjYxMDA0NDc1DQoyMDI1LTEwLTAxLFBydWViYSBpbmRlcGVuZGllbnRlIDIwMjUsUmVncmVzacOzbiBlc3RhY2lvbmFsLDc1OTM3LjQ5OTUyOTIwNDQsNzI5ODguNTE0MTgwNzMyNTQsNTQzNjUuMjYyMzg1NzYwMDQsODgwMjguMTM1ODQ2MjAwNDcNCjIwMjUtMTEtMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsODA4MzIuNzEzNTc4NDE5NzUsNzk1ODMuNzI2MjEzNTA4NDMsNjA0MzYuNzA3MzEzNDYxMDQsOTQ5NTcuNzkxMTU3MDQxMjUNCjIwMjUtMTItMDEsUHJ1ZWJhIGluZGVwZW5kaWVudGUgMjAyNSxSZWdyZXNpw7NuIGVzdGFjaW9uYWwsODE4ODcuMzMwNDUxMDU3ODMsODUzMDUuODMwMTcwNzQ3MTEsNjY3NjQuNTA0Mzg4Mzg0NjEsMTAwMDIyLjQxNzc5MDkyMjgNCg==", BinaryEncoding.Base64) else File.Contents(RutaDatos & "\ValidacionForecast.csv"),
    Csv = Csv.Document(Binario,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Csv,[PromoteAllScalars=true]),
    Tipos = Table.TransformColumnTypes(Encabezados, {{"Fecha", type datetime}, {"Etapa", type text}, {"Modelo", type text}, {"Real", type number}, {"Predicho", type number}, {"LI95", type number}, {"LS95", type number}}, "en-US")
in Tipos